### ISSUE TITLE
Paticka na malom displeji orezava obsah

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#105]
Ked ma paticka viac ako 2 riadky, orezava obsah (pretoze `body` ma spodny margin fixne 4 rem).

**Comment by repli2dev** [comment]
Mozna bude stacit sat padding bottom body.

J.

16. 8. 2019 v 8:42, Martin Ukrop <notifications@github.com>:

**Comment by mukrop** [comment]
@repli2dev: Nerozumiem, co navrhujes. Snazil som sa vygooglit nejaky "sat padding", ale nenasiel som nic take. Internet odporuca pouzit flexbox, ale to mi pride ako dost prekopavanie velkosti, takze som to zatial vyriesil neflexibilne jednoduchym podmienenym paddingom (kedze aktualne su len dve moznosti velkosti paticky).

**Comment by repli2dev** [comment]
@mukrop jo padding-bottom bylo to zamýšlené... zbytek je nějaký artefakt psaní na mobilu.
