### ISSUE TITLE
Dva a více zdrojů dat

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#107]
Některé grafiky (např koncentrace CO2 - bacha vyvíjí se v samostatné větvi) obsahují více zdrojů. Chtělo by to nějak vyřešit odkazování na původní data - buď více tlačítek(každé pro jinou datovou sadu), nebo rozbalení tlačítka, nebo...??

Neím jak moc je to komplikace... priorita to asi není, protože stejně na původní data kliká málokdo, ale časem by to chtělo spravit.

**Comment by crysman** [comment]
@mukrop čekám na prerekvizitu array/doubles a rename "src" na "data-*"

**Comment by crysman** [comment]
podle mě je toto úspěšně hotovo ([pull#159](https://github.com/mukrop/faktaoklimatu/pull/159)), zavírám
