### ISSUE TITLE
Vyriesit problem s fontom v navbare

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#109]
Font pouzity v navigacnej liste ma zvlastne vyzerajuce tucne ů (vidno po nascrollovani na sekciu o autoroch).

**Comment by repli2dev** [comment]
U mě (FF na OS X) to selhává na CORS, takže font se vůbec nenačte a je tam jen výchozí sans-serif...

**Comment by repli2dev** [comment]
Hmm, problém u mě s načtením fontu je dán výchozí blokací reklam u FF.

**Comment by repli2dev** [comment]
@mukrop vyzkoušej větev `task-109`, zkusil jsem tam dát lokální font.

**Comment by mukrop** [comment]
U mna funguje dobre v GC aj MFF, povazujem za vyriesene (dik).
