### ISSUE TITLE
Slovník pojmů a diskuse o CO2eq (CDE) vs CO2e a GWP

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#112]
Už fakt potřebujeme - pro věci jako "CO2eq" a "teplotní anomálie" a spousta dalších ustálených spojení.

S Ondrášem jsme se shodli, že bdue lépe mít interní odkazy na náš slovník pojmů, ve kterém až pak budou eventuálně odkazy např. na českou Wiki.

**Comment by crysman** [comment]
teď mě napadlo, že by možná stálo za to udělat šablonu (variable) pro tyto pojmy ala

`{{ slovnik-CO2eq }}` , což by se rozvinulo na `[*CO<sub>2</sub> ekvivalent*](URL_slovnikoveho_pojmu)`

**Comment by ondraspribyla** [comment]
Pojmy pro slovník: 
Jednotky: 
- ppm
- tCO2eq - s příklady a poměry
- výkon a energie : W (kW, MW, GW, TW), kWh, GWh, TWh... s příklady 
  
Instituce:
- IPCC, NASA GISS, NOAA, CHMI, CZECHGLOBE

Jiná slova: 
Antropocén, Biodiverzita, CCS - Carbon Capture and Storage, Emisní scénáře RCP XX (representative  concentration pathways), Radiační působení, ...

**Comment by ondraspribyla** [comment]
Práce na slovníčku v Gdrivu zzde: 
https://docs.google.com/spreadsheets/d/1T0bVi7dl7_auUEDf17G4nnHz7jDrVoy7L-fvhFh4Vbo/edit?usp=sharing

**Comment by mukrop** [comment]
Duplicitne s #19. A prosim skuste rozumne priradovat stitky pri vytvarani novych issues (a pokial sa to tyka novych features alebo deploy, prifavajte aj dany projekt).

**Comment by crysman** [comment]
@mukrop čekám na prerekvizitu push rozpracované větve plz vč. komentářů u metadat thx

**Comment by crysman** [comment]
@mukrop tak jsem se do toho pustil, a narazil jsem na problém - nevím, jak mám zpřístupnit atribut jedné položky :/ - toto mi vyhazuje `nil`:

```
{% assign chmu = site.data.glossary | where: "id","chmu" %}
{{ chmu.name-short | inspect }}
```

přitom toto funguje:
```
{% assign chmu = site.data.glossary | where: "id","chmu" %}
{{ chmu | inspect }}
```

- akorát já chci jen konkrétní atribut, a ne celý objekt :/


jinými slovy: jak co nejlépe, nejčitelněji a nejjednodušeji pro editory zapisovat ta hesla? Osobně jsem si představoval něco jako `{{ site.data.glossary.chmu }}` což by vyhodilo `<a href="$URL_DO_GLOSSARY#ID" title="$NAME-LONG" class="glossaryItem">$NAME-SHORT</a>` - ale nevím, jak to udělat a nechce se mi kvůli tomu učit celý _liquid_... poradíš?

**Comment by mukrop** [comment]
* Pridal som ti tam este prototyp stranky, ktora generuje zoznam hesiel slovnika (zatial bez zasadnejsieho stylu).
* Myslim, ze problem mas v tom, ze vysledkom filtra cez `where` je zoznam, nie prvok (v tvojom pripade velmi casto jednoprvkovy zoznam). Pozri sa na to moje povodne pouzitie v `_includes/glossary.html`.
* Osobne neviem, ci `{{ site.data.glossary.chmu }}` je o tolko lepsie ako `{% include glossary.html id='chmu' %}`. Dlzka velmi podobna, v oboch si musis dohladavat id. Suhlasim, ze to tvoje je o chlp intuitivnejsie, takze ak to pojde nejako systemovo pouzit, urobme to (ale za prasarny typu manualne vkladanie na niekolko miest to nestoji :-P).

**Comment by crysman** [comment]
osobně preferuju tuto variantu, kterou zkouším - akorát že `{{ site.data.glossary.chmu }}` mi nefunguje, nechápu moc proč (ale neumím liquid - takže možná to má nějaké simple vysvětlení? @mukrop )

nicméně, celé to je fuk, protože to, co chci, je nějaký simple způsob pro editory, což bude vyžadovat nějaký pre/postprocessing - představuju si nějaký druh makrování ala `GLOSSARY:chmu` což se .sh skriptem zprocesuje třeba na na `{% include glossary.html id='chmu' %}` - makro jsem schopen udělat, to je simple sed/grep/awk job... - co myslíš?

**Comment by mukrop** [comment]
`{{ site.data.glossary.chmu }}` same o sebe nemoze fungovat, pretoze `site.data.glossary` je pole, ktore nema ziadne dalsie pomenovane atributy (s vynimkou `.size`).

Chapem, ze chceme byt co najintuitivnejsi sposob vkladania slovnikovych veci pre editorov. Makrovanie mi ale pride dost netrivialne -- chceli by sme potom, aby textovy subor zostal bez zmeny, ale aby sa to premietlo do kompilacie aj lokalne aj pre deploy step. A to uplne neviem, kam zaradit (a ty vylepsenie, ktore to prinesie, mi pride relativne male, takze prekopavat kvoli tomu cely build proces je nevhodne).

Osobne by som navrhoval teraz priorotozovat obsah slovnika (ktory tiez nebude vobec trivialny na spisanie) a pripadne to zjednodusit dodatocne, ak sa ukaze, ze to pouzivame casto, je toho vela alebo je to pre editorov narocne.

**Comment by crysman** [comment]
začal jsem makat tady na tomto... je to o dost víc práce, než jsem si myslel, de to pomalu - a to se zabývám jen definicema pojmů a jejich hledáním a konsolidací ve stávajících textech :/

**Comment by crysman** [comment]
první vlaštovka zde https://github.com/mukrop/faktaoklimatu/commit/4fe983709d2d8e4d5b8dd5f5fbead6bd28380c97 - ale je to na dlouho - jakékoliv číslo trvá věčnost, než to ověřím a najdu dostatečně kredibilní zdroje...

**Comment by mukrop** [comment]
Dobra praca! Myslim, ze zo zaciatku tam toho nemusi byt vela. Po napisani tych par pojmov by som navrhol pouzit ich v texte stranok. Potom to zverejnime, dalsie pojmy mozme dopisovat aj potom.

Pridal som ti tam drobne vylepsenie designu a obravil funkcnu chybku, ktora sposobovala, ze vsetky odkazovane hesla boli CHMU.

Dva dotazy:
* Doteraz sme pouzivali CO2eq, ty navrhujes CO2e. Mas na to nejaky dovod (napr. si to vygooglil ako pouzivane v cestine)? Aj v grafikach mame totiz CO2eq a ak sa rozhodneme pre CO2e, bude to treba prerobit aj tam.
* Do nadpisu na stranku slovnicku by som dat za skratke pomenovanie dvojbodku alebo pomlcku a potom dlhe pomenovanie. Aktualne mi pride, ze sa to dlhe pomenovanie straca v tom odstavci textu. Co myslis?

**Comment by crysman** [comment]
ad 1: no @mukrop , zdůvodnění je takovéto:

1. používá se to v [anglických textech na Wiki](https://en.wikipedia.org/wiki/Carbon_dioxide_equivalent), a používá to i [kalkulačka na stránkách MŽP](https://www.mzp.cz/cz/kalkulacka_co2_ekvivalent).
1. pouze "e" umožňuje vyhnout se překladům, protože "q" se v češtině nepoužívá, česky máme "[ekvivalent](http://prirucka.ujc.cas.cz/?slovo=ekvivalent)", nikoli "equivalent". Takže bych musel použít něco jako "ekv" nebo "ek" a obojí mi přijde blbé. Ale vlastně nevím, co je lepší - **otevírám tímto diskusi** @mukrop @ondraspribyla .

ad 2: zkoušel jsem, vypadá blbě u zahraničních dlouhých zkratek typu NASA, kde se to slívá stejně tak - znepřehledňuje to ten přehled jako celek, kukaj: 

![image](https://user-images.githubusercontent.com/5269350/64490458-36852e00-d25d-11e9-80f2-c117852240ee.png)

prostě z toho přestanou "lézt" ty hesla, a celé se to slívá v jeden moloch, byť je něco velké tučné...

**Comment by ondraspribyla** [comment]
Ad CO2eq:
Jsou dva přístupy k výpočtu EKVIVALENCE (viz anglická wiki!):
1. Ekvivalentní Global Warmig Potential. CO2eq. Požívá IPCC. *The
following units <https://en.wikipedia.org/wiki/Units_of_measurement> are
commonly used: By the UN <https://en.wikipedia.org/wiki/UN> climate change
panel IPCC
<https://en.wikipedia.org/wiki/Intergovernmental_Panel_on_Climate_Change>:
n×109 tonnes <https://en.wikipedia.org/wiki/Tonne> of CO2 equivalent
(GtCO2eq).*
2. Ekvivalentní Radiation Forcing. CO2e.

V datech Eurostatu není explicitně napsané, že řeší Global Warming
Potential, ale nečekal bych, že by počítali ekv Radiation Forcing.
--------
Tedy závěr: používejme CO2eq, protože IPCC. V případě paranoidní nejistoty
zkusme dohledat manuál k datům Eurostatu, abychom ověřili kterou
ekvivalenci berou do úvahy.

**Comment by crysman** [comment]
hmm, I see, takže používáme vlastně _CDE_ - tím pádem musím opravit i definici, kua.. to je napalicu, jediné info je v ENG pořádně, ve španělské verzi Wiki (4 nejmluvenější jazyk světa) je jen jedna verze CO2eq, a to sice ta _CDE_ ... takže z toho by se taky dalo soudit, že ten přepočet ×GWP je to ONO, nikoliv ta radiační podivnost.

**Comment by crysman** [comment]
hele, je v tom bordel, začínám  být frustrovaný. Na španělské Wiki se píše, že metan má GWP cca **23**, zatímco na anglické tvrdí, že **34**. Když si otevřu[ původní zdroj z anglické Wiki](https://web.archive.org/web/20100401082218/http://www.ipcc-wg1.unibe.ch/publications/wg1-ar4/ar4-wg1-chapter2.pdf), tak tam vidím číslo **25** (v rámci 100 let) - WTF? :( @ondraspribyla @Keramadohal

**Comment by ondraspribyla** [comment]
@Martin crysman Zahradník <crysmanovo@gmail.com> tak se nefrustruj a nech
to zatím být, my se na to podíváme...

O.

**Comment by protivinsky** [comment]
Mimochodem taky se na to divam - protoze jsem podobny prepocet pouzival pro emise svet (podle AR4 - nicmene ted jsem nasel doporuceni, ze je lepsi pouzivat novejsi prepocet AR5)

![image](https://user-images.githubusercontent.com/9573993/64491908-751ee680-d265-11e9-97d0-a10f2c160318.png)

**Comment by protivinsky** [comment]
Jako autoritativni zdroj bych pouzival IPCC AR5 WGI - https://www.ipcc.ch/report/ar5/wg1/

Strana 714:

![image](https://user-images.githubusercontent.com/9573993/64492212-aac5ce80-d269-11e9-8092-166e6eb3ffa1.png)

Cili ty rozdilne udaje mohou byt vysvetleny pouzivanim GWP vs GTP, zahrnuti climate-carbon feedback nebo pripadne pouzivanim predchozich IPCC zprav (AR4, SAR). Nevim jestli ohledne tohoto mame nejake preference - zkusim se na to letmo podivat, osobne se mi zda ze kombinace **GWP100, no climate-carbon feedback** je nejvice pouzivana v ostatnich zdrojich (28 pro NH4, 265 pro N2O). Pokud wiki neni v souladu, opravme to i na wiki (pripadne by stalo za to i vytvorit cesky preklad).

V #111 jsem to moc neresil a pouzival jsem AR4, prepocitam to na AR5 (podle toho na kterem se dohodneme). Zaroven jsem vytvoril #171 abychom na IPCC studie alespon odkazovali + popsali jejich zakladni strukturu (coz i poukazuje na komplexnost celeho problemu).

**Comment by crysman** [comment]
nejnovější verze zde https://github.com/mukrop/faktaoklimatu/commit/410673095fbdb1e54208951e79423580fa22865a

prosím @protivinsky a @ondraspribyla o revizi textů, zejména CO2eq, díky

**Comment by protivinsky** [comment]
super, za me ok

**Comment by crysman** [comment]
@protivinsky na Wiki opraveno:

1. přidal jsem https://cs.wikipedia.org/wiki/CO2_ekvivalent jako redirect na https://cs.wikipedia.org/wiki/Sklen%C3%ADkov%C3%A9_plyny#CO2_ekvivalent
2. [požádal jsem o úpravy GWP hodnot](https://cs.wikipedia.org/wiki/Diskuse:Sklen%C3%ADkov%C3%A9_plyny#Neozdrojovan%C3%A1_tabulka,_nespr%C3%A1v%C3%A9_hodnoty_CO2eq_(GWP)) na stejné stránce

**Comment by crysman** [comment]
updatována branch slovnicek třema commitama, takto bych si to představoval, tj:

1. stránka slovníku má ozdrojované pojmy
1. udělal jsem demo pro emise-cr - všude je CO2eq jako slovníkový pojem + extra nadpis - chtěl bych to do klimatonu mít jako šablonu tu stránku emise-cr, aby to podle toho mohl někdo eventuálně předělat všechno - zbývá doplnit další pojmy, teď už ale musím jít spát...
1. ostyloval jsem slovníkové pojmy, aby šly lépe odlišit od standardního linku jinam

**Comment by crysman** [comment]
nahodil jsem to na testovací server, můžete stávající devel branch `slovnicek` [omrknout online zde](http://fok.luzanky.cz/infografiky/emise-cr)

**Comment by crysman** [comment]
@mukrop mrkni prosím na řádek 13 emise-cr.md nějak nevím, jak to udělat systémově správně :/

**Comment by crysman** [comment]
PS: na španělské wiki už to na můj popud [opravili](https://es.wikipedia.org/wiki/CO2_equivalente), tak uvidíme, kdy to zvládnou čeští editoři...

**Comment by protivinsky** [comment]
@crysman super, diky za wiki! (a pardon, omylem jsem zeditoval predchozi prispevek - pouzivam jen nejakou aplikaci na telefonu)

**Comment by mukrop** [comment]
@crysman: Vyborna praca, obsahovo si si fakt makol, myslim, ze slovnik je na dobrej ceste k zverejneniu (a dalsie hesla sa budu dosadzovat postupne).

Par technickych:
* Vkladat HTML do MD je OK, ak to nejde vyriesit priamo v MD (to na margo toho riadka 13, co si sa pytal). Vhodnejsie by mi ale prislo nechat to ako h2 (resp. ako markdownove ##) a do no-transform zabalit len to, co sa nema transformovat (tj. CO2eq). Teraz je to nesystematicke v tom, ze ak sa rozhodneme nekapitalizovat nadpisy, tak tento zostane kapitalizovany.
* Chapem nutnost odlisit slovnikove odkazy -- ale prosim nie tak, ze hover meni sirku textu (a tym padom posuva vsetky slova v odstavci, v extremnom pripade moze inak zalomit riadky). O knizke sme sa bavili, to je dobry napad (a casom tam dam nejaku, ktora viac ladi so stylom webu :-P), len by som ju tam nechal stale. Ked tam bude knizka, tak mi ciarkovane odkazy uz pridu zbytocne (dalsi tyb zvyraznovania textu naviac to vizualne zneprehladnuje).

Este raz dik, fajn praca :+1:

**Comment by crysman** [comment]
Pokud by měl někdo náladu a chuť a především odvahu dělat potenciálně zbytečnou věc, tak může updatovat cs.wikipedia [dle mého diskusního návrhu k CO2eq](https://cs.wikipedia.org/wiki/Diskuse:Sklen%C3%ADkov%C3%A9_plyny#Neozdrojovan%C3%A1_tabulka,_nespr%C3%A1v%C3%A9_hodnoty_CO2eq_(GWP)).

**Comment by mukrop** [comment]
Hotovo v #180.

**Comment by mukrop** [comment]
> Pokud by měl někdo náladu a chuť a především odvahu dělat potenciálně zbytečnou věc, tak může updatovat cs.wikipedia [dle mého diskusního návrhu k CO2eq](https://cs.wikipedia.org/wiki/Diskuse:Sklen%C3%ADkov%C3%A9_plyny#Neozdrojovan%C3%A1_tabulka,_nespr%C3%A1v%C3%A9_hodnoty_CO2eq_(GWP)).

Urob na to prosim samostatne issue a nakopiruj do neho relevantne casti diskusie, nech ten, kto to bdue robit nemusi citat cele vlakno tu.
