### ISSUE TITLE
Upgrade možnosti KONTAKTování

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#12]
Zpětná vazba: "...kdyby to chtěl nějaký novinář použít, tak se mu nebude chtít mailovat, ale raději si zavolá..."

Je otázka, zda bychom v budoucnu dokázali nabídnou i takovou konzultaci. Jestli ano,pak mít stránku KONTAKT s nějakými podrobnostmi o kontaktování + telefonem by bylo dobré.

**Comment by mukrop** [comment]
Aktualne zatvaram. Mailovanie zatial funguje celkom fajn -- a keby bolo treba, telefon alebo samostatna stranka sa pridat daju.
