### ISSUE TITLE
Zvazit iny nastroj na build bitmap

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#120]
Zvazit, ci nechceme mensie delo ako Inkscape na konverziu SVG -> PNG. Inkscape bol historicky pouzity ako prve riesenie, ale je asi zbytocne velky a ma dost zavislosti. Jasna moznost by bol ImageMagic, ale ked som povodne vyberal, nasiel som nan vela negativnych referencii.

@repli2dev nemas nejaky tip?
Potrebujeme:
* Konverziu PDF -> SVG, ktora dokaze prekrivkovat texty (aktualne pouzivame `pdf2svg`).
* Konverziu SVG -> PNG, ktora zvlada nastavit rozlisenie (aktualne pouzivame CLI Inkscape).
* Do buducna sa mozno bude hodit aj nieco na resizovanie JPG (nahladove obrazky napriklad na studie).

**Comment by vlstill** [comment]
Na konverzi na rastrový obrázek by ImageMagic mohl jít použít při správném nastavení rozlišení (má to milion nastavení, chtělo by to nastudovat). Na resize jpg by použitelný být měl.

**Comment by mukrop** [comment]
@repli2dev ake mas ty skusenosti s ImageMagic-om?

**Comment by repli2dev** [comment]
@mukrop imagemagick je vcelku dobře použitelný, typicky používám `convert` a `mogrify` z příkazovky, jen si vždycky musím dohledat všechny parametry pro DPI, rozlišení atp.

**Comment by repli2dev** [comment]
@mukrop obecně bych se ho nebál, je na něj spousta negativních referencích především proto, že pořádně nic jiného neexistuje a všichni ho používají. (A sekundárně proto, že není úplně štastně napsaný, takže se v něm objeví nějaký ten security problém, což je ale kritické spíš pokud ho používáš jako extension v PHPku atp... a výrazně méně v případě build toolu.) (Btw. na převod z PDF je potřeba ghostscript, bez toho to bude hlásit divné chyby.)

Pro PDF -> SVG bych ale nechal `pdf2svg` ;-)

Z důvodu nedostatku času předávám zpět :-/

**Comment by mukrop** [comment]
To je v pohode, od teba som chcel len nazor (mas vacsie skusenosti), naimplementujem si to uz kludne ja.

**Comment by crysman** [comment]
@mukrop s obojím `convert` a `mogrify` mám dobré zkušenosti, ještě ve spojitosti s obrázky používám často `exiftool`. A z IM jsem použil úspěšně i `montage` v rámci jednoho projektu. Pravdou je, že jsem ale nikdy neřešil bezpečnost, lebo jsem to používal jen lokálně z terminálu.

**Comment by mukrop** [comment]
Aktualne zatvaram, nedolezite (mozno sa otvori v buducnosti).
