### ISSUE TITLE
odkazy a reference na stránky v archivované formě (webcitation.org (?)

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#122]
Navrhuju odkazovat na vždy archivované stránky externích zdrojů, rád používám ~~https://webcitation.org (už nefunguje :(~~ alternativa zde: https://web.archive.org/

důvody PRO:
- odkaz bude vždy funkční (dokud jede citovací služba) i když se např. změní URL či originál prostě zmizí
- obsah je ve tvaru, na který v daném čase odkazujeme

důvody PROTI:
- odkazovaná stránka nevypadá tak hezky
- nevypadá to důvěryhodně

pokud ano, je třeba navrhnout maličký guideline (hlavně jaký uvádět e-mail)

**Comment by repli2dev** [comment]
Nejvetsi duvod proti je, ze to nevypada ani trochu duveryhodne.

22. 8. 2019 v 20:00, Martin crysman Zahradník <notifications@github.com>:

**Comment by mukrop** [comment]
Podla mna to nie je dobry napad.
* Bezna prax to nie je, ludia na to nie su zvyknuti (a to je jeden z dovodv, preco to neposobi doveryhodne).
* Pride mi to nefer voci odkazovanym strankam. Nemaju moznost zmenit obsah/nazor. Ak by sme nahodou niekoho odkazovali, ze tvrdi XYZ a oni sa neskor rozhodli, ze to nie je pravda a upravili data/nazor/stihali clanok/..., tak je podla mna vhodnejsie upravit nase texty nez odkazovat, ze pred nejakym casom niekto nieco tvrdil.
* Chapem, ze nedostupnost externych odkazov by mohol byt problem, ale v dnesnych dobach sa to stava relativne malo casto. Navyse nasadenim kontroly dokazov, ako @crysman navrhol (#137) sa tento bod riesi.

**Comment by crysman** [comment]
Ahojte, no.. to že to je fixované považuju právě za výhodu, protože to je to, co my citujeme. Na druhou stranu beru, že vývoj se děje a vesmír se hýbe... Asi nechávám zavřené tedy. @repli2dev @mukrop
