### ISSUE TITLE
ikona zdůrazňující, že jde o button "ke stažení"

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#125]
### Problém:
Podle mě **není na první pohled vidět, že si tu můžu něco stáhnout**. Musím všechny texty přečíst, a pak pochopit, že to tmavě modré pozadí je teda asi na stahování.

### Řešení:
**Doplnit "download" ikonu**, jako to má většina webů. Příklady zde:

- slunecnice.cz: ![image](https://user-images.githubusercontent.com/5269350/63545413-983c5d00-c527-11e9-842e-21e6046f7d39.png)
- uloz.to: 
![image](https://user-images.githubusercontent.com/5269350/63545476-ca4dbf00-c527-11e9-9a38-5788c73d219d.png)
- stahuj.cz: 
![image](https://user-images.githubusercontent.com/5269350/63545583-0d0f9700-c528-11e9-9a52-49f530453580.png)
- ... a spousta dalších

možná se můžeme i vyhnout obrázkům a použít UTF char nějaký:
https://www.utf8icons.com/search?query=down

tedy něco jako toto: **⭳**

**Comment by repli2dev** [comment]
Vsak ono se taky nic nestahuje, ale jen otevira v nahledovem nastroji prohlizece. Pridani stahovaci ikonky by se muselo programove vynutit to stazeni (tzn. bez pouziti nahledoveho nastroje prohlizece).

V soucasne dobe navic muze byt, a typicky je, tlacitkem ve webovych a mobilnich aplikaci kde co, takz ikonka to uz moc nevytrhne a spise naopak spis stranku vizualne prehlti - zde napriklad na strance detailu by byla cca 6x.

22. 8. 2019 v 22:01, Martin crysman Zahradník <notifications@github.com>:

**Comment by mukrop** [comment]
Suhlas s Honzom. Argument, ze citatel si musi vsetky texty precitat mi nepridde uplne padny, kedze v pravom paneli je hned ako prvy pomerne prominentny nadpis "KE STAŽENÍ". Myslim, ze modre tlacitka su pomerne intuitivne klikatelne (pouzivame ich vyhradne pre klikatelny obsah). A ano, pridanie ikon (muselo by ich byt viac, aby sme boli konzistentni) by stranku zahlcovalo.

**Comment by crysman** [comment]
ok
