### ISSUE TITLE
! nesoulad v datech mezi infografikami

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#129]
toto https://faktaoklimatu.cz/infografiky/emise-eu-poradi (i ten druhý) v sekci na obyvatele neodpovídá číselně tomuto https://faktaoklimatu.cz/infografiky/emise-vybrane-staty

namátkou ČR, Německo, ani Polsko

**Comment by mukrop** [comment]
Snad vyriesene v #133.
