### ISSUE TITLE
Patička stránek

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#13]
Momentálně stránky končí "Myšlenka a tvůrci" v případě homepage a textem v případě komentářů infografik - což vypadá divně. Chtělo by to něco, co vizuálně sdělí, že to je konec stránky a případně bude obsahovat klasické patičkoidní informace.

**Comment by mukrop** [comment]
@xlauko, neskusil by si pridat nejaku jednoduchu paticku, ktora bude rozumne vyzerat?

**Comment by mukrop** [comment]
@ondraspribyla: Mozes prosim nahodit informacie, ktore maju byt v paticke?
* Za mna datum poslednej zmeny (automaticky generovany).
* Chceme tam email?
* Chceme tam tagline projektu? ("Verejne dostupne infografiky a datasety o zmene klimatu v CR")
* Chceme tam vyzvu na feedback? (nieco typu "Nefunguje neco? Budeme radi, kdyz nam das vedet" a link na GitHub issue tracker).
* Co este by tam mohlo/malo byt?

**Comment by mukrop** [comment]
Paticka je nachystana, caka na navrh obsahu,

**Comment by ondraspribyla** [comment]
- Prošel jsem patičky zahraničních webů pro inspiraci
- našel jsem footer.html ale rozhodl jsem se do něj nehrabat
Tedy píšu takto: 

Jasné věci: 
- datum poslední změny
- email 
- Tagline
- výzva k feedbacku: Nefunguje něco? Chtete navrhnou vylepšení? Budeme rádi, když nám dáte vědět.
(re "link na github": ideálně tak, aby mohli něco napsat i lidé, kteří se v programování příliš nevyznají...)

K diskusi: 
- "Technický kurátor webu: MUkrop, Obsahový kurátor webu: Ondráš Přibyla" - možná s kontaktama, vč telefonu?
- Jak nám můžete pomoci? + odkaz na stránku, na které bude podrobněji popsané jak mohou pomoct - šíření informací, poskytnutí cílených kontaktů (novináři, politici), přidání se do týmu... 

Někdy v budoucnu: 
- disclaimer - vysvětlení stylu práce a odpovědnosti za správnost dat.
