### ISSUE TITLE
Nezavisla kontrola funkčnosti, dat a textů

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#130]
před novým public release potřebujeme nechat to někoho nezávislého zkontrolovat (buď člověka mimo konkrétní klimaton, nebo člověka explicitně s touto rolí) - konkrétně:

- ověřit data v celé sekci
- ověřit funkčnost a relevanci linků
- koherenci dat
- gramatiku a typografii

**Comment by mukrop** [comment]
Upravil som nazov issue, prisiel mi nevystizny, plietol sa s #60.

**Comment by ondraspribyla** [comment]
Momentálně máme procesní pravidlo, že se nikdy neuppravuje master a vždy se pracuje pouze s větví, kterou pak musí zkontrolovat @mukrop předtím, než se udělá Merge. Nechával bych tedy na něm, zda si vyžádá review. Pro mě je proces momentálně dostatečný. Tedy navrhuju zavřít (případně napište comment a udělejte re-open )

Nezávislá komise by byla fajn, ale při našem tempu práce (mám teď na mysli hlavně šest týdnů zaseklou grafickou sekci) to nedává smysl.
