### ISSUE TITLE
verzování a changelog, historie změn

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#131]
Chyby i při dodržení [workflow guidelines](https://github.com/mukrop/faktaoklimatu/issues/130) stejně i tak budou. S tím souvisí:

### 1) nutnost verzovat infografiky
(přímo obr) - v každé ifografice něco jako `v.2019-08-23a`

a k tomu

### 2) nutnost založit stránku aka "changelog"
kde budeme jednotlivé major issues/změny vysvětlovat a říkat, kterých verzí se týká

**Comment by repli2dev** [comment]
3) sjednotit commit zprávy a generovat z nich (polo-)automatizovaně GitHub release logy

**Comment by crysman** [comment]
@kikinna zatím si popřemýšlej, kde by ta verze mohla být

ostatní> myslím, že to docela spěchá, čím dřív to uděláme, tím líp, není to moc práce

ad poloautomatizovaý release log> nejsem si jistý, zda to potřebujeme, rád bych viděl ten changelog čitelný a jednoduchý

**Comment by mukrop** [comment]
Hlavne miesame dve nesuvisiace veci, ktore sa daju riesit zvlast. Rozdelene do #139 a #140.
