### ISSUE TITLE
Nekoherence ohledně letecké dopravy

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#136]
nekoherence ohledně ne/zahrnování s letecké dopravy mezi
https://faktaoklimatu.cz/infografiky/emise-cr,
https://faktaoklimatu.cz/infografiky/emise-cr-detail

("_V údajích o emisích nejsou zahrnuty emise z mezinárodní letecké dopravy, protože je komplikované přisoudit, které zemi by emise daného letu měly „patřit“ (místo vzletu?, místo přistání?, země která vyprodukovala letecké palivo?)._"

a

https://faktaoklimatu.cz/infografiky/emise-vybrane-staty,
https://faktaoklimatu.cz/infografiky/emise-eu-poradi,
https://faktaoklimatu.cz/infografiky/emise-eu

("_V rámci této infografiky jsou v údajích o emisích zahrnuty emise z letecké dopravy._")

klidně, ať to je někde zahrnuté a jinde ne, ale nemůžeme o tom psát, že to nejde, a přitom to jinde používat...

**Comment by mukrop** [comment]
Assigned to Yena Krcal.

**Comment by jankrcal** [comment]
Data mám upravená (to bylo samozřejmě asi 5 minut práce), zatím je blokováno na vyřešení #77.

**Comment by jankrcal** [comment]
@kikinna, myslíš, že bys mohla opravit grafiku podle upraveného G sheetu?
https://docs.google.com/spreadsheets/d/1y52VXoiW7OmzT1sm1UQeT0XhZTuKge1962A4pjFmqzg/edit#gid=0

**Comment by mukrop** [comment]
Hotovo.

**Comment by jankrcal** [comment]
@mukrop Vyměnil jsi i datasety odkazované z webu?

**Comment by jankrcal** [comment]
Potřebujeme odkázat na https://docs.google.com/spreadsheets/d/1y52VXoiW7OmzT1sm1UQeT0XhZTuKge1962A4pjFmqzg/edit#gid=0 místo na předchozí https://docs.google.com/spreadsheets/d/1igCIcrkec7J6sfp4L4lGMzeDS4Mf-o7GZOxduZC8-pc/edit?usp=drive_web&ouid=103561362448492207446

(ten nový jsem už přesunul do složky final a přejmenoval, aby to působilo finálně)

**Comment by mukrop** [comment]
Pocitam s tym, bavili sme sa o tom s Ondrasom asi pred hodkou.
(Ale je pravda, ze to tam este nie je.)
