### ISSUE TITLE
Doplnit infolist k zprave od Energynautics

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#138]
Vytvorit nepovinne tlacitko pod weba PDF, kde moze byt nejaky sumar alebo clanok. Pre spravu od Energynautics tam pridat odkaz na cesky InfoList.

**Comment by ondraspribyla** [comment]
Po připomínkách dvou šťouralů vidím doplnění českého infolistu jako důležité, jsou v něm odpovědi na některé jejich komentáře. Nepřidávám tímto urganci, jenom důležitost.

**Comment by mukrop** [comment]
Pri citanim poznamok inde prioritizujem vyssie.

PS: Zaujimave rozlisenie urgencie a dolezitosti

**Comment by mukrop** [comment]
Nachystane vo vetve `zmeny-studii`.
