### ISSUE TITLE
Novinky/suhrn zmien

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#139]
Mozno chceme stranku alebo sekciu, kde sa budu pisat aktuality ('pridali sme infografiku') alebo vyraznejsie zmeny ('upravili sme data v XYZ').
* Vyhody: Pre navstevnikov je lahsie sledovat, co je nove; transparentnost s tom, co menime (ked zmenime infografiky alebo data).
* Proti: Je treba to udrzovat (ked je posledna aktualita spred roka, je to zle); nie je jasne, kam to dat (nechceme hore, nemalo by to brat pozornost).

Povodne navrhol Crysman v #131.

**Comment by mukrop** [comment]
Chceme ich (po diskusii).

**Comment by mukrop** [comment]
V gite je branch s draftom stranky s novinkami. Prilezitostne mozte pisat texty (mohol by nadrafrovat @crysman a potom zrevidovat @ondraspribyla).

**Comment by crysman** [comment]
velký update, viz https://github.com/mukrop/faktaoklimatu/pull/224

**Comment by mukrop** [comment]
Hotovo.
