### ISSUE TITLE
Chyba v grafu "Emise" - sunburst

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#14]
Graf v současné podobě obsahuje jednu chybu a jednu nepřesnost:

Chyba: nějak došlo k prohození nákladní a osobní dopravy. Správně má být osobní automobilová doprava 10.86 MtCO2 (8.3%) a nákladní 7.16MtCO2 (5.4%). V grafu jsou ale naopak...

Nepřesnost: "Energetika mimo HU" by se měla správněji jmenovat "Teplárny a zpracování paliv"
----
Upgrade pro nepřesnost: do drivu jsem nahrál opravenou verzi .svg výstupu (který je nutné zpracovat grafikama) ve kterém jsou teplárny a zpracování paliv samostatně.

**Comment by kikinna** [comment]
@ondraspribyla 
Čauko, tady píšeš hodnotu 5.4% pro nákladní, ovšem v nově vygenerovaném SVG na drive je hodnota 5.5%. Která verze má být správná?

**Comment by ondraspribyla** [comment]
Zaokrouhlovací problém... Teď z mobilu to nezjistim

Dne pá 28. 6. 2019 10:29 uživatel kikinna <notifications@github.com> napsal:

**Comment by mukrop** [comment]
Aktualne patri @ondraspribyla: Zisti, ci tam ma byt tych 5.4% alebo 5.5% (a bolo by fajn, aby suma bola 100% :-)). Ked to zistis, prehod tento issue na @kikinna.

**Comment by ondraspribyla** [comment]
Hodnota pro autobusouvou a nakladni dopravu je 5.49%, tedy sp8vn0 zaokrouhleni je 5.5%
