### ISSUE TITLE
Carbon Tax + 100% dividenda

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#141]
Základní infografika popisující Carbon Tax + návrh ceny (třba 1000kč na tunu?) a výpočty zvýšení cen...
+ výpočet dividendy.

**Comment by ondraspribyla** [comment]
https://ourworldindata.org/carbon-pricing-popular

**Comment by ondraspribyla** [comment]
@protivinsky

**Comment by protivinsky** [comment]
zajimavy zdroj - http://documents.worldbank.org/curated/en/636161467995665933/State-and-trends-of-carbon-pricing-2015

**Comment by protivinsky** [comment]
@ondraspribyla update: 
- world bank vydava skvele studie, za rok 2019: https://openknowledge.worldbank.org/handle/10986/31755
  - skvely zdroj, zajimave grafiky, under CC license
  - rychlou vyhrou by mohlo byt nekterou z grafik proste vzit a prelozit, pripadne mirne doplnit (licence to umoznuje, jen musime odkazovat / doplnit disclaimer) - toto bych nejspis zvladl i sam, bez graficky
- zpravidla se hovori o Carbon Pricing, ktere je nasledne rozdeleno na carbon tax a emissions trading schemes (ETS; osobne jsem to taky vnimal dost podobne, proto jsem se predtim i ptal na ty emisni povolenky)
  - system povolenek plati v cele EU a pokryva 41 % emisi, momentalni cena je cca 25€ / t CO2eq (tedy cca 650 Kc za tunu) - cenu lze dohledat pod tickerem EUA, historicky vyvoj napriklad zde https://sandbag.org.uk/carbon-price-viewer/ (nekde jsem videl, ze by byla potreba o kus vyssi cena, cca na urovni 50-100 $ / t CO2eq - zatim je tedy znacne nizsi, nicmene EU muze snizit mnozstvi povolenek a cena pak prirozene pujde nahoru)
  - toto by tedy melo pokryvat i ceske emise, byt jsou tam nejaka kriteria jake sektory / podniky jsou presne zahrnute (predpokladam ze to nepokryva male producenty - nevim jak je to u energii)
  - nektere staty EU maji krome ETS i carbon tax (Svedsko, Svycarsko, Finsko, Francie a dalsi)
  - rad bych tedy cilil grafiku i na ETS - prijde mi stejne dulezite zlepsovat image existujiciho nastroje jako propagovat novy nastroj (a ve vysledku mohou fungovat podobne)
- Cina jako nejvetsi producent momentalne take zavadi ETS - https://en.wikipedia.org/wiki/Chinese_national_carbon_trading_scheme - jejich plan zni skutecne ambiciozne:
  - *China promised in the Conference of Parties to reduce their carbon intensity per unit of GDP by 60-65% by 2030*
- zde nekolik ukazek grafik ze studie WB, ktere by napriklad bylo mozne prejmout (prvni dve mne prijdou nejzajimavejsi):

![image](https://user-images.githubusercontent.com/9573993/64654524-7268f080-d421-11e9-8d69-72b8c3557aea.png)

![image](https://user-images.githubusercontent.com/9573993/64654555-86145700-d421-11e9-93c2-f587de303326.png)

![image](https://user-images.githubusercontent.com/9573993/64654591-96c4cd00-d421-11e9-8768-2e3ab3b1739b.png)

![image](https://user-images.githubusercontent.com/9573993/64654615-ab08ca00-d421-11e9-8c54-d6f0e1aa8c3e.png)

**Comment by protivinsky** [comment]
Myslel jsem ze uz jdu spat, ale pak jsem jeste hodil do google "infographics carbon pricing" a nejak me zaujalo co z toho vylezlo.

**Zajimave infografiky:**
- How Carbon Pricing Works - https://i.pinimg.com/originals/de/ca/fd/decafddc77d1a8d0a883cffd4748d027.jpg
- What is Carbon Pricing - http://environmentalsociety.ca/publications/2018/what-is-carbon-pricing/
- Carbon Pricing Canada - http://natoassociation.ca/the-projected-effects-of-a-national-price-on-carbon/
- A Price on Carbon Emission - https://www.asiaone.com/sites/default/files/inline/images/18110_1487304088.jpg
- Market stability reserve - https://www.carbontracker.org/wp-content/uploads/2018/08/Carbon-Countdown_infographic3.png
- Canada Overview - https://www.osler.com/en/resources/regulations/2015/carbon-ghg/carbon-and-greenhouse-gas-legislation-across-canad
- 5 Reasons why Carbon Pricing is the Future - https://www.carbonpricingleadership.org/news/2015/5/23/5-reasons-carbon-pricing-is-the-future-1
- Ontario Cap & Trade - https://pricecarbonnow.org/sites/default/files/Capntrade_roadmap2_1.png
- How Carbon Pricing Works (not so great) - https://www.pinterest.co.uk/pin/247979523218365255/

Neni problem jim napsat a zeptat se, zdali muzeme neco z toho pouzit / prelozit / upravit (coz by bylo potreba asi u vsech). Z meho pohledu trochu zalezi, do jake miry tim chceme ciste informovat o tom co to je a proc je to dulezite a do jake miry to chceme propojit s daty / cenami / dividendami. Nektere v zasade zahrnuji oboje.

![how-carbon-pricing-works-2](https://user-images.githubusercontent.com/9573993/64656462-6c760e00-d427-11e9-8643-6917dd50bc9d.jpg)

![carbon-pricing-canada](https://user-images.githubusercontent.com/9573993/64656466-71d35880-d427-11e9-9410-a74b4d7478fe.png)

**Comment by ondraspribyla** [comment]
Koukám na ty infografiky a přijdou mi všechny dost slabé...

1. Začínají od cíle (o kolik chtějí snížit emise) ale 1.1 poptávka po
energii je podle některých spíše nepružná, 1.2 snížení emisí je komplexní
efekt, způsobeny z velké části vhodným investováním peněz z carbon tax
získaných (infrastruktura, fve...)

2. Vůbec nikde neuvádí ani přibližně o kolik se co zdraží

Tedy přijdou mi fajn jako komody, ale nedokážu si představit, že jdu do
dvtv a vezmu si sebou grafiku, abych mohl s Veselovským lépe diskutovat...

Takže zatim bych hledal něco lepšího...
A možná nejvhodnější bude si zavolat a bavit se o tom...



Dne st 11. 9. 2019 1:02 uživatel Tomas Protivinsky <notifications@github.com>
napsal:

**Comment by ondraspribyla** [comment]
Dobrý zdroje...

Přemýšlím k jakým argumentům povede srovnání mezi zeměmi... Intuitivně
nemám dojem že když řeknu "Země x a y mají ETS/CT" tak to nějak změní
diskusi...

Asi bych chtěl něco co se jasněji týká života lidí. Opět asi na diskusi...

Kdy můžu zavolat?

O.

Dne st 11. 9. 2019 0:21 uživatel Tomas Protivinsky <notifications@github.com>
napsal:

**Comment by protivinsky** [comment]
Zavolat muzu vecer, cca po pul desate tveho casu.

- pokud by poptavka po energiich byla skutecne nepruzna, pak ETS jsou
vyrazne lepsim nastrojem nez carbon tax (protoze ETS nastavuji cilove emise
a cena se prizpusobi)
- 100% dividenda ale stejne miri dost jinym smerem nez investice do
infrastruktury apod?

Souhlasim, ze mnoho informaci v tech grafikach chybi. Osobne vnimam tri
roviny:
1. Co carbon pricing je a proc je to dobra metoda (vyrazne lepsi nez zakazy
a regulace, rychlejsi nez spolehani na uvedomele spotrebitele)
2. Neni to nic obskurniho, je to overena metoda zavadena v mnoha zemich
vcetne Ciny (tedy neni to ze Cina emituje a nic nedela, jen my na to
kasleme; osobne mam skutecne dobry dojem z velkeho narustu opatreni v
poslednich letech, je to dobry lek na environmentalni zal).
3. Odhady dopadu na bezny zivot, prevedeno na ceny benzinu / elektriny /
vytapeni.

Prodiskutujeme po telefonu.

**Comment by protivinsky** [comment]
Btw:

![image](https://user-images.githubusercontent.com/9573993/64734007-bb7e7a80-d4dd-11e9-958d-13cb38b9398a.png)

![image](https://user-images.githubusercontent.com/9573993/64734098-e23cb100-d4dd-11e9-9c0a-daded3edd5ce.png)
(levy graf)

![image](https://user-images.githubusercontent.com/9573993/64734142-f97b9e80-d4dd-11e9-8b65-f2c7c0e1e1d9.png)

Vse je z IPCC AR5 WG3 - Climate Change 2014, Mitigation of Climate Change - https://www.ipcc.ch/report/ar5/wg3/

**Comment by protivinsky** [comment]
There is no planet B, str. 147:

*For perspective, a carbon price of $100 per tonne CO2 adds just 3 cents per mile to the cost of driving an oil-powered car and about eight cents per kWh onto the price of coal-powered electricity.*

*My guess as to where it will end up, assuming we want to restrict warming to 2 C or less? $1000+ per tonne by 2050.*

Cisla jsem neoveroval, nicmene 3 centy / mile znamena cca 40 haliru / km, cili 6 Kc / 15 km coz je zhruba litr benzinu. $1000+ pak odpovida 60+ Kc na litr benzinu - coz povazuji za prilis vysoke - jednak politicky nerealizovatelne a jednak si myslim ze i nizsi dan povede k nahrazovani cistsimi technologiemi.

**Comment by protivinsky** [comment]
tldr: Co je nejlepsi cesky ekvivalent Carbon Pricing? Treba **zpoplatnění emisí** nebo **cena za uhlík**? Pro Carbon Tax bych pouzival **uhlikova dan** (prijde mi uz zavedena), pro Emissions Trading System **system pro obchodovani s emisemi** (abych se vyhnul negativne konotovanym povolenkam). 


Vzhledem k tomu ze tema nyni vnimame primarne jako "Carbon Pricing", potrebujeme k tomu cesky ekvivalent. Inspirace z jinych jazyku:
- Carbon Pricing
- Prix du carbone (francouzsky)
- CO2-Preis (nemecky)
- Precio de las emisiones (spanelsky)

V cestine se aktualne vyskytuji:
- zpoplatnění emisí (skleníkových plynů / uhlíku / CO2)
- zpoplatnění uhlíku
- oceňování uhlíku
- oceňování emisí
- stanovení cen uhlíku
- cena za uhlík

Pro Carbon Tax je uhlikova dan dostatecne zavedena (a zaroven prekladem anglickeho terminu). Pro emisni povolenky se zpravidla pouziva ETS (emissions trading system) nebo Cap and Trade - ovsem mam dojem, ze emisni povolenky maji negativni konotaci - rad bych bud zmenil konotaci povolenek, nebo ji nahradil jinym vyrazem (system pro obchodovani s emisemi / omezení (strop, limit) a obchod).

A jako off-topic, cela oblast na ceske wikipedii je zpracovana dost slabe. Az toto dotahneme, stalo by zato ji predelat.

**Comment by protivinsky** [comment]
Pro lepsi trackovani jsem rozdelil issue na samostatne casti - #204, #205 a #206.
