### ISSUE TITLE
rozšíření emise-eu-poradi o velikost státu

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#143]
rozšíření [emise-eu-poradi](https://faktaoklimatu.cz/infografiky/emise-eu-poradi) o velikost státu (buď HDP nebo počet obyvatel) - představuju si to jako tři sloupce - čili k tomu jak to je teď přibude doleva počet obyvatel (nebo HDP) - bude to takový WIDE graf - myslím že nemusíme tvořit *výhradně* pro A4 formát, což? @kikinna @ondraspribyla

**Comment by ondraspribyla** [comment]
Není priorita - obecně by s tou grafikou šlo dělat hromadu dalších upgradů... az budou prioritni, udelame si na to issue. Zaviram.
