### ISSUE TITLE
Korektura našich finálních datasetů

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#146]
Projít naše zveřejněné datasety, doplnit, přejmenovat, ...
Ondráš ví detaily.

**Comment by mukrop** [comment]
Assigned to Yena.

**Comment by ondraspribyla** [comment]
@jankrcal - procházím stary issues... tohle je špatně zformulovany. Mohl bys prosím udělat nová issues na kontrolu/přepracování dat, která ještě nejsou hotová a tohle zavřít?

**Comment by jankrcal** [comment]
Ano, udělám zítra ve vlaku.
