### ISSUE TITLE
 srovnání emisí mezi státy eu

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#15]
Potřebná data pro vytvoření infografiky, kde se srovnají emise skleníkových plynů na člověka mezi všemi státy a poukáže se na důvody pro výběr jednotlivých států pro infografiku "srovnání emisí vybraných států EU" 
1. Je třeba rozhodnout které státy (jaké je kritérium podle kterého vybíráme státy?)
2. Nejspíš z [eurostatu](http://appsso.eurostat.ec.europa.eu/nui/show.do?query=BOOKMARK_DS-089165_QID_20FB36E9_UID_-3F171EB0&layout=GEO,L,X,0;AIREMSECT,B,Y,0;UNIT,L,Z,0;AIRPOL,L,Z,1;TIME,C,Z,2;INDICATORS,C,Z,3;&zSelection=DS-089165INDICATORS,OBS_FLAG;DS-089165TIME,2016;DS-089165UNIT,MIO_T;DS-089165AIRPOL,GHG;&rankName1=UNIT_1_2_-1_2&rankName2=AIRPOL_1_2_-1_2&rankName3=INDICATORS_1_2_-1_2&rankName4=TIME_1_0_0_0&rankName5=GEO_1_2_0_0&rankName6=AIREMSECT_1_2_0_1&rStp=&cStp=&rDCh=&cDCh=&rDM=true&cDM=true&footnes=false&empty=false&wai=false&time_mode=NONE&time_most_recent=false&lang=EN&cfo=%23%23%23.%23%23%23%2C%23%23%23) (?) vytáhnout data a vytvořit novou tabulku v emisích.

**Comment by ondraspribyla** [comment]
@kikinna 
Něco jsem stihl zpracovat ještě na hackatonu ve čtvrtek. Data jsou připraveny pro několik států EU.
ZZkusil jsem dát i do nějakého grafu, ale zaztím s tím spokojený nejsem. Více vizz poslední záložka v souboru
https://docs.google.com/spreadsheets/d/1IJn4amBeD2Ra_0LFKCWY-iT-UyaxpaU2pvoQ-uuPp2o/edit?usp=sharing

**Comment by kikinna** [comment]
Paráda, díky. Já nevěděla, kde to hledat, ale pamatuji si, že jsi na tom začal pracovat ))

**Comment by ondraspribyla** [comment]
https://docs.google.com/spreadsheets/d/1IJn4amBeD2Ra_0LFKCWY-iT-UyaxpaU2pvoQ-uuPp2o/edit?usp=drivesdk

Data celkovych emisí jsou připraveny akorát graf by se hodil spíše plošný... Možná s nějakým zvýrazněním kolik emisi připadá v daném státě na hlavi

**Comment by ondraspribyla** [comment]
Prace je hotova a je tady: https://faktaoklimatu.cz/infografiky/emise-vybrane-staty
Zavírám Issue.
