### ISSUE TITLE
Tomáš Jungwirth

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#153]
Dohoda s Tomášem, že pošleme otázky, na které bychom rádi dostali zpětnou vazbu od novinářů, právníků lobbistů...

**Comment by protivinsky** [comment]
Mimochodem neni to take hlavni tahoun klimatickeho programu pro Piraty? Nebo to je jiny Tomas Jungwirth? www.amo.cz/autor/tomas-jungwirth

Trochu mi lezi v hlave, ze by bylo fajn, kdyby se nekterych temat, ktera se snazime otevirat a kultivovat, chopila i nejaka politicka strana a zahrnula je do sveho programu. U Piratu bych doufal v urcitou otevrenost k resenim zalozenych na faktech, samozrejme ale predpokladam, ze projekt chceme mit jako apoliticky. 

Nezvazujeme treba nejake konzultace s politickymi stranami / pripominkovani relevantnich casti volebnich programu apod? Mozna se to samozrejme deje, akorat ja o tom nevim.
