### ISSUE TITLE
Upravit sekci "Tvůrci" (feedback od Lenky Krčálové)

### ISSUE THREAD

**Issue by jankrcal** [mukrop/faktaoklimatu#156]
Ukazoval jsem web svojí ženě. Líbil se jí :)

Narazila na sekci "Tvůrci":
  - "Běžný novinář nebo politik (ani běžný Čech) většinou nemá tolik trpělivosti nebo dostatečnou úroveň angličtiny a tak si data nevyhledá." na ni pusobi dost prezirave
 - navrhuje vetu smazat a misto toho rozsirit predchozi vetu: "Jde to, ale musíte umět dobře anglicky, musíte si dohledávat spoustu souvislostí a stojí to spoustu času."

Celkově ji přišlo, že by to mohlo působit důvěryhodněji - nedá se o lidech v týmu napsat víc? Třeba jen stručně, co kdo dělá, nebo tak. Nebo nějak jinak podpořit, že jsou za tím konkrétní lidi, kteří se za to nestydí a jsou schopni vyjít s kůží na trh.

**Comment by jankrcal** [comment]
Tu první část klidně upravím, pokud někdo další potvrdí, že to dává smysl.

K té druhé části je potřeba víc diskuse.

**Comment by repli2dev** [comment]
@jankrcal naprostý souhlas s první půlkou. Osobně bych doplnil i nějak vhodně "dát věci do kontextu".

**Comment by mukrop** [comment]
Suhlas, ten text chce preformulovat uz davnejsie. Pri tej prilezitosti by sme mohli vyriesit aj #100. Vytvoril som vetvu `sekce-tvurci`, kde som navehol obsah suboru `AUTHORS.md`

@jankrcal: Mohol by si do tejto vetvy prosim skusit preformulovat text tak, ako navrhla Lenka? Zaroven prosim uprav zoznam uvedenych mien tak, aby zodpovedal core timu (mozes ist podla `AUTHORS.md`). Suhlasim aj s tym, ze by sa o nich dalo napisat viac -- skus velmi strucne nieco navrhnut (aspon ukazku k sebe). Daj potom vediet, ja doplnim info o ostatnych, potom urobime pull request a prediskutujeme konkretny navrh v sirsom time.

**Comment by jankrcal** [comment]
Přidal jsem do `sekce-tvurci` slíbený commit. Pár komentářů:
 - Je mi trochu žinantní ve svém prvním ever commitu přidat na web svoje jméno :) Co už, aspoň si tak sám vytvářím závazek si toto "odpracovat".
 - Rozhodně jsem se necítil na to, někoho mazat, ale aspoň jsem změnil pořadí, aby lidi v core byli vyjmenovaní první. Petr Novotný není zmíněn v AUTHORS.md vůbec, je to omyl? Mám ho tam přidat nebo ho snad naopak smazat z hlavní stránky?

Nějak pocitově bych prvně chtěl mít na webu "Odborné garanty" a až pak něco víc říct o autorech. Přijde mi, že pokud prvně řekneme víc o nás, tak to může být kontraproduktivní vzhledem k důveryhodnosti ("vždyť oni po většinou vůbec nejsou z oboru!!!").

A tak bych udělal pull request, jak to je, a doplnění více o týmu bych nechal na příště.

@mukrop: co myslíš?

**Comment by jankrcal** [comment]
@repli2dev: chvíli jsem nad tím přemýšlel, ale slovo "kontext" je natolik podobné slovu "souvislost", že mi to tam nešlo.

**Comment by mukrop** [comment]
Vyzera to fajn, dik. Upravil som mena, ktore sa zorazuju priamo na titulnej strane (ten povodny text bol pisany este v dobe, ked vobec nebolo jasne, kto sa viac zapoji, tak to uplne nezodpovedalo). Pridal som odkaz na AUTHORS.md.
Urob z toho pull request a oznac tam par ludi na review.
