### ISSUE TITLE
Vyhledávání grafů podle tagů

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#16]
I have a dream :-) 
zakliknu si Tagy, které mě zajímají (ČR/Evropa/Svět, Teplota/Emise/..., Historie/Předpovědi)
a obrazí se mi relevantní grafy...
A navíc ke každému grafu budu mít rovnou nabídku souvisejících...
:-)

**Comment by mukrop** [comment]
Akoze -- ano, ale podla mna to nema zmysel, kym mame 6 infografik. Zatial nechavam otvorene ako funkcionalitu, ktoru mozno budeme chciet do buducna.

**Comment by mukrop** [comment]
Zatial nie ako vyhladavanie, toto zatvaram (a vyrobim novy issue na suvisiace grafy cez tagy).
