### ISSUE TITLE
Zdroje dat (soubor vs. web)

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#161]
Některý odkaz na zdroj dat otevírá novou stránku, jiný stáhne xls soubor - což mi přijde matoucí. 
Ideální by bylo vždy otevřít stránku, ale odkazů na stránce, ze které jsme stahovali bylo typicky hodně - takže by bylo nejlepší označit konkrétní link...? Je to k diskusi.

**Comment by crysman** [comment]
@ondraspribyla obávám se, že to není možné. Modelový příklad zde:

https://faktaoklimatu.cz/infografiky/koncentrace-co2 -> Zdroj -> EPICA vede na: ftp://ftp.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/epica_domec/edc-co2-2008.xls

když si otevřeš jen:
ftp://ftp.ncdc.noaa.gov/pub/data/paleo/icecore/antarctica/epica_domec/

tak je tam příliš mnoho věcí, než aby se v tom user zorientoval, takže my **musíme** odkázat na ten XLS soubor...

Navrhuju zavřít jako WONTFIX

**Comment by mukrop** [comment]
Za mna je dorbym riesenim snazit sa (pokial je to aspon trochu mozne) linkovat sprievodne stranky, nie priamo datove subory. Aj preto, ze na sprievodnych strankach je casto kopa uzitocnych metadat.

To, co pise @crysman je pravda, ale to je podla mna neprehladne hlavne preto, ze to je priamy pristup na FTP server, tj. do suborov. Stranka odkazovanej studie je tu: https://www.ncdc.noaa.gov/paleo-search/study/6091 (beriem, ze ma drobnu nevyhodu, ze odkazuje len TXT data a nie XLS, ale obsah je rovnaky).

PS: Az tak sa v tych datach nevyznam, ale vyzera to, ze existuju aj novsie (2015). Korespondujuca studia (s odkazmi na data, tentoraz aj na XLS) tu: https://www.ncdc.noaa.gov/paleo-search/study/17975

**Comment by mukrop** [comment]
Ako padlo v diskusii neskor osobne, je otazka, ci pri kvalite spracovania dat, aku mamte teraz (system od Jenu) je vobec nutne mat na strankach odkaz na povodny zdroj (kedze link na povodny zdroj/e je v nasich data). Nechavam na diskusiu.

**Comment by ondraspribyla** [comment]
Tohle issue je z doby, kdy jsme hledali, jak věci dělat. Když si teď procházím stránky, přijde mi jako zásadní feature, že jsou na všech grafikách odkazy na "původní data" i když ten formát je pokaždý jiný. Tedy každopádně bych nechal "Původní zdroj dat"  (credibility) a snažil se co nejlépe linkovat přehlednou stránku. Pokud to bude nějakým uživatelům (novinářům) vadit, tak na to třeba upozorní...
Tímto issue zavírám.

**Comment by mukrop** [comment]
OK, vytvara to kredibiliotu (aj ked praktickejsie je to v nasom spracovanom dokumente aj s poznamkami). Suhlas, nechajme aktualny stav.
