### ISSUE TITLE
Vycistit externe odkazy

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#162]
Externe odkazy by mali byt oznacene, ze sa otvaraju v novom okne a mali byt mat `rel-noopener` (viz #108). Tj. pre-deploy skript asi doplni aj obrazok otvorenia v novom tabe (takze pridat podporu pre FA).
Pri tej prilezitosti vymysliet, ci nejako rozlisovat odkazy na stranky vs. na subory.

**Comment by repli2dev** [comment]
@mukrop ikonka jde udělat i pomocí css: https://waaz.xyz/adding-external-link-indicator-with-css/

**Comment by mukrop** [comment]
@repli2dev To je dobry tip, zvazim.
Ale FA som zvazoval aj kvoli inemu pouzitiu.

**Comment by mukrop** [comment]
Implementovane v #188.
