### ISSUE TITLE
verzování CSS (používání suffixu/query v URL) kvůli cache

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#163]
důvod: klienti mají cache a nezobrazují se jim změny CSS včas

jsem pro používání suffixu/query v URL - tak to, mimochodem, dělají wordpressy, vypadá to nějak takto:
`https://test.web/wp-content/themes/sydney/style.css?ver=4.9.10` a dával bych tam timestamp, lebo číslo commitu znám až PO commitu, ne? (@repli2dev)

_Originally posted by @crysman in https://github.com/mukrop/faktaoklimatu/pull/159#issuecomment-527798370_

**Comment by repli2dev** [comment]
Vezmu si to, tohle by měl být one-liner.

**Comment by repli2dev** [comment]
Přidal jsem tam build time, je jednoduše k dispozici.

Dal jsem to i u infografik ať když se změní tak se aktualizují... z dalších důležitých obrázků tam je jen favicon a tam není úplně důvod to dělat. (Jinak řečeno, udělat to přesně by znamenalo preprocesovat celý CSS a z něj externě načítané věci a řadu dalších externích souborů), současné nastavení stylu a infografik jako nejdůležitějších a nejčastěji měněných souborů ze mě OK.

**Comment by mukrop** [comment]
Vyzera to OK. Len zvazujem --  je to nune aj pri obrazkoch? Ako velmi to prehliadace cachuju? Az tak casto sa infografiky nemenia a toto sposobi, ze to budu prehliadace tahat znova pri kazdom nasom novom builde (aj kde sa infogarfiky nemenili).

**Comment by repli2dev** [comment]
@mukrop prohlížeči je jedno jestli je to styl nebo obrázek, obojí je soubor u kterého přichází informace kešovat.  Kdybychom měli verzi infografiky, šla by tam dát ona. Pokud si myslíš, že inforgrafiky se budou měnit málo, klidně to u nich zruš.

**Comment by mukrop** [comment]
Myslim, ze sa budu menit malo, ale pred rozhodnutim by som sa este spytal: Tusis, aky je asi cache timeout u roznych klientov? (Alebo to ovplyvnuje aj server?) Ja totiz nemam odhad, ci je to v hodinach, dnoch alebo tyznoch.

**Comment by repli2dev** [comment]
@mukrop nastavuje to server (pogooglil bych co github pages), klient nad tím může (a typicky dělá) nějakou chytristiku (obzvláště třeba Chrome)

**Comment by mukrop** [comment]
GH pages nastavuje expiraciu cache na vsetko na 10 minut. Ale chapem, ze klienti nad tym este mozu robit magic. Na CSS by som to nechal, ale z infografik vyhodil.

**Comment by mukrop** [comment]
Uzavrete v #169.
