### ISSUE TITLE
Přidat Martina Jonáše do GITu

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#170]
... abych mu muhl assignovat úkoly, na kterých pracuje

**Comment by ondraspribyla** [comment]
update> zjistil jsem, že martin jonas na gitu je, @martinjonas, stejne jako @protivinsky, ale nemuzu jim assignovat issue... což bych ale rád, ať mám pořádek v tom, kdo na čem dělá...

**Comment by mukrop** [comment]
Ja som ho pridaval obratom vo stvrtok, ale on musi prijat pozvanku, ktora
mu pride mailom.

> Tomas je rovnaky pripad.

**Comment by protivinsky** [comment]
Prijato (nevsiml jsem si predtim ze to vyzaduje moji reakci)

**Comment by mukrop** [comment]
Martinovi som sa pripomenul na Messengeri, potvrdil, mas ho tam.

>
