### ISSUE TITLE
nevalidní HTML kód

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#173]
máme jeden error a jeden warning přímo na landing page, další jsem nekontroloval:
https://validator.w3.org/nu/?doc=https%3A%2F%2Ffaktaoklimatu.cz%2F @repli2dev @mukrop

**Comment by mukrop** [comment]
Preberieme vo stvrtok osobne.
Prihadzujem na stvrtok do agendy systematicnost prace a bikeshed problem.

**Comment by crysman** [comment]
ok, prozatím odstraňuju "chyba" tag, lebo mi to přijde zbytečně poutající pozornost, ještě jak to je červené...

**Comment by mukrop** [comment]
Presiel som niekolko nastrojov na kontrolu. Vacsinou dopadame dobre, hlasene chyby su menej relevantne a casto by vyzadovali vyraznejsie zmenit strukturu HTML. Aktualne zatvaram.
