### ISSUE TITLE
Vytvořit základní vysvětlující stránky/rozkliky

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#19]
- Co je CO2 Ekvivalent?
- CO je teplotní anomálie a proč se používá
- Základní údaje o emisní náročnosti  různých druhů dopravy či jiných procesů

**Comment by mukrop** [comment]
Hm. Chapem, preco by si to tam chcel. Moja uvaha je ale nasledovna: Chceme, aby stranky k jednotlivym infografikam boli samonosne. Tj. na kazdej stranke k emisiam by vo vysvetkujucom texte malo byt strucne napisane, co je CO2eq. Ak to chceme rozvinut do detailov, mozme vytvorit samostatnu podstranku typu FAQ, kde tieto popisy budu -- ale zase si hovorim, nie je to znovuobjavovanie Ameriky? Nemohli by sme len linkovat nikoho, kto to uz popisuje? (Napr. cesku Wikipediu, ak to ma.)

Co si myslia @kikinna a @crysman?

**Comment by mukrop** [comment]
@ondraspribyla: Ako vidis toto? Stale plati, ze taku nejaku sekciu tam chceme?

**Comment by kikinna** [comment]
Včera jsme se zrovna o tom s Ondrášem zrovna trochu bavili. ))
Na jednu stranu nechceme znovuobjevovat Ameriku, na druhou stranu si myslím, že by bylo fajn mít něco ala "cheat sheet" s jednotkami a pojmy, co používáme a nemusí být obecně známé. (Myslím, že něco obdobného má na konci knížka There is no planet B.)
A popravdě, myslím, že se dokážeme zamyslet nad tím, jak to lidem vysvětlit stručně a jasně a Wikipedie umí být často matoucí, protože tam je spousta informací navíc a dost často obecně popsané. Zároveň by tím pádem vznikl takovej Slovníček pojmů týkajících se klimatické změny, což může být taky užitečné pro lidi, kteří o tom chtějí vést debatu? Maybe?

**Comment by mukrop** [comment]
OK, to znie rozumne.
Nechavam teda otvorene s tym, ze format a design sa vymysli, ked budeme mat obsah.

**Comment by mukrop** [comment]
Zatvatam, duplicitny s #112.
