### ISSUE TITLE
Podzemní voda

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#192]
Issue k skladování odkazů a diskusi k tématu podzení voda (budoucí podklady pro infografiky)

https://news.uci.edu/2015/06/16/a-third-of-the-worlds-biggest-groundwater-basins-are-in-distress/

**Comment by ondraspribyla** [comment]
Nicméně, hledám data, ze kterých vycházet. Našel jsem zprávy o hydrologické bilanci množství a jakosti vody v čr, od roku 2002 http://voda.chmi.cz/opzv/bilance/bilance.htm.

Zprávy obsahují docela podrobné informce o srážkách, odtoku, zásobách sněhu a zásoby vody v půdě. Lépe se podívat http://voda.chmi.cz/opzv/bilance/zprava_bilance_08.pdf na stránku 17, zajímavé mně přišly i odchylky od dlouhodobé normy.

Nejsem si jist, jestli celkové srážky budou mít nějaký významný pokles, nicméně mohlo by být zajímavé vykrestlit data o vodě v půdě či zásobách sněhu — možná ještě zajímavější by mohly být odchylky — jestli se například výkyvy srážek stavají časem extrémnější.

Nejpodstatnější otázka, kterou si pokládám, je, zda je 15 let dostatečně dlouhá doba na to usuzovat jakýkoli vývoj, tedy i za předpokladu, že tam nějaký je :). Tedy, zda se má smysl do toho pouštět.

Díky za info, hezkej den
Blonďák (Ondřej Lomič)

**Comment by lamanchy** [comment]
Mno, zkusil jsem data vykreslit, co z toho vyleze, spíše jen ze zvědavosti. Všechny hodnoty jsou průměrem za daný měsíc přes všechny oblasti, když nad tím přemýšlím, suma by asi dávala větší smysl), nicméně pro relativní porovnání trendu to vychází stejně.

Info o předpovědi poklesů průtoků jsem našel [zde](http://portal.chmi.cz/historicka-data/pocasi/zmena-klimatu/zakladni-informace), konkrétně [zde](http://portal.chmi.cz/files/portal/docs/meteo/ok/klimazmena/files/cc_chap11.pdf).

![odtok celkovy mereny](https://user-images.githubusercontent.com/4850265/65170686-7ad8b100-da49-11e9-8f92-73ae5ab83b1f.png)
![odtok zakladni](https://user-images.githubusercontent.com/4850265/65170687-7b714780-da49-11e9-8588-6279045c0d4e.png)
![prirozene prutoky](https://user-images.githubusercontent.com/4850265/65170688-7b714780-da49-11e9-8521-bc6b9da4408f.png)
![srazky](https://user-images.githubusercontent.com/4850265/65170689-7b714780-da49-11e9-9b9a-aa8f3d2ec2a6.png)
![zasoba snehu](https://user-images.githubusercontent.com/4850265/65170691-7c09de00-da49-11e9-99bc-a51cd74c12eb.png)
![zmena zasob podzemni vody](https://user-images.githubusercontent.com/4850265/65170692-7c09de00-da49-11e9-875a-ac1d4f881f41.png)

**Comment by jankrcal** [comment]
Téma mě zaujalo v emailové notifikaci, tak se na to koukám a mám pár náhodných otázek / komentářů:

1) Mám radost, že ses do toho pustil :)

2) Překvapuje mě, jak klesá celkový odtok. To je suma průtoků řek, které vytékají z republiky? Vzhledem k tomu, jak oproti tomu málo klesají srážky, tomu nerozumím. Znamená to, že se víc odpaří a mraky utečou za hranice?

3) Graf zásob podzemní vody mi nepřijde čitelný, když je to derivace. Nemůžeš to zintegrovat? (nevím, jestli je známé "c" pro integraci, ale na tom teď nesejde). Přijde mi škoda, že tam nejsou novější data, když léto 2018 bylo tak výrazný sucho. Možná by stálo za to počkat, až ČHMI zveřejní bilanci za 2018?

4) Obecně, když se dívám na ty grafy, které klesají, tak si spekticky musím přiznat: "A není to normální a přirozená variace v datech, která nemá nic společného se změnou klimatu?" Proč nejsou starší data než 2002? To ČHMI neměřil nebo to nemají digitálně nebo to jen nemají zpracované to souhrnných zpráv? Nestálo by za to jim napsat?

**Comment by lamanchy** [comment]
1. Já taky :D
1. Konkrétně je to průměr průtoků přes 10 bilančních oblastí, takže v zásadě suma podělená deseti. 
Myslím, že jo, že to funguje tak, že naprší stejně, ale voda se odpaří, než aby odtekla.
1. Mno, ono asi není třeba integrovat, lze vidět, že hladina podzemních vod neklesá (aspoň ne dle těchto dat, za toto období), to by musela být derivace stabilně pod nulou. Naopak mi přijde dost zajímavé, že k začátku období se přes jaro hladiny zvýšili a k podzimu zase vrátili "zpět", ta tendence s časem mizí.
1. Zkusím napsat, taky se mi to nelíbí. Určitě tuším, že nějaká měření budou, jen asi ne takto zpracovaná. Nicméně, zkoušel jsem uříznout první dva roky, které vypadjí, že by mohly být extrém a tím to celé naklápí, ale kupodivu to bez nich vypadá ještě hůř. :D

Trochu grafy ještě doladím a pak jim pošlu dotaz, jednak čím vysvětlit jak klesající průtoky toků, tak tu změnu hladiny podzemních vod, případně zda nemají i starší data, či ideálně i data za poslední rok, většinou to zveřejňovali kolem srpna, už by mohl být ten čas... :)

Dík za reakci

**Comment by jankrcal** [comment]
Ad predchozi:
  3. Ja to v tom teda nevidim :) Souhlasim zbeznym pohledem, ze nedochazi k vyraznemu ubytku. Ale jestli za sledovane obdobi hladina spodni vody neklesla treba o 3-5%, to z toho nejsem schopen usoudit.

Prolistoval jsem zbezne tu zpravu CHMU za lonsky rok, zaujalo me nekolik veci:
 - U nekterych metrik, napr. srazek, udavaji odchylku od dlouhodobeho prumeru (za roky 1981 - 2010). To znamena, ze nejaka starsi data maji, navic to muzeme dostat do perspektivy.
 - Prijde mi ok mit na webu graf, ktery ukazuje, ze v Cesku _nedochazi_ ke zmene uhrnu srazek, prip. nejake dalsi veliciny. Jakoze ne vsechno se meni.
 - Soucasne mi u srazek prijde hodne zajimave, jak se (ne)meni jejich rozdeleni v case. Jestli neni vic narazovych destu a mezi tim obdobi sucha. Tady bychom potrebovali aspon uhrny za den, aby tam neco mohlo byt videt. Zda se, ze pro par stanic je volne ke stazeni od roku 61: http://portal.chmi.cz/historicka-data/pocasi/denni-data.
 - Taky me dost zaujaly rozsahle tabulky o kvalite / znecisteni podzemni vody. Sice neni primo zmena klimatu, ale k tematu vlivu cloveka na zivotni prostredi je to porad blizko. Kdyz se divam na jeden rok, tak z toho nic nevykoukam. Tady by zase bylo potreba srovnavat v dlouhodobem horizontu. Koukam na http://hydro.chmi.cz/isarrow/, ale zatim nevidim moznost snadno stahnout data.

**Comment by lamanchy** [comment]
Zde je hladina podzemních vod, začínající na 0 (když neznám to C).
![hladina zasob podzemni vody](https://user-images.githubusercontent.com/4850265/65311377-7ff44800-db90-11e9-9b71-62a76b032536.png)

A zde je "celkový pohyb podzemních vod", tedy původní graf akorát všechny hodnoty jsou v absolutní hodnotě.
![celkovy pohyb zasob podzemni vody](https://user-images.githubusercontent.com/4850265/65311391-8682bf80-db90-11e9-882e-e807d74cc562.png)

Na chmi jsem napsal včera ráno, na odpověď čekám, nicméně dnes se objevila zpráva za 2018, tak jsem ji přidal.

Denní data vypadají zajímavě, zkusím se podívat, jestli jsou v intenzitách srážek nějaké extrémy, případně co jiného by z toho šlo vytáhnout. Jsou tam záznamy i z rychlosti větru, tlaku, vlhkosti, výšky sněhu a slunečního svitu. Taky tam jsou min. a max. denní teploty, třeba by mohla být variace i v jejich rozdílu. 

Ona by měla exitovat stránka [IS Množství](http://hydro.chmi.cz/osd/index.php?id=mnozstvi/index.php), právě o povrchových / podzemních vodách s historickými daty, nicméně aktuálně není v provozu...

Ad kvalita vody, to mohlo být zajímavé, ale určitě bych to oddělil od této issue :D

**Comment by jankrcal** [comment]
Diky!

A diky za integraci (a musim uznat, zes to v tom videl +- spravne :))
Od roku 2010 (obecne hodne tepla dekada) spodni vody celkem dost klesly (cca 50cm), ale rozhodne to neni zadna bezprecedentni zmena. 

Co me prekvapuje, ze ani rok 2019 neprinasi znatelny ubytek spodnich vod. Coz je pro me kontra-intuitivni vzhledem k intenzivnimu suchu (nebo aspon jeho medialni prezenci). Mozna je v krajine mnohem vice videt povrchova voda (tedy ty uplne prvni dva grafy, ktere jsi poslal).

Celkove srazkam a vode malo rozumim, abych si dovolil interpretovat data, tedy rict, ktere trendy jsou podstatne a ktere nepodstatne.
@ondraspribyla Mas Ty prehled o vode a suchu, tedy o tom, ktere z techto trendu jsou podstatne vzhledem ke klimaticke zmene?
Prip. myslim muzeme pozadat CHMU o konzultaci.

**Comment by lamanchy** [comment]
Jen update, z CHMI se stále nikdo neozval, zkusil jsem se dnes připomenout.

A pár zajímavostí, na které jsem mezitím narazil:

1. Dle [bakalářky](https://theses.cz/id/sd6nl1/BP_Houdek.pdf?fbclid=IwAR0M6n1pI-93Wtl83WbUCJby812bFaqXBbrKrW7OMFUuoB--5OunLI3UF64) (i wiki) je rychlost evapotranspirace cca lineární k teplotě, nicméně zarazila mě ta změna:
    - Za zimu je to 45mm, na podzim 105mm, na jaře 210mm a v létě 325mm. (to je množství na m2 za roční období v česku).
    - To docela odpovídá i průměrným dlouhodobým teplotám za dané období (-3.3 2.4 6.7 15.9), nicméně spíše je zajímavé, že oteplení o stupneň znamená (325-45)/(15.9 - (- 3.3))*4 = 58 mm vody ročně. Oteplení o 2 stupně pak na ploše české republiky dělá zvýšení ročního odpaření o 9 miliard metrů krychlových za rok. To je stejná hodnota, jako dlouhodobý průtok labe za rok v ústí nad labem. 
    - Jakože, jsem si vědom, že je to jen velmi hrubý odhad, navíc data pochází z bakalářky, mno. Jen že by to mohl být zajímavý směr.
2. Naházel jsem denní data do influxu a udělal jsem pár grafů v grafaně. Pracuji s tím v práci, tak to šlo docela rychle, vlevo je vždy absolutní hodnota (suma či průměr, dle toho, co dávalo větší smysl), vpravo je poté směrodatná odchylka. Vím, že data nejsou úplně normálního rozdělení, nejsem si však jist, co použít na detekci, no, odchylky. 5. a 95. percentil by byl lepší? To taky není problém. Vždy je tam i průměr za posledních 10 let.
![slunce](https://user-images.githubusercontent.com/4850265/65498259-df699500-debb-11e9-93b9-ba65bfbfcf9f.PNG)
![snih](https://user-images.githubusercontent.com/4850265/65498260-e0022b80-debb-11e9-8d26-2cebc39cb7b1.PNG)
![srazky](https://user-images.githubusercontent.com/4850265/65498261-e0022b80-debb-11e9-82a1-2122270e65a6.PNG)
![teplota](https://user-images.githubusercontent.com/4850265/65498262-e0022b80-debb-11e9-8618-a9fc053f1a6b.PNG)
![tlak](https://user-images.githubusercontent.com/4850265/65498263-e0022b80-debb-11e9-92b9-5d720635af92.PNG)
![vitr](https://user-images.githubusercontent.com/4850265/65498264-e0022b80-debb-11e9-8b0e-e40ce94c83e3.PNG)
![vlhkost](https://user-images.githubusercontent.com/4850265/65498266-e09ac200-debb-11e9-8e11-6f10dae1468c.PNG)
3. Nakonec přidávám i histogramy z průměrné teploty přes měsíce, to jsem si jen tak hrál s tím, co grafana umí :). Jeden má raw hodnoty, druhý je průměr za 10 let (proto je o 10 políček kratší ;) ). 
![Annotation 2019-09-20 155419](https://user-images.githubusercontent.com/4850265/65498655-949c4d00-debc-11e9-8f7e-51d468c5990f.png)
![Capture](https://user-images.githubusercontent.com/4850265/65498658-949c4d00-debc-11e9-99ea-fc880b6e79fa.PNG)

**Comment by jankrcal** [comment]
Pěkný, díky!

Co je pro mě zajímavý, že ty srážky ani v detailnějších datech nevykazují žádný viditelný trend :)
Směrodatné odchylky nic, jsou tam jen vidět občas extrémní roky (např. povodňový rok 1997).
Suma taky nic, dokonce ani "extrémně suchý" rok 2018 nemá nijak mimořádně nízké srážky (jakože tak 10 dalších let ze sledovaného období má přiližné podobně nízké srážky).

Takže se zdá, že je potřeba se dívat na kombinaci srážek a průměrné teploty, aby člověk mohl vysvětlit množství povrchové vody a sucho.

Stejně mi to nejde do hlavy, co se s tou v Česku vypařenou vodou děje. Jiný zdroje (např. velmi stručně [1]) tvrdí, že ve střední Evropě úhrnné srážky dlouhodobě spíše rostou, což by dávalo smysl vzhledem k tomu, že se více vypaří, ale zdá se, že to u nás neroste úměrně k tomu, co se vypaří.

Přemýšlím na hrubo nad tím, jaké sdělení pro infografiku by se z těchto dat dala vyrobit:
 1) Úhrn srážek se skoro nemění
     (taková klidná grafika na vyvážení, ne všechno se mění nebo aspoň ne tak, jak byste si mohli myslet).
 2) Úhrn srážek se nemění, ale (povrchové) vody je čím dál méně. 
     (kromě srážek ukázat i odtoky řek jako zjednodušenou metriku pro vyjádření množství povrchové vody).
 3) Úhrn srážek se nemění, ale (povrchové) vody je čím dál méně, protože se kvůli teplu mnohem víc vypaří.

Nejvíc by se mi líbila verze 3), ale na to bychom asi potřebovali mít nějaká měření vypařování vody nebo aspoň přesněji rozumět klimatickým modelům, jak vypařování funguje. Nenapadá Tě nějaký další zdroj pro toto?

Co si o těch datech zatím myslíš Ty?

[1] http://www.klimatickazmena.cz/download/2893542239471599f8e5787847497cc9/5.%20kapitola_pozorovan%C3%A9%20zm%C4%9Bny.pdf, kap. 5.4

**Comment by lamanchy** [comment]
Dík. ;)

Nedříve bych zmínil, že z Chmi kdosi odpověděl, že dotaz předal kolegovi, co se hydrologickou bilancí zabývá, že odpoví, jen co bude mít čas.

Líbí se mi, jakým způsobem přemýšlíš nad potencionální infografikou, také se mi nejvíce líbí 3. verze, i když ještě přemýšlím, jestli dluhodobá data ze zásob podzemních vod budou taky nějak zajímavá.

Zkusím pohledat nějaký zdroj, myslím, že by mohl pomoci ten kontakt z CHMI, až se ozve.

Čeho jsem si všiml já:
- Možná by stálo za to udělat infografiku "sníh na Lysé hoře". Inu, klesá, denní průměr za 20 let klesl za posledních 40 let o 25%. Nepovažuji to ani za "vybírání" dat, co vypadají dobře, z deseti stanic je ta na Lysé hoře ta jediná, kde pravidelně bývá nějaký sníh, narozdíl třeba od Prahy. Ač to asi není nic objevného, že když je větší teplo tak je méně sněhu, myslím, že zpráva "oteplilo se o 2 stupně" člověka tak nerozhodí, jako "Na lysé hoře je o čtvrtinu méně sněhu".
- _Pokud_ je vypařování důvodem ztráty vody, přišlo by mi zajímavé nějak zpracovat závislost evapotranspirace na teplotě. Vím, že výpočet v minulém commentu je _velmi_ hrubý, fakt mě ale překvapilo, jaký dopad může mít oteplení o jeden stupeň na odpařování. Zase ovšem, bude to chtít asi trochu lepší zdroj...
- Jakože, nedává mi smysl, že klesá průměrná vlhkost :D. Jakože, fouká méně (nebo aspoň ne více), teplejší vzduch pojme větší množství vlhkosti, pokud se více vody vypaří, nemělo by se to nějak projevit? :D. To jen, že mi to přijde hrozně neintuitivní.

**Comment by jankrcal** [comment]
Otázka je, jak to s tou vlhkostí funguje. Třeba ta vypařená voda v teplém počasí stoupá nahoru do vyšších vrstev a vlhkost se měří dole u země? Současně nižší vlhkost dále nahrává rychlejšímu vypařování, což dál podporuje, že vnímáme sucho.


Teď bych chtěl poodstoupit a pár kroků zpět:
 - přes všechnu Tvoji skvělou práci tady *zatím* z mého pohledu nejsou dost jasné trendy a dost jasné porozumění celé problematice, abychom si mohli dovolit z toho udělat grafiku;
 - to, co děláš, je v podstatě výzkum, což s sebou přináší velké riziko, že to nevyjde, že to víc úsilí neprolomí;
 - volal jsem si o víkendu s Ondrášem a ten taky vyjadřoval určitou skepsi k tomu, jestli to je materiál na grafiku.

Z mého pohledu by tématu srážek / podzemní vody / povrchové vody pomohlo, 
 - kdybychom měli nějaký dost renomovaný článek tvrdící něco, co bychom chtěli prezentovat, nebo
 - kdybychom měli dost renomovaného hydrologa, který by zaštítil, že to, co chceme prezentovat, je vědecky relevantní.
Ale celkově je Ondráš ten, kdo má hlavní slovo při "posílání grafiky do produkce", tak to doporučuju probrat s ním.

Nechceš přijít ve středu na Klimaton? (od 17h na FI MU, místnost A220)
Tam bys to mohl přímo s Ondrášem probrat, co by se s tím dalo dál dělat.
A nebo se příp. nadchnout pro nějaký jiný méně riskantní datový úkol :)
(já tam nebudu, budu v Mnichově, ale bude tam spousta jiných milých lidí :)

**Comment by lamanchy** [comment]
Během dnešního klimatonu mně odpověděl Radek Vlnas z CHMI, fakta o klimatu považuje za super, mé grafy už tak ne (se dalo čekat, tu lin. regresi jsem si mohl odpustit). Hlavně ale i proto, že metodika získání těch veličin se lehce v průběhu měnila, takže data nejsou takto porovnatelná. Nicméně přesměroval mě na (článek, strana 27)[https://www.vtei.cz/wp-content/uploads/2015/08/vtei_2015_4-51.pdf], který se věnuje trendům.

Z článku bych si odnesl větu ze závěru: "Ačkoli tyto závěry mohou při častém užívání výrazu „pokles“ vyznívat pesimisticky, platí, že na výrazné většině stanic nebyl zjištěn statisticky významný trend."

Tímto bych tedy toto téma opustil, budu se věnovat infografice, co jsme dnes začali na klimatonu ;).

**Comment by ondraspribyla** [comment]
@lamanchy Navrhuju issue zavřít, souhlasíš? Nebo na tom chceš ještě pracovat? - nějak mi to nesedí s vyschlýmipotoky v minulém létě... ale asi nic lepšího nenajdem. **Chci ještě dodat, žes na tom odvedl obrovské množství práce!**

**Comment by lamanchy** [comment]
@ondraspribyla Jop, souhlasím. Možná jen přemýšlím nad tím, jak je tedy vlastně aktuální sucho v čr ovlivěno klimatickou změnou. Protože přímo odpověď z chmi obsahovala:
"3 ze 4 poslednich let byly srazky mimoradne podnormalni, spadlo kolem 70 % srazek, nebyl snih, takze nebylo z ceho doplnovat zasoby podzemni vody."
z čehož mi vyplývá, že poslední roky je prostě sucho, vyší evaporace tomu nepomáhá, ale to jsou jednotky procent.
Což si vlastně nejsem jist, jestli by nebyla dobrá informace na stránky "faktaoklimatu". Na jednu stranu říci, že globální oteplování srážky nijak neovlivňuje, to také není pravda, na druhou stranu často vidím: "aktuální sucho je způsobeno oteplováním" - což je vlastně výrok, který taky nebude úplně pravdivý. Aktuálně to v česku vypadá spíše na odchylku, než na změnu klimatu.

Ale to jsou jen úvahy :D. Klidně ji zavři, tento klimaton nestíhám kvůli víkendovce, ale na ten příští už třeba konečně nalákám Peťu Kuse, pokud se ti ještě neozval. A i já třeba zase budu mít více času :)
