### ISSUE TITLE
Nemůžu pushnout novou branch

### ISSUE THREAD

**Issue by lamanchy** [mukrop/faktaoklimatu#194]
Při instalaci lokálního verze (`bundle install`) byl problém s chybějícími závislostmi, chtěl jsem přidal poznámku do readme, nicméně ačkoli zdá že pull request mohu vytvořit, novou branch pushnout nemohu.
Díky

**Comment by mukrop** [comment]
Ahoj. Dik za chut pomahat a opravovat :-).
To, ze branch pridat nemozes je vedome nastavenie -- pristup do repa ma len core tim projektu. Ale vitame pull requesty od kohokolvek. (Standardny GitHub flow: projekt si forknes k sebe, vytvoris vetvu s novymi zmenami a urobis pull request spat k nam.)
Ak by si s niecim potreboval pomoct, kludne sa spytaj.

**Comment by lamanchy** [comment]
@mukrop ah, díky, nedošlo mi, že musím projekt forknout. Díky
