### ISSUE TITLE
Divestment (odinvestovani fosilnich paliv)

### ISSUE THREAD

**Issue by protivinsky** [mukrop/faktaoklimatu#195]
Zatim spis jako obecna otazka, co vsechno to znamena a jestli by bylo mozne a uzitecne to nejak zpracovat. Issue nam umozni centralizovat informace. Co vsechno to muze obnaset shrnuje obsahly clanek: https://www.newyorker.com/news/daily-comment/money-is-the-oxygen-on-which-the-fire-of-global-warming-burns

1) velke banky prestanou pujcovat rozsahlym fosilnim projektum (pripadne lze rozdelit na “nepujcovat na nove zacinajici projekty” a nasledne “snizovat financovani existujicich projektu”)
2) velke investicni fondy budou snizovat zastoupeni fosilnich firem ve svych portfoliich (a nabizet klientum vice nefosilni investicni produkty)
3) pojistovny se zavazou nepojistovat fosilni projekty
4) obcane se mohou zapojovat do kampani, protestu a bojkotu usilujicich o dosazeni vyse uvedenych bodu (napr. protesty ci bojkoty pobocek vyse uvedenych bank)

Obecne zatim nemam na tema prilis uceleny nazor, nicmene povazuji za uzitecne je vice zmapovat a zorientovat se v nem.

**Comment by protivinsky** [comment]
Report “Banking on Climate” - https://www.ran.org/wp-content/uploads/2019/03/Banking_on_Climate_Change_2019_vFINAL1.pdf

**Comment by ondraspribyla** [comment]
Jelikoz je to zatim jen napad, p5esunul jsem to do WIKI, sekce "Napady na infografiky" a 'Knowledge base"
Timto zaviram
