### ISSUE TITLE
Nefunkční zadávání odkazů

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#20]
V zdrojových kódech ...emise-1.md a ...emise-2.md jsem se pokusil zadat linky na jiné stránky.
Nefunguje ani MD []{}, ani <a href=...>
Nevím, jestli dělám chybu já, nebo je problém někde v překladu...

**Comment by repli2dev** [comment]
Markdown používá formát `- [Srovnání emisí jednotlivých sektorů ČR na obyvatele s dalšími státy EU](https://faktaoklimatu.cz/infographics/emise-3/)` tzn. kulaté závorky namísto složených.

**Comment by repli2dev** [comment]
Zkusil jsem to upravit v `emise-1` a vypadá to, že to minimálně v tomto kontextu funguje.

**Comment by ondraspribyla** [comment]
Děkuju!

Dne út 9. 7. 2019 7:03 uživatel Jan Drábek <notifications@github.com>
napsal:
