### ISSUE TITLE
nefunkční hyperlink

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#203]
jeden zdroj vyhazuje:

> Forbidden You don't have permission to access /data/atmospheric_co2/icecore_merged_products on this server.

konkrétně je to tento: `http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products`,

debug data zde:
```
❱ grep -iRI "http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products" ./
./_infografiky/teploty/koncentrace-co2.md:            , [ "Scripps", "http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products" ]
./_infografiky/teploty/koncentrace-co2.md:* Mladší data (0-2000 let před současností) jsou složením současných měření na Mauna Loa, Hawai a měření z ledovcových vrtů na Jižním pólu ([data Scripps](http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products)).
./_site/infografiky/koncentrace-co2.html:                  <a class="ext-link dropdown-item" id="data-original-1" href="http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products" target="_blank" rel="noopener noreferrer">Scripps</a>
./_site/infografiky/koncentrace-co2.html:  <li>Mladší data (0-2000 let před současností) jsou složením současných měření na Mauna Loa, Hawai a&nbsp;měření z&nbsp;ledovcových vrtů na Jižním pólu (<a href="http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products" target="_blank" rel="noopener noreferrer" class="ext-link">data Scripps</a>).</li>
./.jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown/f0/4cc28f32e57ec051c8b4dbf98bf53e9baffd8a7ef7f1d2d86c27992352263f:  <li>Mladší data (0-2000 let před současností) jsou složením současných měření na Mauna Loa, Hawai a měření z ledovcových vrtů na Jižním pólu (<a href="http://scrippsco2.ucsd.edu/data/atmospheric_co2/icecore_merged_products">data Scripps</a>).</li>
```

(zjištěno díky tomu mojemu watchdogu)

Žádný link na stránce http://scrippsco2.ucsd.edu/data/atmospheric_co2/ není dostupný (stejný error), takže jsem je (`rkeeling@ucsd.edu`) už kontaktoval a uvidíme, co mi odepíšou...

**Comment by mukrop** [comment]
To je novinka, tie data fungovali (sam som ich nedavno pouzival).

Pockal by som, co sa stane za par dni, resp. co ti odpisu.

**Comment by crysman** [comment]
Odpověď:
> Thanks for the interest. We are aware of the issue and are working on it.
> -Ralph

no, počkáme chvílu...

**Comment by crysman** [comment]
Watchdog hlásí:
> %%MSG: trying to find something...
> Found no broken links.

Takže vše OK, ručně ověřeno - už to opravili.

Každopádně, plyne z toho, že crysmanův watchdog má stále užitečné uplatnění - jsme schopni linky kontrolovat i systémově pravidelnějc, než jen při merge do mastera? @mukrop

**Comment by mukrop** [comment]
Ack, ignore na tuto domenu som odstranil.

Mne sa stale nezda, ze toto je nieco, co by sme chceli kontrolovat castejsie, ako to aktualne kontrolujeme. Aj tak sme s tym nic neurobili, cakali sme, kym si to vyriesia oni. Menit kvoli nedostupnosti odkaz na nieco ine (alebo archive verziu) mi pride relevantne az v momente, ked bud je link neaktivny vyse 1-3 mesiace alebo zodpovedne vieme, ze aktivny nebude alebo sa o to nikto nestara (a kedze linkujeme pomerne zodpovedne zdroje, tak casto sa to nestava).

Kazdopadne je samozrejme v pohode watchdoga s nechat, ak ho chces :-).
