### ISSUE TITLE
Studie: Stern Review

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#218]
Jako základní překlad pro OBSAH studie by asi stačil:  http://www.lse.ac.uk/GranthamInstitute/publication/the-economics-of-climate-change-the-stern-review/

Více z wikipedie:
https://en.wikipedia.org/wiki/Stern_Review

nebo 
https://webarchive.nationalarchives.gov.uk/20100407163608/http://www.hm-treasury.gov.uk/d/Summary_of_Conclusions.pdf

**Comment by protivinsky** [comment]
Ceska verze: http://amper.ped.muni.cz/gw/stern_review/
Je to preklad executive summary.

**Comment by protivinsky** [comment]
@ondraspribyla prvni nastrel Sternovy zpravy pro web: https://docs.google.com/document/d/1DKylin0Ew6nd1fJ9pgg3AvkS-tb8A3GcFv9oGeRcC7I/edit#

Akorat je to dost dlouhe. V podstate shrnuti executive summary, zatim jsem vybral vsechno, co mi prislo zajimave. Zkusim to pak jeste projit a treba polovinu toho vynechat, ale je to tezke, je to informacne hutne. Pripadne uvitam i komentar, pokud ti napriklad nektere casti prijdou zbytecne nebo rusive.

**Comment by ondraspribyla** [comment]
Hustý :-) mrknu na to. Mám teď dost cekaciho času (čekám po rentgenu,
zlomil jsem si nohu)
Tak doufám, že me vezmou dřív než mi dojde baterka.

Dne ne 6. 10. 2019 14:18 uživatel Tomas Protivinsky <
notifications@github.com> napsal:

**Comment by protivinsky** [comment]
Zrevidoval jsem text a vytvoril PR - https://github.com/mukrop/faktaoklimatu/pull/225

**Comment by protivinsky** [comment]
Zvazuji posledni drobnost - existuje ceska verze executive summary, zaroven ty anglicke stranky nejsou prilis uzivatelsky privetive (samotna stranka studie na HM Treasury uz dnes neexistuje). 

Povazoval bych za uzitecne doplnit odkaz na tu ceskou verzi, nejlepe do toho ramecku vpravo. @mukrop je nejaky jednoduchy zpusob jak to muzeme udelat technicky? Toto je odkaz: http://amper.ped.muni.cz/gw/stern_review/

A diky za typografii a merge!

**Comment by mukrop** [comment]
Odkaz na ceske zhrnutie som pridal.

**Comment by setcz** [comment]
Ondráš mi před šesti dny psal, ať zkouknu Sternovu studii - _"proofreading spíše významový a stylistycký, než překlepy: https://faktaoklimatu.cz/studie/2006_sternova-zprava - je to podle tebe napsaný srozumitelně a dostatečně podrobně?"_ 

Tak jsem na to teď koukl. Přijde mi to napsané srozumitelně a dost podrobně. Přestože jsem neměl hledat jazykové věci, tak jsem jich pár našel. Když mi někdo vysvětlíte, jak udělat správně změny přímo v té stránce, tak to zvládnu udělat i v tom gitu, ale nerad bych něco rozbil. Tak to zatím píšu sem:

- "Ukazuje, že přínosy silných a včasných opatření výrazně převyšují jejich náklady, a ignorování klimatických změn povede ke snížení hospodářského růstu." - ta čárka před "a" tam podle mě nemá být:
- "Pokud nebudeme jednat, skleníkové plyny v atmosféře mohou na konci století dosáhnout trojnásobného množství oproti předindustriálnímu období (280 ppm  )." - ta závorka by chtěla vysvětlení, k čemu se vztahuje, jestli k tomu, čeho dosáhnou, nebo k tomu předindustriálnímu období (já vím, že to druhé, ale není to z toho poznat)
- "Teplota by v takovém případě by narostla" - dvakrát by
- "Cena za snížení emisí skleníkových plynů je mnohonásobně nižší než celospolečenské náklady dopadů nezmírněných klimatických změny" - je to nějaké rozpadlé na konci
- "avšak odkládání účinné akce a přijetí potřebných opatření zvyšuje cenu" - cenu čeho? (asi těch opatření, ale přidal bych tam něco jako "jejich cenu"
- "Celosvětový HDP" -> celosvětové
- "ke kterému by vedlo trvalé snížení celosvětového HDP, v každém roce vždy o 5 % předpokládané hodnoty HDP." - ta čárka je tam navíc
- "Pro odhad ekonomických dopadů klimatických změn a nákladů na mitigaci studie používá tři metody:" - trochu nešťastný slovosled, vypadá to jako "mitigace studie"

**Comment by mukrop** [comment]
Mozes to opravit priamo v gite. Pokazit to velmi nemozes, pretoze editacia mastra priamo je zakazana, vsetko podlieha pull requestom s review.

Vytvoril som ti vetvu `stern-review-tweaking`, kde to mozes opravit priamo cez webove rozhranie. Chod na https://github.com/mukrop/faktaoklimatu/blob/ster-review-polishing/_studie/2006_sternova-zprava.md, upravy mozes robit po kliku na symbol tuzky vpravo. Ak vies, ako na to, urob potom pull request a oznas ma na review (ak nie, tak napis sem a urobim to ja).

Idealne potom urob druhu zmenu a pridaj svoje meno do zoznamu vsetkych zapojenych ludi tu: https://github.com/mukrop/faktaoklimatu/blob/ster-review-polishing/AUTHORS.md

**Comment by setcz** [comment]
@mukrop Děkuju za rady a za navedení!  Zvládl jsem snad všechny kroky. Připadám si jako megahacker!:)

**Comment by mukrop** [comment]
Dakujeme hackerovi za spolupracu ;-).
