### ISSUE TITLE
newsletter nemá "zavřít" ani křížek

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#228]
newsletter nemá "zavřít" ani křížek (taková ty okna na závěr) - to může být pro dost lidí matoucí - nemůžem to nějak fixnout? @mukrop 

![image](https://user-images.githubusercontent.com/5269350/66955976-c6d83f00-f063-11e9-876a-4f4e507681b9.png)

PS: ESC ani klik mimo popup div nefunguje

**Comment by mukrop** [comment]
To ale nie je overlay na stranke faktaoklimatu.cz, to je samostatna stranka (tj. krizik mi tam nedava zmysel).

Mozno by sa dalo prestavit, aby sa to pri zadani emailovej adresy otvaralo v novom okne -- dava ti to tak zmysel?

**Comment by mukrop** [comment]
V medzicase dalsi clovek navrhol, ze by sa to mohlo otvarat v novom okne. Upravil som (#229).
