### ISSUE TITLE
Licence infografik

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#23]
Napisat k licencii viac informacii, tj. asi napisat nazov CC-BY-4.0 licencie (skontrolovat, ako sa vola v cestine) a umiestnit to vhodne vedla obrazka.

**Comment by mukrop** [comment]
Este vylepsenie: Bolo by vhodne dat ludom priamo instrukcie/text, ako to citovat (aktualne napriklad nie je jasne, ako citovat autora). Napriklad popup aj s odkazom.

**Comment by mukrop** [comment]
Z osobnej diskusie: Ako autora pouzivat neosobne "faktaoklimatu.cz".

**Comment by mukrop** [comment]
Vytvoril som modal s popisom, ako infografiky spravne zdielat.
@repli2dev: Pozries sa prosim, ci je to napisane rozumne? Pridal/vypustil by si nieco?

**Comment by repli2dev** [comment]
@mukrop rámcově OK, následující je spíš nth:

- "stabilitu" -> "dlouhodobou funkčnost"
- " použít přímo staženou infografiku" - "staženou" bych dal tučně
- Rovnou do odkazů bych generoval `rel="noopener"`, je to aktuálně standard, byť riziko je pro ty odkazující stránky a ne pro nás. Viz https://jecas.cz/noopener

**Comment by crysman** [comment]
vzhledem k reportovanému případu porušení licence navrhuju, aby:

### 1. se  licence použila i v infografice
stačí CC-BY logo, konkrétně stačí to malé: https://i.creativecommons.org/l/by/4.0/80x15.png
![image](https://user-images.githubusercontent.com/5269350/63788533-f1283e80-c8f5-11e9-9094-0254d13f7a8c.png)
@kikinna 

### 2. abychom logo měli i v rámci grafiky na webu
tj. nějak takto:
![image](https://user-images.githubusercontent.com/5269350/63789242-444ec100-c8f7-11e9-9c61-08f96deb19d9.png)

případný zdroják pro patch zde:
@mukrop 
```
<p>Všechny naše infografiky jsou k&nbsp;dispozici pro další použití pod licencí<br><a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC-BY-4.0<img alt="Licence Creative Commons" style="border-width:0;padding-left:0.5em;" src="https://i.creativecommons.org/l/by/4.0/80x15.png"></a><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"></a></p>
```

### 3. Aby se obrázek CC-BY zobrazoval na malém displayi.
V současné době mizí i s textama - takže není divu, že to někdo ořízl, pokud **licenci na svém zařízení ani neviděl**:
![image](https://user-images.githubusercontent.com/5269350/63789353-7bbd6d80-c8f7-11e9-8e4b-41da2ed3799b.png)

**Comment by mukrop** [comment]
@crysman A podla teba zahrnutie obrazku nieco zmeni? Z webu som ho vyhodil, lebo je skaredy a rovnaku informaciu nesie aj text CC-BY-4.0. Navyse (podla mna) tym, ze ten text je podciarknuty je intuitivnejsie, ze je to odkaz (v porovnani s obrazkom).
To, ze licenciu na mobile nevidel uvedenu textom nikoho neospravedlnuje predpokladat, ze tam nie je (v CR je default, ze vsetky prava patria majitelovi, tj. full copyright). Navyse pochybujem, ze cely remix infografiky, ktory publikovali, urobil na mobile.

Ja som proti vo vsetkych troch bodoch (v poslednom si viem predstavit kompromis, ze sa text licencie bude zobrazovat v skratenej podobe).

**Comment by crysman** [comment]
Ahoj do pléna všem,

díky Martinovi za rychlý názor, každopádně, trochu mě to překvapilo takové silné odmítnutí. Teď věcně:

1. mně škaredý nepřijde a "škaredý" je subjektivní, takže tady je to jen hádačka o názorech, a na to nemáme čas ani chuť - věřím tomu, že grafik to umí pojmout tak, aby to škaredé nebylo
1. nenese stejnou informaci, nese **informaci navíc**, protože poutá pozornost více než text, text je jenom text, obrázek CC-BY je něco, co chytíš okem podvědomě, protože to prostě znáš odjinud, aniž bys četl text
1. že je default copyright je sice hezké, ale na to tady lidi prdí, toto je pirátská země, pokud chceme, aby dodržovali lidi licenci, myslím, že je dobře ji explicitně podpořit. Pokud je nám dodržování jedno, můžeme to mít prostě jen textama a nic nedělat...
1. taky pochybuju, že to dělal někdo na mobilu/tabletu, ale pravdou je, že nevíme, co viděl (a že text v záplavě textu de vidět hůř než známý obrázek)
1. poslední bod je MUST, protože na malých zařízeních prostě nic o licenci není. vůbec nic.

prosím o vyjádření @kikinna a @ondraspribyla a další, díky
