### ISSUE TITLE
Carbon Capture & Storage

### ISSUE THREAD

**Issue by protivinsky** [mukrop/faktaoklimatu#248]
https://www.youtube.com/watch?v=XHX9pmQ6m_s&fbclid=IwAR2NM1KcOYKYizow32ZJ26cA8kvrgqixUqBcevJ97TWmRsOGv8-ITsHJVBw

Zaroven i IPCC uznava, ze Carbon Capture & Storage je nezbytny, pokud mame usilovat o otepleni do 1,5 °C. A prijde mi to jako zajimavy a malo znamy nastroj, zatim to oteviram spise s tim, abychom mohli shromazdovat souvisejici informace a nasledne vymyslet, jakym zpusobem to zpracovat.

Ve videu tvrdi, ze mohou provozovat CCS s cenou 94-232 $ / t CO2 (a odkazuji na stavajici technologie s cenou cca 600 $ / t CO2. Podle IPCC jsem nekde videl i nizsi odhad, nicmene tyto vypadaji duveryhodneji. Odhadoval bych, ze s dalsim rozsirenim technologii ceny jeste poklesnou. Zaroven toto take povazuji za maximalni odhady pro nezbytnou uhlikovou dan, pokud by byla v takove vysi, vedla by k masivnimu rozsireni CCS. Aktualne fungujici CCS projekty odchytavaji radove desitky milionu tun CO2 rocne.

**Comment by ondraspribyla** [comment]
Presunuto do WIKI Knowledge base. Timto zaviram

**Comment by ondraspribyla** [comment]
Presunuto do WIKI Knowledge base. Timto zaviram
