### ISSUE TITLE
Doladit datasheet emisí svět pro zveřejnění

### ISSUE THREAD

**Issue by jankrcal** [mukrop/faktaoklimatu#249]
Vytahuju stopy diskuze z #77 k tomuto datasheetu do separátní issue: konkrétně můj komentář https://github.com/mukrop/faktaoklimatu/issues/77#issuecomment-535214456:
 * Navrhoval bych oba výstupy přesunout do Shrnutí, s použitím šířek sloupců viz předchozí komentář
 * Ty oba dva číselníky bych spíš vynechal. U výstupní tabulky, která tyto kódy a české názvy a přiřazení obsahuje bych to jen okomentoval textově, že české názvy zemí jsou dle ČSÚ a rozdělení je dle world bank, wiki, atd. Asi bych tam ani nedával odkazy. Jakože o toto v těch datech fakt nejde.

A moje otázka je, uděláš to, Tome, nebo to mám udělat?

Tak jako tak bych rád udělal "recenzi" toho datasheetu, tedy zkontroloval, jestli tomu rozumím a upravil, kde tomu nerozumím. A kosmeticky poladil, kde jsem v mezičase změnil intrukce :) 

A k tomu bych potřeboval vědět, jestli můžu a jestli na to teď vhodná chvíle.

**Comment by protivinsky** [comment]
Diky - ciselnik zemi uz jsem vyhodil, naopak jsem pridal dalsi vystup pro druhou infografiku. S tvymi navrhy na upravy souhlasim, chystam se to dotahnout behem vikendu. "Recenze" tedy dava smysl az po dotazeni.

**Comment by jankrcal** [comment]
Skvělé, dej mi tedy prosím vědět, až bude vhodná chvíle.

**Comment by protivinsky** [comment]
Upraveno a pripraveno na recenzi: https://docs.google.com/spreadsheets/d/1aZNVRC7lJM28FxbKKnXo7HsPlyE2RaMbG3KDs8igwec/edit#gid=0
Diky!

**Comment by jankrcal** [comment]
Skvělé díky! Kouknu na to dnes / zítra.

Drobnosti budu rovnou upravovat, na případné větší věci kdyžtak použiju komentář.

**Comment by protivinsky** [comment]
Mimochodem zdrojova databaze EDGAR ma nejake rozbite webovky - https://edgar.jrc.ec.europa.eu/ - takze ty linky na data nefunguji. Snad to obnovi do puvodni podoby, pokud ne, budeme to muset prelinkovat.

**Comment by jankrcal** [comment]
Přijde mi to skvělý, dobře srozumitelný.

Udělal jsem spíš drobné změny:
 - sjednotil font na Arial 10,
 - změnil jazyk dokumentu na Češtinu,
 - použil jednotný formát pro čísla ve všech tabulkách,
 - u tabulek EDGAR smazal "metadata" a přesunul je do hlavního listu do dalšího sloupce,
 - ke všem vstupním přílohovým listům přidal pro jednotnost a přehlednost hlavičku, kde se opakuje odkaz na zdroj, komentář (příp. metadata),
 - nastavil chránení listů na úzkou skupinu lidí,
 - a další drobné formátovací změny.

Pokud bys měl s některou ze změn problém, napiš :)

Co mi ještě chybí je
 - Odkaz na list "Přiřazení zemí k regionům" a vysvětlení, odkud se to tahalo. Jak jsme se bavili dřív, toto jsou triviální data, ale jeden řádek v tabulce Shrnutí s krátkým komentářem si to podle mě zaslouží,
 - Pokud to půjde, náhledové grafy vytvořené v Google Tabulkách přímo z těch dat, aby člověk viděl 1:1, které výstupní tabulky souvisí se kterými grafikami. Tady to možná bude oříšek , tak to nepovažuju za nutné. Např. u druhé výstupní tabulky mě zmátly sloupce "Kumulativní populace", protože jsem si za tím hned nepředstavil tu grafiku.

Ani jedno nepovažuju za zásadní, za mě můžeme zveřejňovat.

**Comment by protivinsky** [comment]
Diky za upravy!

- Pridal jsem odkaz na "Prirazeni zemi k regionum" do vstupu.
- Ani jeden z grafu v Google tabulkach vytvorit neumim (tree mapy tam sice jsou, ale nepovedlo se mi z nich dostat nasi grafiku - Google tabulky k nim chteji vice promenych, zjevne ten graf konstruuji odlisne). Pripadne tam muzeme primo nakopirovat nase infografiky pro srovnani s daty?

**Comment by jankrcal** [comment]
Tohle mu trochu uniklo, omlouvám se za měsíční latenci :)

Kopirovani infografik mi neprijde dobre -- prijde mi dulezite, aby bylo videt, jak to z tech dat v tabulce tvorime. 

Pridal jsem tree mapu (a kvůli ní také jeden šedý sloupec). Pokud by Ti to přišlo blbý, zas ji smaž. Jinak toto issue zavírám, protože datasheet je dávno zveřejněný :)
