### ISSUE TITLE
Studie: Stabilizing climate requires near-zero emissions 

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#255]
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2007GL032388

projít, možná dodat do studií.

**Comment by protivinsky** [comment]
Procetl jsem, je to kratke; clanek zhruba rika:

Carbon sinks (puda, ocean) pohlcuji emise uhliku z atmosfery, ale zaroven ohrev atmosfery vede k otepleni oceanu. I pokud prestaneme vypoustet emise uhliku temer uplne a CO2 v atmosfere bude klesat v dusledku carbon sinks, teplota presto bude po nekolik staleti stabilne zvysena, protoze pokles CO2 v atmosfere bude vyvazen oteplenim oceanu. Proto pro dosazeni stabilni teploty je potreba zredukovat emise v podstate na nulu.

Graf nize predpoklada snizeni emisi na nulu po dosazeni urcite urovne (50 / 200 / 500 / 2000 GtC; pozor, GtC, nikoli GtCO2). cast A ukazuje kumulativni emise, B atmosfericky CO2 (klesa v dusledku carbon sinks), C zmenu teploty oceanu (vzrusta po dlouhe obdobi) a D zmenu teploty atmosfery - zustava vicemene stabilni, protoze efekty B a C se vzajemne vicemene vyrusi.

Popravde, samo o sobe mi to neprijde natolik nosne, aby to melo smysl zpracovavat do studii - mam dojem, ze verejnost obecne o carbon sinks ani nevi, tudiz nejspis nepredpoklada, ze by teplota mohla samovolne zacit opet klesat zpet.

Krom toho me zaujaly take casove horizonty, ktere autori uvazuji a ve kterych se zemske klima promenuje - desitky az stovky let. Z toho pohledu se ultimata do roku 2025 apod. jevi jako dost arbitrarni, byt samozrejme nechci zpochybnovat nutnost prijimat rychla a ucinna opatreni.

@ondraspribyla - pokud mas nejaky konkretni duvod, proc bys to prece jen chtel dat do studii, muzeme si samozrejme zavolat a prodiskutovat to dale. Jinak bych to zavrel a maximalne nahral clanek jako PDF s nejakymi zvyraznenymi castmi na GD. Nebo idealne pridal do nasi knowledge base :)

![image](https://user-images.githubusercontent.com/9573993/67717243-3d126500-f9c5-11e9-97d8-2d70d8dced30.png)

**Comment by ondraspribyla** [comment]
Přenesl jsem do WIKI, knowledge base. Líbí se mi ten obrázek, ale nevím jak ho přidat do wiki. Nevíš Tome? @protivinsky
Issue zaviram... (kdybys vymyslel jak obrazek dat do wiki bude to fajn, jinak to prostě necháme zazvřený.)

**Comment by mukrop** [comment]
@ondraspribyla Zatial mozes linkovat obrazok z issues, tj. https://user-images.githubusercontent.com/9573993/67717243-3d126500-f9c5-11e9-97d8-2d70d8dced30.png

Inak sam vaham – obrazky ktore nie su online by sa mozno dali vkladat do wiki gitu (wiki je samostatny git repozitar so vsetkym, co k nemu patri). To ked tak vyskusame a dohodneme sa osobne.
