### ISSUE TITLE
nedostupná podkladová data pro svět

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#261]
Toto nefunguje korektně:
![image](https://user-images.githubusercontent.com/5269350/67760382-82747800-fa41-11e9-9523-28c7c49c3067.png)

dysfunkční chování:
vyžadován Google login

**Comment by jankrcal** [comment]
Opraveno, díky za kontrolu!
(pokud by Ti to stale nefungovalo, otevri to prosim znovu)
