### ISSUE TITLE
Studie: How to mitigate climate change (IMF) 

### ISSUE THREAD

**Issue by protivinsky** [mukrop/faktaoklimatu#271]
Studie Mezinarodniho menoveho fondu porovnava ruzna opatreni na mitigaci. V zasade ukazuje, proc jsou uhlikova dan a emisni povolenky efektivnejsi nez jina opatreni.

https://www.imf.org/en/Publications/FM/Issues/2019/09/12/fiscal-monitor-october-2019

**Comment by protivinsky** [comment]
@ondraspribyla jeste jsem vcera zminoval prohlaseni ekonomu: https://www.econstatement.org/home

Je uzitecne o tom vedet, zaroven je to dost kratke a starsi (z roku 1997). Je to vyjadreni shody ekonomu, ze uhlikova dan je vyrazne lepsi prostredek nez regulace; zejmena pokud zachovava celkove danove zatizeni (revenue neutral).

**Comment by protivinsky** [comment]
@ondraspribyla nastrelil jsem velice predbezny text - https://docs.google.com/document/d/1lJf6WYEUmHDC2b-ElOC3BjRB7GrwZhAurx_G6ULQk_0/edit#
Chci si to jeste s odstupem procist a zeditovat (behem par dni), potom bych k tomu uvital dalsi pohled, at uz od tebe nebo od nekoho dalsiho.

Puvodne jsem chtel sepsat tu zpravu od Svetove banky, State and Trends of Carbon Pricing 2019 (#220). Nicmene tato od IMF mi prisla zajimavejsi v tom, ze jednotlive pristupy porovnava a ukazuje, proc je Carbon Pricing stezejni. Nevim, zdali je uzitecne tu Svetovou banku sepsat pozdeji take.

Zde je tabulka porovnavajici jednotlive nastroje - rad bych to tam aspon trochu zahrnul, ale nevim jak moc se to da zjednodusit aby to bylo porad smysluplne.
![image](https://user-images.githubusercontent.com/9573993/68544730-45ec3900-03be-11ea-9189-ac4692c43696.png)

Mimochodem maji i nejake infografiky:
![image](https://user-images.githubusercontent.com/9573993/68544751-716f2380-03be-11ea-87a6-1373baa9bd55.png)

**Comment by setcz** [comment]
@protivinsky Vím, že jsi psal, že chceš aby to někdo přečetl, až to zedituješ - ale byl jsem zvědavý a pročetl jsem to už teď. Přijde mi ten text zajímavý. 

Psal jsem tam nějaké (hlavně jazykové) komentáře přímo jako komentáře do dokumentu. Pár obecnějších myšlenek:

- přišlo by mi dobré si ujasnit, pro koho ten text je (případně pro koho web faktaoklimatu je). Teď mi přijde text psaný pro někoho, kdo prošel aspoň jedním semestrem ekonomie. Což není úplně vysoká laťka, ale podle mě i chytrého člověka, co si k ekonomii nečuchl, to trochu může odradit. 
- za sebe v článku nevidím a ocenil bych nějakou silnější argumentaci, proč je uhlíková daň nejlepší. Konkrétněji asi - nevím jakou váhu mají jednotlivé sloupce v tabulce. Nevím, proč tam jsou zrovna ty sloupce a ne nějaké jiné. (A možná to není kritika překladu, ale původního článku, ten jsem nečetl. A možná to vychází z nějakých "ekonomických dogmat", která neznám - třeba já nevím, proč je lepší tržní nástroj než netržní nástroj)
- a hlavní otázka, co mi vrtá po přečtení hlavou - jak velký odhadovaný dopad to teda bude mít, když se zavede třeba ta uhlíková daň? O kolik se sníží emise CO2?

**Comment by protivinsky** [comment]
@setcz diky, ja vas hlavne chtel usetrit ruznych preklepu a neobratnych formulaci. Nicmene ty obecnejsi myslenky bych pri editaci stejne nezmenil, takze diky za ne, jsou to rozhodne uzitecne postrehy.

Pokud vim web neni primarne cileny na verejnost, ale na novinare / opinion makery. Pro sirsi verejnost maximalne prostrednictvim ukazovani infografik nekde na stancich s dovysvetlenim. Podle toho k textum pristupuji (je to tak @ondraspribyla ?).

Coz stejne moc nemeni na tom, ze ani u novinaru nemuzu predpokladat semestr ekonomie. Zkusim to vice rozvest a dovysvetlit, pripadne pak nekterou z casti vyhodime, kdyby to bylo prilis dlouhe.

**Comment by lilyjoe19** [comment]
Ahojte,
výstup z dnešného klimatonu je plus mínus spomenutý v dokumente. Bola som dnes druhý second reader a moje komenty sú v texte. S @ondraspribyla sme sa bavili, že by to mohlo ísť čoskoro do sveta, je to spracované pekne :) @protivinsky, mrkni sa prosím na to niekedy

**Comment by protivinsky** [comment]
Diky za komentare @lilyjoe19 ! Postupne zapracuji.

- zalozil jsem samostatne issue pro preklad tabulky - a priradil jsem sebe. Myslim si ze bez precteni cele studie (a pripadne ekonomickeho zazemi) je dost tezke to rozumne prelozit.
- ekonomicke terminy - externality pridam do slovniku; fiskalni lepe vysvetlim a dale budu spis vynechavat nebo opisovat; feebates - porad nevim co s nimi, zamyslim se. Je to kombinace fees a rebates, neni to neco, co by se v ekonomii bezne pouzivalo. Mozna by to slo opisne jako "poplatky a prispevky". (Individualizovane poplatky nezahrnuje rebates - tzn. ze nekteri plati, jini naopak podporu dostavaji, aby to celkove bylo rozpoctove neutralni).

**Comment by ondraspribyla** [comment]
Re Feebates: za mě jsou **poplatky a příspěvky** docela dobrý překlad -
stejně ho bude potřeba dobře vysvětlit

Dne st 13. 11. 2019 22:48 uživatel Tomas Protivinsky <
notifications@github.com> napsal:

**Comment by lilyjoe19** [comment]
helou, 
zapracovala som novú nomenklatúru do textu. @protivinsky , skúsiš sa prosím ty pozrieť na technické veci typu vysvetlenie termínov? bez štúdie predpokladám, že ani infografika #285 nebude môcť ísť do sveta. netráp sa diakritikou, to môžem urobiť bez väčších problémov ja :)

**Comment by protivinsky** [comment]
s @lilyjoe19 jsme dnes studii zeditovali, zitra ji commitnu, az bude hotova grafika muzeme vytvorit PR a mergovat.

**Comment by protivinsky** [comment]
Pushnul jsem text do vetve. PR ceka na finalni verzi grafiky #285 

@mukrop je mozne u slovnikoveho hesla definovat, v jake podobe chci aby se zobrazilo v textu na strance? momentalne se zobrazi napriklad jako: "pro Mitigace klimatickych zmen", muzu to nejak nahradit aby se zobrazilo jako "mitigaci" ?
