### ISSUE TITLE
Téma: Data a kontexty pro emise z dopravy

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#28]
- Podíl letecké, automobilové a hromadné dopravy
- Emise na km
- doprava lidí vs doprava zboží
--- 
Kontext celkových emisí ve světě

**Comment by spacekpe** [comment]
Ad letecká doprava: komu ji započítat?

Naivní nápad: Emise za každý let rozdělit napůl a první polovinu započítat zemi odletu a druhou polovinu zemi příletu. Pokud jde o vnitrostátní let, tak země dostane obě poloviny.
Úvaha za tím je, že země z toho mají benefit a vzdálenost kterou letadlo uletí nad určitým územím není z ekonomického hlediska asi podstatná.

Určitě už to někoho napadlo, kde je háček? :-)

**Comment by ondraspribyla** [comment]
Ad letecka doprava: z dat ktera jsme měli ji můžeme snadno získat (jen vzít jiný řádek a trochu předělat součty) proto: **Leteckou dopravu máme v současné době započtenou**

Jinak by sice bylo hezké doplnit podrobnější data pro emise z dopravy,  (například z ročenky CENIA) ale v současné době to není priorita. Prtoo Issue nyní zzavírám. Když to bude důležité, (např příjdou dotazy od lidí) tak issue vytvoříme znovu a bude mít jasnější produkt než tohle. Tohle bylo zapsané spíš jako nápad.
