### ISSUE TITLE
přidat info o metodice k emisím GHG

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#283]
V emisích odkazujeme na data Eurostatu, který používá formát a strukturu dat CRF. Chceme přidat nějaké info o metodice sběru dat a jejich významu a kategoriích atp.

Podklady:

> CRF je common reporting format - což  není metodika, ale je dle metodiky IPCC formát dat a jejich struktura, ve kterých se vykazuje emisní inventura. Oficiální metodika emisí GHG se jmenuje "2006 IPCC Guidelines for National Greenhouse Gas Inventories"  - v textu většinou referováno jako 2006 Gl.  2006 Gl obsahuje metodiku jak se k jednotlivým zdrojovým kategoriím, tak jak je v CRF vykazovat. Veškerá metodika k výpočtům i k reportingu je na stránkách národního programu inventarizace emisí (NGGIP - national greenhouse gas inventory programme) https://www.ipcc-nggip.iges.or.jp/ a je závazná pro všechny státy UNFCCC. Platná metodika pro všechny kategorie kromě LULUCF je zde https://www.ipcc-nggip.iges.or.jp/public/2006gl/index.html, LULUCF má ještě rozšíření pro mokřady zde https://www.ipcc-nggip.iges.or.jp/public/wetlands/index.html. 
Eurostat stejně jako jiné mezinárodní organizace data přebírají buď z národních reportingů, nebo přímo z UNFCCC (Např. světová banka). Pro eurostat tato konkrétní data sbírá z členských zemí evropská environmentální agentura.  

(zdroj: e-mail od někoho z cenia.cz)

Issue založeno na základě žádosti @ondraspribyla

**Comment by crysman** [comment]
Návrh nové odrážky pro emisní infografiky:

> Emisní inventura poskytovaná Eurostatem využívá formát a strukturu dat _CRF_ (_common reporting format_), veškerá metodika k výpočtům a reportingu je na [stránkách národního programu inventarizace emisí](https://www.ipcc-nggip.iges.or.jp/) (NGGIP - national greenhouse gas inventory programme) a je závazná pro všechny [státy UNFCCC](https://cs.wikipedia.org/wiki/R%C3%A1mcov%C3%A1_%C3%BAmluva_OSN_o_zm%C4%9Bn%C4%9B_klimatu).

plus k tomu oprava:

> Data o emisích poskytují Eurostatu jednotlivé země EU – tedy data za Českou republiku reportovala přímo Česká republika.

změnit na:

> Data o emisích poskytují Eurostatu jednotlivé země EU – tedy data za Českou republiku reportovala přímo Česká republika, konkrétně skrze Evropskou agenturu pro životní prostředí.


Co vy na to? @ondraspribyla ?

**Comment by ondraspribyla** [comment]
closed via #297
