### ISSUE TITLE
Tabulka srovnavajici mitigacni opatreni (z IMF studie)

### ISSUE THREAD

**Issue by protivinsky** [mukrop/faktaoklimatu#285]
Chceme prelozit tabulku a udelat z ni samostatnou infografiku. Ze studie IMF, viz #271 

![image](https://user-images.githubusercontent.com/9573993/68806696-44d93700-065e-11ea-9da1-4e550db358c5.png)

**Comment by ondraspribyla** [comment]
Jestli máš čas na překlad tabulky tak je to za mě **top priority** - visi
na tom práce grafiku, a zrovna zítra mají vyhrazeny pracovní den. Dokážeš
nastrelit překlad do zítřka?

Dne st 13. 11. 2019 22:40 uživatel Tomas Protivinsky <
notifications@github.com> napsal:

**Comment by protivinsky** [comment]
https://docs.google.com/spreadsheets/d/12NkZyTKAofs6iIP1rsTI7sFGXJkNoJJQbxw6T0gWNRs/edit#gid=0

Preklad samotny neni prilis slozity, ale je potreba take vysvetlit, co jednotliva opatreni a kriteria (sloupce) znamenaji, pripadne jak jsou vyznamne. Nejsem si uplne jisty, jak zpusobem to zahrnout do infografiky - nebo to mozna nechame cele do pruvodniho textu pod infografikou?

Vysvetleni nekterych mene srozumitelnych sloupcu jsem pridal pod preklad, rovnez i popis jednotlivych opatreni (to jsem prekopiroval z textu o studii).

**Comment by lilyjoe19** [comment]
ja sa sem s dovolením přicmrdnem :)
pridala som do spreadsheetu nejaké pripomienky a vytvorila som svoju verziu na samostatnej karte (sheete), v ktorej som vyznačila úpravy (treba skontrolovať po technickej aj jazykovej stránke). 

myslím, že dať informácie pod tabuľkou do sprievodného textu je dobrý nápad, v podstate to kopíruje prevedenie ostatných infografík :)

**Comment by protivinsky** [comment]
diky - mnozstvi komentaru me donutilo najit v praci nejaky pocitac, ze ktereho se muzu prihlasit na GD :)
obecne souhlasim, nekolik pripadu jsem okomentoval. jedine, co je urcite potreba opravit je B17 na tvem liste, vysvetlil jsem v komentari jak je to mysleno (ta regulace a doprava). za ostatni opravy diky, za me je to takto ok.

**Comment by kikinna** [comment]
![Mitigace v1 0-01-01](https://user-images.githubusercontent.com/11555522/68866133-3fc6c700-06f4-11ea-82b6-02a2db5fc6f1.png)
Zatím první nástřel tabulky. Zatím jsem vzala texty od Lenky (se zeleným podbarvením). Počítám, že se budou kdyžtak dolaďovat. Taky bych potřebovala nadpis a podnadpis.

**Comment by lilyjoe19** [comment]
typos:
podnadpis: .. "je" C daň a emisné povolenky (myslím si, že má byť "jsou")
"patření" namiesto "opatření (4. stĺpec, nadpis)

zdroj - IMF je skratka International Monetary Fund, predpokladám, a ďalej píšeš Medzinárodný menový fond (-> MMF). nechceme to nejak zjednotiť (buď do EN alebo do češtiny), aby tam tie písmená boli konzistentné? to len taká blbosť na zamyslenie

mne sa to inak páči, čo na to @ondraspribyla ? :)

**Comment by ondraspribyla** [comment]
@kikinna  Za mě graficky dobrý. 
@protivinsky @lilyjoe19 zkuste doladit texty a můžeme to nasadit společně s výtahem ze studie IMF. Relativně low hanging fruit :-)

O.

**Comment by lilyjoe19** [comment]
Lenka hlási, že sa čoskoro na dlhú dobu poberie do offline sveta (asi tak po mesiaci idem konečne cvičiť, jej! :D) - vrátim sa buď cca 22.30 alebo až zajtra. 
@ondraspribyla , myslím, že v tejto fáze prípravy nám pomôže, keby si si prečítal naše komentáre v spreadsheete (hlavne B17 a F17) a povedal, čo si myslíš (či je to rozumne zrozumiteľné a zároveň to vyjadruje to, čo chcel Tom ako človek z odboru napísať, resp čo v komentári vysvetľuje)

dnes v práci izolujeme z medu nejaký proteín, tak sa nemôžem toľko Faktom venovať :( ;)

**Comment by protivinsky** [comment]
Nahled vypada dobre, diky!

- udelal jsem par zmen do tabulky v Lencine listu, konkretne bunky: B17, F14, F16, F17, H16 - za me to takto muze byt finalni
- souhlas s Lencinymi typos vyse, to opravit a vyhodit IMF; (Mezinarodni menovy fond jako zdroj staci)
- zvazuji, zdali by nebylo srozumitelnejsi, kdybych do tabulky zaznacili, ktere charakteristiky jsou dobre a ktere spatne. Napriklad zeleny / cerveny podkres, nebo zelena fajfka vs cerveny krizek? U vetsiny sloupce je to asi intuitivne jasne, ale bylo by to rychleji citelne a tusim ze ani Set si u trzniho mechanismu nebyl uplne jisty. Pokud to chceme a lze to nejak graficky hezky udelat, mohu to zaznacit do zdrojove tabulky - pravdepodobne budou potreba tri urovne, pozitivni, negativni a neco uprostred (neutralni).

**Comment by lilyjoe19** [comment]
@protivinsky , aby sme to mohli pustiť do sveta, je ešte potrebné doklepať ten sprievodný text. budeš mať čas sa na to mrknúť v najbližších dňoch?
písmenká kopírovať nemusíš, to môžem urobiť ja. presne viem, ako sa cítiš, bola som v UK na Erazme a ľudia ľahko vedeli, či som na univerzite alebo doma podľa toho, ako som používala diakritiku :)

(tá info o mede bola pre Ondráša - mám teraz mesiac novú prácu a zvyčajne sa tam strašne nudím, lebo na mňa nikto nemá čas/objektívne nie je veľmi čo robiť (štátna sféra ;)), tak som včera na klimatone vravela, že vďaka novej práci aspoň môžem viac pracovať na Faktoch :D)

**Comment by kikinna** [comment]
Díky za připomínky)) Nadpis, podnadpis a patička byla z mé strany rychle plácnutá jen jako dokres šablony, tudíž typos a chyby. Obecně to v počátečních fázích neřeším neb se texty dolaďují na závěr (to, abyste se i u příštích work-in-progress infografik moc nedivili za množství nedotažeností))

@protivinsky Co se týče tří úrovní zaznačení, co je dobrý a co zlý, tak to je dost zajímavý. Myslím, že by stálo za to to lidem ukázat (předává to přeci jen další hodnotnou informaci), jen mi to určitě trochu graficky zkomplikuje, haha)) Ale určitě to zkusme.

**Comment by protivinsky** [comment]
@kikinna doplnil jsem do te finalni Lenciny tabulky barevne znaceni vystihujici pozitivni, negativni ci neutralni. Pokud to ale bude vypadat divne, neni to nutne. Ono je obcas stejne trochu nejasne, jak velke ty rozdily skutecne jsou, pripadne jaka je dulezitost jednotlivych sloupcu. V nekterych pripadech to znaceni je trochu muj subjektivni dojem.

@lilyjoe19 zkusim se na pruvodni text podivat zitra. Pokud to nezvladnu, budu mit pripadne cas az po vikendu. Take jsem upravil bunky E14 / E15, viz komentar u E14.

**Comment by protivinsky** [comment]
Navrh pruvodniho textu k infografice / tabulce:

https://docs.google.com/document/d/17FLiNkY4xC0bqK5UG5xbCdHyAwB2i9tnO6ahro1AcmQ/edit#

**Comment by kikinna** [comment]
@protivinsky Tome, díky moc za práci a rozdělení na tři kategorie. Trošku se bojím, že ty kategorie nebudou tak snadné zahrnout, ale zkusím to, jen se k tomu dostanu bohužel až v druhé polovině týdne. 
Je super, že jsi udělal ten průvodní text k infografice. :) Napadlo mě, jestli by jsi nechtěl vymyslet i přímo název a podnadpis v infografice. )) Já bych to tam pak hodila dohromady s návrhy na kategorizaci a vykopla nějakou prefinal verzi na testování?

**Comment by kikinna** [comment]
![Mitigace v1 0 300-02](https://user-images.githubusercontent.com/11555522/69381911-1ee31080-0cb6-11ea-9cd1-da59ad7eadc7.png)
@protivinsky @ondraspribyla Tak po všemožných testováních jsem skončila u jediné varianty, která za mě funguje pro kategorizaci. 
Původně jsem čekala, že kategorizaci možná odmítnu (že bude čistší varianta bez kategorizace), ale ve výsledku mi přijde, že to krásně vizuálně podporuje tvrzení, že uhlíková daň a emisní povolenky mají více výhod a jsou tedy efektivnější (správná úvaha?) a zároveň to pomáhá se v té tabulce orientovat → koukat za pozitivními / negativními aspekty (např. co je hlavní pozitivní stránka regulace a že zbytek u ní je negativní).

Teď je otázka na vás, jestli si teda za tady tou kategorizací stojíte a zda-li vám (po abstrahování od vizuálních detailů—je to stále jen draft) přijde tato vizualizace fajn?

**Comment by protivinsky** [comment]
@kikinna diky za draft, vypada to dobre! Za me kategorizace takto funguje - trochu premyslim, jestli ty rozdily mezi odstiny nejsou prilis male, klidne bych je o kousek zvyraznil. Ale pokud jsi to zkousela a uz se ti to nelibilo, beru i tuto verzi.

Jeste par komentaru, co mi padlo do oka (nektere souvisi s pozdejsimi zmenami ve zdrojove tabulce (tj A13 az H18 na listu Lenka v https://docs.google.com/spreadsheets/d/12NkZyTKAofs6iIP1rsTI7sFGXJkNoJJQbxw6T0gWNRs/edit#gid=303433420) - chapu, ze je to stale draft, ale abychom to tu meli pohromade a nezapomneli na to:
- vyhodit zavorku v prvni sloupci u regulaci (tu o doprave)
- naopak pridat zavorku pro uhlikovou dan a emisni povolenky do dopadu na ceny energii
- uhlikova dan, dopad na ceny energii - typo: politcke, chybi i
- uplne vpravo dole - "monitorovani" bych rozdelil spis po slabikach
- vyhodit "IMF" ze zdroje dat

**Comment by kikinna** [comment]
@protivinsky Super, děkuji )) 
Ano, máš pravdu, odstíny mezi barvami jsou ještě příliš malé. Trochu je udělám výraznější, ale nechci o moc (aby to nebylo úplně lego). 

Díky, že jsi sepsal ještě všechny připomínky (ano, ještě jsem to neřešila, ale je hodně nápomocné to mít na hromádce). 
Co se týče nadpisu, tak se nám tam krásné vlézá i ten delší. Spíš je otázka, jestli chceme použít ten termín Mitigační opatření (který jsem třeba já před prací na faktaoklimatu neznala). Pokud ano, tak by nejspíš stálo za to ho jště někde v infografice vysvětlit. Třeba dát první větičku podnadpisu říkající, že mitigační opatření jsou opatření pro zmírnění klimatické změny a že MMF ukazuje, že ty dvě jsou efektivní. 
Co myslíš?

**Comment by lilyjoe19** [comment]
ahojte,
ja ešte dodávam, že je v novšej verzii zachovaná aj táto issue, ktorú už som spomínala vyššie: 
> "patření" namiesto "opatření (4. stĺpec, nadpis)

mne "Mitigačné opatrenia" nevadia - ak je našim publikom zľahka odborná verejnosť, nemal by to byť zásadný problém a v kombinácii s nejakým po(dnad)piskom, ako @kikinna navrhuje, je to imho dobré riešenie 

a ešte @protivinsky - pozerám teraz na sprievodný text k tej infografike. je fajn mať tam popis k jednotlivým riadkom/stĺpcom. možno by som zachovala vyššiu deskriptivitu viď zdrojové dáta (B21 a 22, resp 37 a 38), lebo to si vedia neexperti ľahšie predstaviť. je to taký učebnicový spôsob písania, by som povedala :) pri riešení štúdie na klimatone sme sa zhodli s Ondrášom, že príklady apod nie sú vôbec na škodu.
ak sa pozrieš na ostatné infografiky, býva to viac ~interpretácia, resp doplnenie infografiky, niečo na štýl Doplňující komentáře. určite je dobré zachovať vysvetlenie nástrojov/kritérií, no nedali by sa pridať nejaké kľúčové výstupy a podobne, čo myslíš? ak si čítal tú MMF štúdiu celú, určite máš predstavu, čo ťa najviac zaujalo a aká je take home message

**Comment by kikinna** [comment]
![Mitigace v1 0-04-04-04-04-04-04](https://user-images.githubusercontent.com/11555522/69454620-e2bbb880-0d66-11ea-9b2f-234c90b81e8c.png)
@protivinsky @lilyjoe19 Mohla bych vás pěkně poprosit o kontrolu, jestli jsem spravila vše, co bylo třeba? Teď mám na mysli hlavně texty
Zároveň, mohla bych vás prosím poprosit o pomoc pro dovymyšlení legendy? Zatím tam mám jen klíčová slova "pozitivní / neutrální / negativní", ale přijde mi, že by chtělo doplnit, o co se jedná—pozitivní "co?". To se mi nedaří pořád vymyslet ))) 

@protivinsky Tome, ty barvy jsem trochu změnila, ale ve výsledku ne tak moc. Máš stále pocit, že to je málo odlišné? (Mým cílem nebylo je výrazně odlišit, ale dostatečně, if that makes sense. Nechtěla bych tomu vizuálně dát příliš velkou váhu, aby to nerozbilo tabulku)

**Comment by protivinsky** [comment]
@kikinna diky za opravy i za zmenu barev - libi se mi to, texty jsou v poradku. legenda: takto mi to nevadi, vlastni mi to prislo v pohode. Pripadne muzeme pouzit neco vice popisneho, napriklad "Účinnost opatření: vysoká / střední / nízká"

@lilyjoe19 ja se predtim snazil ten popis zkratit, aby to uz nebylo prilis dlouhe. Pokud vam to prijde vice vysvetlene lepsi, jsem pro. 

Klicove vystupy apod - za me je hlavni vystup infografiky prave to, ktera opatreni jsou nejucinnejsi. Samotna IMF zprava zahrnuje i dalsi oblasti a zavery, nicmene ty bych spis zduraznil v samostatnem textu shrnujicim studii #271 - a zde u tabulky bych pouze odkazal na ten druhy text. Aby obe stranky nebyly v zasade totozne. (Dalsi moznosti by bylo oba texty sloucit uplne a mit jeden vystup namisto dvou; osobne mi to ale dava vetsi smysl oddelene.)

**Comment by ondraspribyla** [comment]
Finisujeme - v branchi je nachystaný .md soubor na studii, tabulku a nová sekce "Adaptační a mitigační opatření

Prosím o 

- [ ] PDF tabulky

- [ ] Kontrolu textů studie

- [ ] Doplnění obrázku studie

**Comment by kikinna** [comment]
![Mitigace v1 0 colors-08](https://user-images.githubusercontent.com/11555522/69501895-a8d6e780-0f09-11ea-834c-1025b2fbf796.png)
Ahojte @ondraspribyla @protivinsky @lilyjoe19 )) Mám chuť se omlouvát za komplikovaní práce. Současně mi to přijde důležitý to řešit, aby ta tabulka byla opravdu příjemně čitelná a dobře se v ní orientovalo.
Po konzultacích s dalšími pár lidmi jsem přišla ještě s novým updatem. Ráda bych vás poprosila, jestli byste na to nekoukli. 

O co se jedná:
* změnila jsem barevné schéma (to je nejvíc viditelný) - tak, aby žádná barva neměla vizuálně větší důležitost (což u původní verze bylo). Zároveň je jasný zařazení dobrý / zlý. 

* po konzultaci s dalšími lidmi je legenda opravdu nejasná, tak jsem se chtěla zeptat, jestli se tam nedá hodit nějaká taková "lidská" větička, která dopomůže rychle pochopit, o co jde (raději než nutně domýšlet věci tam budou řečený explicitně) -> máte k tomu prosím nějaký návrh, lepší větu? (Zatím jsem prototypově hodilo "O jakou vlastnost se jedná?" -> pozitivní / neutrální / negativní 

* další věc, od které jsem se trochu odprositla v průběhu vizuálního návrhu, ale teď mi vyvstává víc a víc (a taky mi byla potvrzena dalšími lidmi), je občas nešikovnost nadpisů sloupečků. Nedalo by se to přepsat trošičku do lidštějšího jazyka, prosím? Cílem je hlavně, aby to čtení tabulky plynulo - tím myslím například to, že se člověk podívá na sloupeček a přečte si "Jedná se o tržní mechanismus?" -> "Ano". Nebo třeba "Jaká je administrativní zátěž?" -> "Dodatečná ( _kvůli_ monitorování emisí a obchodního systému). Myslím, že by to mohlo opravdu pomoct příjemnějšímu zpracovávání tabulky. Byli byste pro? 
Jinak já konkrétně mám třeba největší problém s představou o co se jedná/kostrbatostí u nadpisů tržní mechanismus, převedení opatření v praxi, přijatelnost dopadu na ceny energie (tady obzvlášť, že ta odpověď imho nenavazuje plynule na otázku "přijatelnost", ale spíš "jaký to má dopad na ceny energie")

**Comment by protivinsky** [comment]
@kikinna diky za dalsi navrh - alespon strucne za me:
- zmena barevneho schematu se mi libi! osobne mi trochu prijde, ze ta "neutralni" je vizualne vyrazne blizsi "pozitivni" nez "negativni". nedala by se vybrat nejaka barva, co vypada vice "uprostred"?
- veticka k legende - jsem pro. bud to co navrhujes, nebo se pripadne da pouzit i "Ucinnost opatreni: vysoka / stredni / nizka". ony sice nektere ty vlastnosti nejsou primo o ucinnosti, ale my stejne na zaklade souhrnneho porovnani tvrdime, ze dan a povolenky jsou nejucinnejsi, tak mi to zjednoduseni prijde ok.
- dovysvetleni "mitigacnich opatreni" za nadpisem - osobne se mi libil vice ten predchozi zpusob, vysvetleni a sipka k tem jednotlivym opatrenim.
- nadpisy sloupcu - souhlasim, ze se to momentalne necte uplne snadno. popravde, tabulka se podle me neda prilis pochopit bez doplnujiciho textu (ktery vysvetluje, co je trzni mechanismus, prevod opatreni v praxi a proc je to pozitivni nebo negativni) - nebo v idealnim pripade vysvetlujiciho komentare pri prezentaci infografiky nekde v diskuzi nebo na stanku. pro lidi bez ekonomickeho vzdelani je to pomerne slozita problematika a nemyslim si, ze to lze zjednodusit, aby to bylo skutecne snadno ctive a navodne. zaroven web neni zamereny na obecnou verejnost, ale na novinare / politiky / vzdelanejsi lidi se zajmem o problematiku. ponechal bych nadpisy takto - nemyslim si, ze bychom dokazali prepsat do otazek vsechny a nekonzistence ve stylu by mi tam vadila vic.

**Comment by lilyjoe19** [comment]
@protivinsky , prosím ťa, mohol by si sa pozrieť ešte na komentár k F13 v spreadsheete (https://docs.google.com/spreadsheets/d/12NkZyTKAofs6iIP1rsTI7sFGXJkNoJJQbxw6T0gWNRs/edit?disco=AAAAD8Um4lg)?
ak sa toto vyrieši, za mňa bude infografika tiež ok. súhlasím, že tabuľka a štúdia sú lepšie samostatne

@kikinna , 
grafika - ja som si teraz bez pozrenia legendy vyložila odtiene sivej naopak, ako sú myslené (tmavosivá mi príde bližšie k čiernej, tj horšia ako svetlosivá). tá červená mi príde veľmi agresívna, teraz je tá tabuľka urobená "v negatívnom režime" - nie je zvýraznené to, čo je pozitívne, tj C daň a povolenky, ale človeku do očí udrú hneď regulácie. ale ja sa v grafickom dizajne vôbec nevyznám :)

obaja:
popis stĺpcov - súhlasím s Tomom. očakáva sa, že si človek prečíta vysvetlenie popiskov pod tabuľkou. otázka tiež je, ako veľmi sa chceme držať MMF verzie - súčasná verzia je pomerne presným prekladom a nie som si istá, či je dobrý nápad zásadne sa líšiť od citovaného zdroja.
legenda - neviem sa veľmi vyjadriť, lebo tomu rozdeleniu poriadne nerozumiem. ja ako človek mimo odbor to "pozitívne/negatívne" chápem ako "V prospech/neprospech zavedenia opatrenia". nemyslím si, @protivinsky , že to, čo ty navrhuješ, je úplne presné... nemôže to byť Účinnosť _opatrenia_, pretože to by potom nemohli byť označené jednotlivé stĺpce, ale celý riadok

**Comment by protivinsky** [comment]
diky, s komentarem F13 souhlasim - @kikinna prosime tedy o zmenu nadpisu sesteho sloupce "Předvídatelnost cen".
jinak ta tmavosiva je modra :) ktera je za me ok pro pozitivni vlastnosti. 
popis legendy souhlas, tak to nechme jak je to ted navrzene.
"vysvetleni mitigacniho opatreni" je drobnost, je mi v zasade jedno, kterou verzi zvolime.

**Comment by protivinsky** [comment]
pushnul jsem do vetve obrazek studie + placeholder grafiky + doplnil jsem ruzne metainformace a odkazy. s finalni verzi grafiky muzeme delat PR.

**Comment by kikinna** [comment]
Ahojte) Děkuji vám moc za podněty)) 
@protivinsky Děkuji za tvůj vjem barev. Upravila jsem teda ještě trošku barvy, tak snad je to lepší) taky jsem dala na tebe s tím dovysvětlením, co znamená mitigační opatřeí (taky se mi to tam nelíbilo, ale trochu jsem bojovala, kde to prostě bude dobrý). 

Ad nadpisy, asi jsem se nevyjádřila dobře. Nešlo mi o to je vysvětlit tak, aby i člověk, který této oblasti nerozumí, tak pochopil o co se jedná (tedy nešlo o dovysvětlení obsahu) -- to by bylo nereálné :D. Ale chtěla jsem pouze pomoci čitelnosti co se týče plynutí textu/informací. Posílám ukázku toho, co jsem myslela (až na "příjem do rozpočtu" jsem ty otázky snad trefila správně). Teď v tom vnímám jasnější návaznost informací na otázku, tak se mi ty informace vstřebávají jasněji. 
Co si o tom myslíte? Zkuste si na to prosím kouknout. @protivinsky @lilyjoe19 @ondraspribyla 
![Mitigace v1 0-02](https://user-images.githubusercontent.com/11555522/69796348-292d6f00-11ce-11ea-8403-c4e7aa07e41f.png)

Jinak by to za mě mohlo být snad vše?

**Comment by lilyjoe19** [comment]
ahojte,
@kikinna , ja som pochopila, čo si chcela povedať ohľadom tých "nadpisov". takto je to urobené pekne, keď je zvýraznená tá podstatná časť, no ja som priaznivcom jazykovej úspornosti a čím menej textu, tým sú pre mňa veci zrozumiteľnejšie :) 

* prevedenie do praxe - príde mi, že lepšie je sa pýtať "ako". tj "Jak se opatření přejeví v praxi?", prípadne "Jak se opatření převede do praxe?"
* prijateľnosť dopadu na ceny - v súčasnej forme odpoveď na otázku je mierne off topic. ak by sme to takto chceli zachovať, navrhujem prepísať bunky na
a) nižší - vyšší ceny mohou vést k nižší spoločenské a politické přijatelnosti
b) dobrá - nižší nárůst cen ...
alebo druhé riešenie je preformulovať otázku - "Je dopad opatření na ceny energie přijatelný?"
osobne som skôr za druhé riešenie - jazyková úspornosť ;)

* príjem do rozpočtu by som dala ako "generuje opatření příjem do (státního) rozpočtu?" možno Tom príde s niečím trefnejším
* predvídateľnosť cien - asi by som použila skôr "budou"
* administratívna záťaž - navrhujem "jaká vznikne" adm. z.

prosím o jazykovú kontrolu, ja po česky neviem :D
a za nepochopenie modrej farby sa ospravedlňujem, pri najnižšom jase a po celom dni som si fakt myslela, že to sú Two Shades of Gray ;) :D

**Comment by protivinsky** [comment]
@kikinna - diky moc za dalsi verzi a za barevne upravy. tvemu navrhu ohledne zahlavi sloupcu rozumim, ale radeji bych ponechal puvodni strucnejsi verzi. asi to vnimam podobne jako @lilyjoe19 , ze vice textu me spise rozptyluje. zmenis to prosim zpatky?

tim bych povazoval tabulku za dotazenou a muzeme to pak mergnout a uzavrit :)

**Comment by protivinsky** [comment]
a po dnesnich dodatecnych upravach jsem commitnul finalni verzi infografiky a rovnou mergnul. diky za spolupraci, zde mame hotovo!
