### ISSUE TITLE
Otestovat info mail

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#29]
Honzo, mohol by si prosim skusit poslat email na info@faktaoklimatu.cz?
Nechcem to robit ja ani o to ziadat nikoho z jadra timu, pretoze tie emaily chodia na skupinu a Gmail je vacsinou velmi proaktivny vo filtrovani mailov, ktore si si poslal sam. Tak nech to mame otestovane takto.

**Comment by repli2dev** [comment]
Sent.

**Comment by mukrop** [comment]
Funguje, dik.
@ondraspribyla dostal si testovaci email tiez?

**Comment by ondraspribyla** [comment]
Ano dostal. Funguje.

Dne pá 12. 7. 2019 12:48 uživatel Martin Ukrop <notifications@github.com>
napsal:
