### ISSUE TITLE
Grafika: Uhelná komise

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#292]
relevantní k současnému dění. SLOZENI KOMISE. CINNOST KOMISE 
 https://www.respekt.cz/spolecnost/komisi-pro-utlum-uhli-budou-hlidat-tezebni-bossove-i-jeden-miliardar

mozna kontaktovat hnuti duha - kozeluh, karnikova

**Comment by ondraspribyla** [comment]
http://www.zelenykruh.cz/na-cem-pracujeme/uhelna-komise

**Comment by kikinna** [comment]
@ondraspribyla Nechceš mergnout issue s #318 ? Ať v tom není nepořádek?

**Comment by ondraspribyla** [comment]
Closed via #318
