### ISSUE TITLE
Revize textů u tlačítek

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#31]
Vedla tlacitok infografiky (stazeni, data, licence) som pridal kratke sprievodne texty (do velkej miery z estetickych dovodov).

@ondraspribyla Prosim pozri sa na ne a uprav (obsah, cestinu). Najdes ich v _layouts/infographic.html.

**Comment by ondraspribyla** [comment]
Na první pohled se mi texty líbí... Korekturu češtiny a detailů jsem zaím nedělal...

**Comment by mukrop** [comment]
Tak ich asi zatial nechajme tak.
