### ISSUE TITLE
Opravy k studii MMF

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#313]
@protivinsky: Prosim nerob merge, ovzvlast velkych zmien bez aspon kratkeho odsuhlasenia odo mna (obzvlast, ked som oznaceny na review a este som ho nedal).

Tyka sa #302. Chcel som sa k tomu dostat az v priebehu tyzdna, ale ked uz je to vonku, tak to holt prejdem teraz, nez pojdem spat. Co boli rychle veci, to som opravil obratom v #312 (typografia, konvencie suborov, pridany rerirect).

Zasadnejsie veci (prosim o vyjadrenie @protivinsky, @ondraspribyla ):

* [x] Aktualne tam nie su ziadne nase podkladove data. Tj. tlacitko po kliku neurobi nic. Naozaj tam nic nemame a nechceme mat? Po potvrdeni mozem prerobit tak, aby sa nezobrazovalo (ale bude to chciet asi aj reformulaciu textu, zatial sme vzdy predpokladali, ze nase data budu).
* [x] Aktualne sa na titulnej strane v sekcii "Adaptační a mitigační opatření" zobrazuje jedna infografuika a jedna studia. Naozaj to takto chceme? Ja by som studie nechal bokom. (Bol to z vasj strany zamer alebo omyl?)
* [x] Aktualny slug stranky je "mitigacni-opatreni". Je to v ramci sekcie "opatreni" vhodny identifikator? Prakticky to znamena, ze v buducnosti inu infografiku, ktora bude len "mitigacni-opatreni" mat nebudeme. Davam na zvazenie (ako alternativy mi napadaju "opatreni-imf" alebo nieco take). Toto celkom ponahla, ovplyvnuje to link, ktory ludia zdielaju.
* [x] Zoznam suvisiacich infografik na spodu stranky je aktualne prazdny. Chceme ho odstranit, alebo pridat nejaku z existujucich infografik?

**Comment by protivinsky** [comment]
Ok, omlouvam se za merge, mohl jsi to samozrejme klidne revertnout - nedoslo mi, ze chces jeste udelat finalni review (a chapal jsem seznam reviewers jako "kdokoli"). A diky za opravy a dobre postrehy:

- podkladova data zde nejsou relevantni (dulezity je ten odkaz na Zpravu MMF, ktery mame). Nevim, jak snadno upravitelny je ten pravy sloupec, idealni by zde bylo nahradit sekci "Podkladova data" napriklad "Zdroj" a odkaz na zpravu MMF, pripadne s textem "Infografika je přeložena ze zahraničního zdroje." nebo neco obdobneho (muze se tykat i dalsich grafik).

- studie a infografika dohromady v sekci "Adaptační a mitigační opatření" mi take prisly zvlastni, ale predpokladal jsem, ze to tak @ondraspribyla chtel (navazal jsem na jeho commit), pripadne jste se na tom dohodnuli. Osobne bych studii z teto sekce vynechal.

- slug - momentalne se v odkazu sekce nezobrazuje, link tedy je https://faktaoklimatu.cz/infografiky/mitigacni-opatreni a jako takovy mi prijde dobry. Souhlasim, ze v ramci sekce je to velmi obecne, takze klidne muze byt i opatreni-mmf (ackoli pravdepodobne dalsi takto obecnou infografiku o mitigacnich opatrenich mit nebudeme, ale tezko predvidat).

- "souvisejici infografiky" bych prozatim odstranil (a vratil je zpatky pozdeji az budeme mit neco ke Carbon Pricing).

Diky a jeste jednou se omlouvam ze jsem ti pridelal takto nahlou praci!

**Comment by ondraspribyla** [comment]
- Naše podkladová data buď nejsou třeba, nebo jen zkopírujeme texty z tabulky.

- Studie je v sekci nedopatřením - když jsem studii TAGoval, dal jsem jí tag "opatreni" - porotže to dává smysl - ale ona se pak zobraila i mezi grafikami. Asi s tagovaním počkáme na  vyheldávání.

- Slug: preferoval bych mitigacni-opatreni-mmf , časem pravděpodobně budeme další mitigační opatření dělat. 

- Souvisejicí infografiky... grafiky, které jsou primárně opatření momentálně nemáme, tedy atím asi vyhodit. 

O.

**Comment by mukrop** [comment]
Upravil som slug po dohode s Ondrasom na "mitigacni-opatreni-mmf", vyhodil studiu zo sekcie a skrypt suvisiace infografiky v pripade, ze neexistuju. Zostavaju vyssie uvedene podkladove data (dohodli sme sa, ze pre konzistentnost tam dame kopiu nasich, urobi @ondraspribyla a napise tam, ze sa jedna iba o preklad). Okrem toho este:
* [ ] Upravit slug v infografike na 'mitigacni-opatreni-mmf' @kikinna

**Comment by mukrop** [comment]
Hotovo.
