### ISSUE TITLE
životnosť odkazov

### ISSUE THREAD

**Issue by lilyjoe19** [mukrop/faktaoklimatu#314]
ahoj,
vyskytol sa problém so zdrojmi - niektoré stránky/dokumenty, na ktoré odkazujeme v sprievodných textoch, už nie sú platné (viď https://github.com/mukrop/faktaoklimatu/pull/303#issuecomment-559827637)
túto situáciu treba riešiť - nejaké nápady?

neviem, či to je prevediteľné, čo sa technickej stránky týka, no jednou z ciest by bolo v čase citovania vytvoriť kópiu danej stránky/dokumentu, niekam to zavesiť (GDrive) a v texte spomenúť "zdroj (citované DD.MM.RRRR)"

**Comment by ondraspribyla** [comment]
Nerozumím, proč issue otevřeš a pak bez poznámky, že je někde jinde vyřešeno ho zavíráš...? 
Jestli už je nerelevantní, nebo je řešeno jinde, napiš sem prosím před zavřením pozznámku.

**Comment by mukrop** [comment]
Podla mna je aktualne riesenie dostatocne. Kopirujem casti svojho komentara z https://github.com/mukrop/faktaoklimatu/pull/303#issuecomment-560311686

> Kopie uz navrhoval crysman – ale podla mna to nie je dobry napad. Izolujes tym stav konkretneho momentu, nedavas moznost precitat si nove (mozno aktualnejsie) informacie na tych weboch. Sila internetu je prave v tom, ze linkuje (a aktualizuje).
> 
> Ad archivovanie: Archivujeme PDF vsetkych studii, ktore odkazujeme a originalne data tiez (vynimka je ta Parizska dohoda na webe MZP, tak tiez mala byt archivovana a omylom nebola).

**Comment by ondraspribyla** [comment]
Souhlas s @mukrop . Nechechavam tedy na @lilyjoe19 , aby si issue bud uzavrela s tím, že takto je vyřešené, nebo ponechala, s tím, že ho chce dál řešit. (můj první protest byl proti zavírání issue bez komentáře, podle mě je to vyřešené, ale nechci zavírat issue, které otevřel nekdo jiný)

**Comment by lilyjoe19** [comment]
pardon, to vzniklo neznalosťou vašich zaužívaných praktík. ako som potom v PR zmienila, pripojila som problém ku Crysmanovej issue #278, preto som potom túto issue zatvorila (aby neboli duplicitné)
