### ISSUE TITLE
FAQ často kladené dotazy (nejen) z pouliční akademie

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#325]
Na pouličních akademiích se opakují dotazy, a často jsou to dobré dotazy - když je mají lidi na poulakademii, budou je pravděpodobně mít i další.

Založil jsem interní [Gtabulku](https://docs.google.com/spreadsheets/d/1O07Cmru9hoJVaZt9DXQexd-rhjvk5mSTC7CFO67U1Bk/edit#gid=0) (klíčové slovo "FAQ"), kde to budeme shromažďovat. Co s tím dále se uvidí, za mě mi přijde zajímavé to po sebrání a učesání zveřejnit, protože to nabízí odpovědi na časté otázky, a protože to tím pádem je užitečné i pro novináře.

**Comment by Keramadohal** [comment]
Super, to se určitě hodí :-) Doplnil jsem ti odkaz přímo na tu tabulku ;-)

**Comment by crysman** [comment]
> Super, to se určitě hodí :-) Doplnil jsem ti odkaz přímo na tu tabulku ;-)

tak už jen doplnit tu tabulku jako takovou ;)

**Comment by ondraspribyla** [comment]
Odkazy na důležité dokumenty na GDRivu jsem hodil na WIKI. Tohle nemá smysl držet jako issue. Zavíám.
