### ISSUE TITLE
Lightbox na infografiku

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#4]
Na stranke infografiky by sa po rozkliku na obrazok mal otvorit lightbox.

**Comment by mukrop** [comment]
Rozchodit preklikavanie vpravo/vlavo medzi grafikami.

**Comment by mukrop** [comment]
Asi je to aktualne v pohode tak, ako to je. Infografiku po rozkliku ludia chcu priblizovat, lightbox by to mohol komplikovat.

**Comment by repli2dev** [comment]
@mukrop souhlas, je to opruz vybrat takový, který funguje dobře na PC i na mobilech a tabletech... typicky ty obrázky pak někam odskakují a lidé na ty obrázky nakonec rezignují.
