### ISSUE TITLE
Vývoj teplot: +2 °C za 50 nebo 60 let?

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#40]
Hlavní stránka říká "Nicméně v České republice za posledních 50 let vzrostla už o 2°C."

Infografika https://faktaoklimatu.cz/infographics/teploty-1/ ale říká něco jiného: "Průměrná roční teplota v České republice narostla za posledních 60 let o 2°C."

**Comment by ondraspribyla** [comment]
Opraveno na 60let.
