### ISSUE TITLE
Záhadný překlep: Chcete vědět, jaké jsou konktétní čísla?

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#41]
Nevím, kde se ten text bere (grepem jsem ho v repu nenašel...), nicméně:
"Chcete vědět, **jaké** jsou konktétní čísla?" je podle mě špatně, mělo by tam být "Chcete vědět, **jaká** jsou konktétní čísla?".

Ještě lepší by ale bylo přeformulovat to na:
Chcete vidět konkrétní čísla? Stáhněte si náš zpracovaný dataset, nebo ten původní, ze kterého vycházíme.

**Comment by mukrop** [comment]
Dik za navrh, preformuloval som to, ako si navrhol.
(Je to spolocny text, takze je v _layouts/infographic.html.)
