### ISSUE TITLE
doplnit podporu: sníh a doplňování vod

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#42]
Na první ani druhé čtení se mi nezdá neprůstřelné tvrzení z https://faktaoklimatu.cz/infographics/teploty-3/:

> Vyšší teploty v zimních měsících způsobují méně sněhu a v důsledku také slabší doplňování spodních vod.

Rychlé googlení mi dalo článek
https://www.vtei.cz/2015/08/hydrologicke-sucho-v-podzemnich-vodach/
a ten explicitně zmiňuje, že doplňování zásob vody sněhovou pokrývkou není jediný možný způsob - zmiňuje i srážky v létě atd.

Asi by se to dalo přeformulovat, např.:
Vyšší teploty v způsobují zvýšený odpar a tím zhoršují sucho, protože odpařená voda se nedostane do podzemí [link https://www.vtei.cz/2015/08/hydrologicke-sucho-v-podzemnich-vodach/ nebo jinam]. Vyšší teploty v letních měsících se také projevují jako vlny veder a nárůstem počtu tropických dní (tedy dní, kdy ani v noci teplota neklesne pod 20°C).

**Comment by ondraspribyla** [comment]
Pridal jsem link na clanek "hydrologicke sucho". Rozdelil zvýšení teplot v zime a v lete (prehlednost).
K doplnovani spodnich vod: destové srazky, zvlášt ty intenzivní spíše stečou po povrchu. Pomalu tající sníh se lépe vsakuje. (soukromá konverzace s hydroložkou ČHMU) - - nicméně tvrzení jsem zeslabil... takže v této podobě se za text můžu postavit.
