### ISSUE TITLE
Čárky na hlavní stránce

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#43]
Někdo, kdo umí česky, by měl ověřit psaní čárek na hlavní stránce. Sám si nejsem jistý, ale ...

Současný text
> Skleníkové plyny se dostávají do atmosféry spalováním fosilních paliv, a dalšími procesy jako například produkce cementu, pěstováním rýže a chov dobytka.

se mi nezdá. Nemá to být
> Skleníkové plyny se dostávají do atmosféry spalováním fosilních paliv a dalšími procesy, jako například produkce cementu, pěstováním rýže a chov dobytka.

?

**Comment by mukrop** [comment]
Toto uz davnejsie niekto opravil, issue zatvaram.
