### ISSUE TITLE
nekonzistentní indexy v CO2

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#44]
Někdy píšeme CO2, někdy CO_2. Dalo by se s tím žít, ale když se to míchá v jedné infografice, tak už je to vážně prasárna a bije to do očí. Např. https://faktaoklimatu.cz/assets/data/emise-1/Emise-sklenikovych-plynu-CR-podle-sektoru_1920.png

**Comment by mukrop** [comment]
Plus treba prejst texty stranky a zjednotit to aj tam. Osobne preferujem peknu typografiu, tj. pouzivat dolny index. V texte mozte bud pouzit priamo Unicode znak (tj. skopirovat to tak, ako to najdete niekde na internete vysadzane), alebo `CO<sub>2</sub>`.

**Comment by mukrop** [comment]
Toto issue sa tykalo aj zmenach v sprievodnych textoch, nechavam otvorene.
