### ISSUE TITLE
emise v ČR: přidat vysvětlení emise != spotřeba

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#45]
Možná je to očividné, ale stejně mi přijde na místě přidat nějakou formu vysvětlení, že emise vyprodukované v ČR != emise spotřeby v ČR.

Příklady:
- ČR vyváží elektřinu - část emisí tedy je "kvůli spotřebě někoho jiného"
- ČR dovážíme maso ze zahraničí - část emisí "jinde" jde k tíži lokální spotřebě
atd.

Nemám ale vymyšlené, jakou formou to podat. Možná samostatná inforgrafika + odrážka s odkazem u ostatních?

**Comment by mukrop** [comment]
Suhlasim, ze je to dolezite rozlisenie, ale neviem uplne, ako to naformulovat, aby to nesposobilo len vacsie zmetenie.

**Comment by ondraspribyla** [comment]
Přidal jsem komentář k datům do všech sekcí o emisích - což proteď stačí. K podrobnějšímu zpracování nám zatím chybí data... (ale souhlasím, že by to bylo zajímavé někdy zpracovat) - Takže proteď issue zavírám.
