### ISSUE TITLE
Doplnit popisek do infografiky Emise podle sektoru 2 (detail)

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#47]
Chtělo by to upravit popisek v infografice k Emisím podle sektorů 2, kde jsou detailně rozloženy energetika, doprava a výrobě. Popisek je zatím stejný jako u základní infografiky emisí podle sektorů 1

**Comment by ondraspribyla** [comment]
Doplněno, zkrácen popisek k emise-cr. Popisek k emise-cr-detailni jsem nechal a rozšířil o informace o přepočtu na obyvatele.
