### ISSUE TITLE
ScrollSpy v hlavním menu

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#5]

**Comment by mukrop** [comment]
@repli2dev vies k tomu doplnil, co vlasnte treba urobit? (Alebo to prilezitostne urobit sam?)

**Comment by repli2dev** [comment]
@mukrop no, je to investigativní práce, bo defaultní https://getbootstrap.com/docs/4.0/components/scrollspy/ nefungoval... což se mi ještě nestalo, ale podezírám, že za to může odkazování pomocí `/#anchor` namíst `#anchor`, které je ale kvůli stránce samostatné stránce grafiky potřeba :/

**Comment by mukrop** [comment]
Opravene.
Mal si pravdu, bolo to (okrem ineho) aj tym odkazovanim cez `/#anchor` namiesto `#anchor`. Vyriesil som to podmienenymi odkazmi (na stranke `index` su ine ako inde).
