### ISSUE TITLE
Pouzit Mission statement ako stranku "Proc to delame?"

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#53]
Nechceme upravit existujuci mission statement a dat ho ako stranku?

**Comment by mukrop** [comment]
Stranka ako taka existuje na https://faktaoklimatu.cz/proc-to-delame, len je treba vymysliet, kam dame odkaz na nu.

**Comment by kikinna** [comment]
Mně by dávalo smysl ten odkaz zahrnout do sekce "Myšlenka projektu a tvůrci" a mít tam něco nějakou akci, která povede na tu stránku, něco alal "chci vědět více o myšlence projektu". Píšu jen jako nápad a otevření diskuze.

**Comment by mukrop** [comment]
Ano, tiez sme s Ondrasom rozmyslali zaradit odkaz tam. Ale nejako sme nevedeli doformulovat tu vetu, co by tam odkazovala. Ak navrhnes konkretnu formulaciu, mozme to tam dat.

**Comment by mukrop** [comment]
Dat ju asi ako preklik tlacitkom.

**Comment by mukrop** [comment]
Uz neaktualne, zatvaram. Ak by sme sa rozhodli vytvorit stranku s textom, preco to robime, bude ten text treba aj tak upravit.
