### ISSUE TITLE
Zobrazeni webu na mobilech

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#54]
Zjistil jsem, že na mobilech se podivně rozhodí vršek stránky a text "Shromažďujeme data..." se naskládá do jednoho dlouhého sloupečku, a člověk pak musí hodně scrolovat než se dostane k infografikám... 

Na stránkách infografik se pak tlačítka ke stažení zobrazují těsně pod infografikou a text s odkazy tak opět není přímo vidět a dostat se k němu vyžaduje dlouhé scrolování. 
Vzhledem k tomu, že z mobilů lidi asi nebudou stahovat data bych asi preferoval, aby se tlačítka ke stažení zobrazily až dole pod textem...

**Comment by mukrop** [comment]
Este som sa zabudol vyjadrit k tej stranke infografik: To je zlozite (menilo by sa logicke poradie prvkov na stranke), ale nieco s tym casom urobime. Bude na to samostatny issue.
