### ISSUE TITLE
Vytvořit stránku s rozcestníkem odkazů

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#56]
Máme docela slušnou tabulku dobrých webů, na které stojí za to odkazovat. To by stálo za zpracování...

https://docs.google.com/spreadsheets/d/1NC1OGrQcCpvUVbwOxAi9yjnDTudUUGeGApU6Em3hpsE/edit?usp=sharing

**Comment by ondraspribyla** [comment]
Tohle je přesně věc, na kterou by stálo zaz to udělat obecný hackaton - společně bychom odkaz pořádně okomentovali, otagovali a přenesli na web - je to práce, kterou mohou dělat i laici. 
Je k tomu potřeba vymyslet (a možná i naprogramovat?) jak se budou odkazy zobrazovat uživateli.
Co vy na to? @mukrop @kikinna @crysman

**Comment by mukrop** [comment]
Na hackathon by to asi slo. Co sa prezentacie tyka, to bude asi treba vymysliet v sirsej skupine.

**Comment by mukrop** [comment]
* Zatial ako sekciu na titulku pod infografiky a pod expertne spravy.
* Zatial bez kategorizacie.
* Kazdy odkaz ma link, kratky popis, co su a kratky popis, co je na ich strankach mozne najst.
* Mozno maly obrazok? (logo/favicon.nahlad stranky?)
* Usporiadanie podla vahy v metadatach.
* Ukladat ako YAML do dat?

**Comment by mukrop** [comment]
Chceme, aby v buducnosti boli vyhladavatelne podla tagov (tj. pouzit rovnaky system ako na infografiky a studie).

**Comment by crysman** [comment]
@mukrop tady sme se domluvili že layout uděláš a já to naplním - podobně jako v případě `studie`

**Comment by mukrop** [comment]
@ondraspribyla Zacal som nahadzoval layout, ale narazil som na prilis vela nejasnosti. Prosim napis mi svoju predstavu o nasledujucom.
1) Kolko tych odkazov asi bude? 5-10? 10-20? 30+?
2) Budu jednotnej povahy (napr. organizacie FFF, CHMU, CzechGlobe, ... resp. dobre knowledge stranky), alebo to bdue zmeska vsetkeho mozneho? Ak zmeska, budes to chciet nejako roztriedit do sekcii (napr. organizacie, stranky s argumentami, stranky s datami, ...)?
3) Kolko textu bude ku kazdemu odkazu? 1 odstavec? 2 odstavce?

Dival som sa na tabulku [1] a tam je tych odkazov velke mnozstvo a popisy maju nanajvys kratke. Pytam sa, aby som sa rozhodol, ci budu mat odkazy samostatnu stranku (ak ich bude vela) alebo len sekciu na titulke (ak ich bude par). A aby som vedel, ci maju byt na celu sirku stranky (ak budu popisy dlhe) alebo na bloky (napr. tretitny tak ako infografiky a studie).

Mohol by si sem prosim dat ukazkovo spracovany jeden odkaz? (Aj preto, aby som videl, ake metadata si k nemu predstavujes.)

[1]:https://docs.google.com/spreadsheets/d/1NC1OGrQcCpvUVbwOxAi9yjnDTudUUGeGApU6Em3hpsE/edit#gid=1753371023

**Comment by crysman** [comment]
Ahojte, nemám teď čas, tak jen krátce: udělejme prosím samostatnou stránku, určitě se to rozroste. A ano, já bych chtěl podsekce. Ad šířka - nedělal bych bloky, alébrž standardní seznam, easy a přehledné.

**Comment by mukrop** [comment]
Z telefonickeho rozhovoru s Ondrasom:
* Suhlas s tym, ze toho casom bude viac a chceme samostatnu stranku.
* Cielom odkazov je pomahat kredibilite projektu. Tj. budu to odkazy na stranky/institucie s datami a relevantne dobre projekty (napr. warming stripes).
* Struktura odkazu: Obrazok, nazov, link, kratky 1-vetovy samonosny popis (bude sa zobrazova v buducnosti sam pri triedeni podla tagov), velke nestrukturovane pole (odstavce textu alebo aj odrazky s odkazmi).

**Comment by crysman** [comment]
@mukrop takže co já teď s tím? :/ čekáme na Ondráše? Nebo to můžu nějak vykopnout a dát se do toho?

**Comment by ondraspribyla** [comment]
Ahoj.

Příklad odkazu: (nutno vyladit češtinu a COPY styl)

LOGO
+
[Nazev] NASA Goddard institute for space studies
+
[Jednoradkovy tagline] Výzkumné centrum NASA zabývající se fyzikou
planetárních atmosfér, modelováním atmosféry a modely klimatické změny
+
[Delsi text] NASA GISS sídlí v campusu University of Colombia, v  New
Yorku. Na jejich stránkách můžete najít repozitář dat z meteorologických
stanic (link), zpracovaná souhrná data o teplotách na planetě ve formě map,
grafů a animací (link), kompletní dokumentaci k aktuálním verzím GCM modelů
včetně kódů (link) a samozřejmě jako u každé vědecké instituce aktuální
seznam publikací (link).

Tohle bude asi jeden z delších odkazů, jiné můžou být krátké
(warmingstripes)
--------------
Předpokládám, že tímto má MartinU podklady pro layout a můžeprogramovat. Až
bude dostatečně hotový, může Crysman začít plnit...

O.

**Comment by mukrop** [comment]
@crysman Hruby draft mas v gite.

**Comment by mukrop** [comment]
Design temer hotovo. Jedine co chyba je prominentnejsia sekcia s preklikom na titulnej strane.

**Comment by crysman** [comment]
@mukrop chápu to správně, že zdroje zůstanou jako html file (a ne .md)?

**Comment by mukrop** [comment]
Ano. Vzhladom na obsah toho subory MD nedava logiku, len komplikuje build. (Slovnik je na tom podobne, mozno to urobim aj tam, ale neponahla to a je to len technicka zmena.)
Podrobne dovody ked tak osobne vo stvtok.

**Comment by crysman** [comment]
@ondraspribyla @mukrop udělal jsem tu [2 nové commity](https://github.com/mukrop/faktaoklimatu/commits/rozcestnik)

**Comment by crysman** [comment]
@mukrop začíná mě štvát to menu a absence slovníku jinde, prosím, myslíš, že by šly zmergovat obě větve `slovnicek` a `rozcestnik` do jednoho kvůli snadnější editaci a propojení? (a nechybějícím featurám) - zmákl bys?

**Comment by mukrop** [comment]
Rozumiem -- tiez som o tom uvazoval. Ale netrufam si odhadnut, ci su obidve v stave na publikovanie v blizkej dobe (za mna aj ano, ale chcel by som na to nazory zbytku timu). Myslim, ze by sme to mohli zmaknut vo stvrtok osobne, bude to rychlejsie.

**Comment by crysman** [comment]
OK, @mukrop osobně ve čt, aspoň se mrknu na to, jak to udělat s nejmenší námahou - bych to zvládl, ale nechci se mořit, když se můžu nejprv poučit u zkušenějších...

@ondraspribyla zde [v sheetu zdrojů a odkazů](https://docs.google.com/spreadsheets/d/1NC1OGrQcCpvUVbwOxAi9yjnDTudUUGeGApU6Em3hpsE/edit#gid=0) jsem začal evidovat, co už máme "web-máme", a druhak jsem přidal experimentální sloupec "web-chceme?" - aby v tom byl nějaký systém přehledný:
![image](https://user-images.githubusercontent.com/5269350/64600086-d73d3000-d3ba-11e9-9294-eeef160edaf2.png)
- potřeboval bych, abychom na klimatonu pozaškrtali spolu `web-chceme` - abych to šlo přes více lidí...

**Comment by mukrop** [comment]
Hotovo v #180.
