### ISSUE TITLE
Stranka infografiky na mobile

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#58]
Ondras:
> Na stránkách infografik se pak tlačítka ke stažení zobrazují těsně pod infografikou a text s odkazy tak opět není přímo vidět a dostat se k němu vyžaduje dlouhé scrolování.
> Vzhledem k tomu, že z mobilů lidi asi nebudou stahovat data bych asi preferoval, aby se tlačítka ke stažení zobrazily až dole pod textem...
Navrhovane riesenie: Na mobile zbalit sekciu s tlacitkami ako menu, aby bol sprievodny text blizsie obrazku.

**Comment by mukrop** [comment]
Prerobil som stlpec metadat tak, ze na mobilos sa zobrazuje v znacne minimalistickej verzii (sekcia na stiahnutie vobec a z ostatnych dvoch sekcii len tlacitka).
@ondraspribyla: Riesi to tvoj problem, mozem issue zavriet?

**Comment by ondraspribyla** [comment]
Za mě dobrý. Dává naprosto smysl, že tam jsou tlačítka jen na sdílení a data...
Tedy děkuju a issue zavírám...
