### ISSUE TITLE
Global mean temperature

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#59]
Data pro global mean temperature připravený na Gdrivu k designu grafiky. Výsledek by měl být podobný jako graf teploty v ČR

https://drive.google.com/file/d/1NPXAUjJMPF-ZqEniz1ylrHnC5Hy-PSOG/view?usp=drivesdk

**Comment by kikinna** [comment]
Prosím o doplnění: 
* popisek (je-li třeba, ale podle mě by se hodilo nějaké vysvětlení, na co koukáme)
* nechtělo by v názvu odrazit, že to je ta povrchová teplotní anomálie? Ale nejsem si jistá, jaký je korektní český termín
* Taky by asi stálo za to nějak poukázat na to, že globální znamená světová? Nebo to přejmenovat zrovna na světová? Globální je docela obecnej pojem vztažitelný na více věcí.

Jinak je to ok?

![Globální průměrná teplotní anomálie-01](https://user-images.githubusercontent.com/11555522/62127137-a228c280-b2d1-11e9-9737-5dd5bae60ae7.png)

**Comment by ondraspribyla** [comment]
Ahoj Kik, 
Díky za zpracování... začal jsem tvořit celý text k tepliotní anomálii[ tady](https://docs.google.com/document/d/1E2nS3GizUl0m1fqBB3NG9j2TREo7vG652idTqSYw-4M/edit?usp=sharing). Tím, že jsou to hodně agregovaný data bude trochu složité vysvětlit jasně o co jde v omezeném prostoru grafiky. Takže to nebude dokonalé, ale pouze nejlepší v rámci omezení...

1. v popisku je důležité uvést referenční období (tedy nastavení "nuly") - to je 1951-1980. (což taky znamená, že oteplení o 1°C je vůči takto nastavené nule, nikoliv vůči pre-industriálu)

2. název grafu = Vývoj světové teplotní anomálie
poznámky k názvu: přijde mi důležité zdůraznit čas - proto "vývoj". Global mean surface temperature annomaly bych kvůli přehlednosti názvu uváděl jen jako "světová teplotní anomálie" - přidání slova "povrchová" je zavádějící, protože asociuje pevninu - ale měření probíhá i nad mořem, snaha je dodržet "2m nad povrchem". Přidání slova "průměrn" nevysvětluje dostatečně průměrovací metody a tedy IMHO ubere přehlednosti ale nepřidá významu. 

3. Text pod názvem navrhuju: __ Svět je nyní o 0,8 - 1°C teplejší než v letech 1951-1980. Data jsou vážený průměr teplotních anomálií 6300 meřicích stanic na pevnině i na moři.__

4. popisek pro modré tečky: __ Světová teplotní anomálie pro daný rok __

5. ještě bych nějak víc zdůrazni zdroj dat NASA (i když data všch zzpracovávaných stanic jsou veřejně dostupná)

**Comment by kikinna** [comment]
Infografika ready, můžete publikovat s textem ;)

**Comment by mukrop** [comment]
A kde je ta infografika nahrana? V gite ani v gDrive ju nevidim.
* Postup prace: Idealne nahravajte rovno do gitu, ked je prispevok oznaceny ako "published: false", tak sa to na web neprepisuje.
* Este minimalne chyba finalny dataset.

**Comment by ondraspribyla** [comment]
Nahrana není - Kika ma nějaké problémy s exportem do svg. Její svg se mě
zobrazuje rozhazený a šedivý... tak jsem to ještě nepublikoval. PDF a PNG
jsou OK.
Finální dataset zkompletuju teď cestou ve vlaku...

O.
ᐧ

**Comment by mukrop** [comment]
Nasadene na https://faktaoklimatu.cz/infografiky/vyvoj-teplotni-anomalie
Prosim @ondraspribyla o nasledovne:
* [ ] Vizulanu kontrolu, ze to vyzera OK.
* [ ] Pripadne rozsirenie popisu pod obrazkom. Aktualne je tam kopia podnadpisu infografiky, chcelo by to trochu rozviest. Ty si tam dal len odkaz na zdroj dat, ale ten som zmazal: V popisoch mavame interpretaciu (zdroj dat je strukturovane vpravo).

**Comment by mukrop** [comment]
Pridal som este ziadost o potvrdenie skratky/slugu/URL.

**Comment by ondraspribyla** [comment]
Díky :-) Popisek obrázku jsem vylepšil, všechno ostatní je OK. Issue
zaviram.
ᐧ

**Comment by ondraspribyla** [comment]
Vse OK, popisek jsem doplnil. Grafika je publikovaná a issue zavírám.
