### ISSUE TITLE
Globální průměrná roční teplota - popis metodiky

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#61]
Doplnit metodiku průměrování, která bude umístěna do infografiky.

**Comment by ondraspribyla** [comment]
Doplňující text ke grafu hotov zde: https://docs.google.com/document/d/1E2nS3GizUl0m1fqBB3NG9j2TREo7vG652idTqSYw-4M/edit?usp=sharing

**Comment by ondraspribyla** [comment]
K umístění do infografiky navrhuju:
* místní teplotní anomálie udává, o kolik byl daný rok v daném místě teplejší než průměr z let 1951-1980. Světová teplotní anomálie je váženým průměrem místních teplotních anomálií, který koriguje rozdílnou husotu měřicích stanic v různých oblastech světa.

**Comment by ondraspribyla** [comment]
@kikinna, @mukrop - až Kika dodá finální verzi grafu a exporty, můžeme nový graf publikovat. Text k němu je připraven zde: https://docs.google.com/document/d/1E2nS3GizUl0m1fqBB3NG9j2TREo7vG652idTqSYw-4M/edit?usp=sharing

**Comment by mukrop** [comment]
Ahoj.
* Rozpracovane stranky prosim davat rovno do repa, google dokumenty sa s takymito "pseudotextovymi subormi" velmi nekamaratia.
* Ked k stranke v repozitari pridate do hlavicky "published: false", tak sa nebude exportovat na web (ale pri zostaveni lokalne je dostupna, takze sa da ladit).
* Ondrasov draft som hodil do gitu (neexportuje sa verejne zatial).
* @ondraspribyla: Prosim povedz, aku by si chcel skratku do URL (na to sa pouziva ten atribut `slug` v hlavicke). Ja som dal `vyvoj-teplotni-anomalie`, moze byt?

**Comment by mukrop** [comment]
Stare issue, hotovo.
