### ISSUE TITLE
Uprava SVG pro Wikipedii (Pavouk)

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#64]
Petr Pavouk Ledvina am napsal poznamku, ktera vyzyva ke změně v způsobu tvorby obrazku...

je potřeba: 
1. zaujmout rozhodnuti
2. případně opravit svg verze
3. napsat zpět Pavoukovi 
----
SVG garfy jsou všechny ve křivkách, tedy i text, pak se nedají případně vůbec upravovat, nebo jen velmi špatně; měly by být textová pole jako text (v nějakém svobodném a rozšířeném fontu, jako jsou třeba grafy na Wikipedii, viz např. "moje" radiační bilance https://commons.wikimedia.org/wiki/File:Radiacni_pusobeni_AR5.svg  (je to  překlad z AR5 za využití pojmů Jeníka). Když tam najdeš chybu (posunutý text, špatnou des. tečku, index) snadno opravíš. Když to je ve křivkách, není to ono.

https://faktaoklimatu.cz/assets/infographics/emise-vybrane-staty_1920.png  opět nadbytečná tučná tečka v první větě pod nadpisem

Licenčně jsou obrázky v pohodě - dají se použít pro Wikipedii, viz https://commons.wikimedia.org/wiki/Commons:Licensing/cs  Koukám, že kolega Jirka dlouhý je už (předevčírem) v příslušném textu Globální oteplování v Česku  https://cs.wikipedia.org/wiki/Glob%C3%A1ln%C3%AD_oteplov%C3%A1n%C3%AD_v_%C4%8Cesku  použil. A teď se nedaj upravovat, viz výše! A mimochodem, a velmi důležitě, nejde z nich kopírovat text (vše jsou křivky) - takže jsem ti nemohl snadno uvést, co je špatně. Narozdíl od https://upload.wikimedia.org/wikipedia/commons/8/8b/Radiacni_pusobeni_AR5.svg  kde si můžeš texty kopírovat.

**Comment by mukrop** [comment]
@kikinna: Ja by som asi bol za to, aby tam bol text ako text. Vidis v tom nejaky problem?

**Comment by kikinna** [comment]
No, problém, který v tom vidím je to, že zatím nevím jak na to :D Dívám se teď na to v rychlosti a nedaří se mi tam vložit custom font zatím (možná s tím má někdo z vás zkušenost?). 
Ale pokud to půjde, tak určitě jsem za!

Pokud ne, tak to potom vnímám jako volbu mezi "mít pěknější font" vs "mít upravitelné texty" ve fontu, který budou mít dostupní všichni (reálné?).
V ten moment můj osobní názor by bylo raději "mít pěknější font", protože stavíme na tom, že naše infografiky jsou atraktivní, zaujmou a lákaj čtenáře infografiku prozkoumávat. Když to srovnám, jak často by někdo chtěl upravovat text, tak mi to přijde důležitější. 
K tomu patří i další myšlenka — pokud chce někdo upravit chybu, preferovala bych to tak, aby nám dali vědět / submitli issue a my to opravíme a tím pádem všichni budou mít dostupnou opravenou verzi (což si žádá aktivitu i v budoucnu, s čímž já za sebe nevnímám problém). 
Další s tím související myšlenka, co mě napadá — chceme si budovat určité jméno / důvěru, že stavíme na datech, tak mi přijde i fajn mít "vlastní" písmo, které je naše jakoby signature. A pokud by si někdo chtěl infografiku upravit a měnit texty, tak si zvolí písmo své a pak bude na první pohled jasné, že to je už infografika modifikovaná a nepocházející od nás (a vzhledem k tomu, že těch textů je tam minimálně, tak v tom nevidím zase tak zásadní problém?).

Nicméně souhlasím, že by byla škoda, že by text nebyl kopírovatelný (což zatím spíš není problém, ale pokud bychom měli infografiky s více textem, tak to už vnímám jako překážku). Takže jsem pro hledání cesty, jak tam custom font dostat.

**Comment by mukrop** [comment]
Hm, googlim a fakt je to viac tricky, ako som si myslel. Asi je to blbost, ale skus export namiesto ukladania ("In newer versions of AI there are three ways to save/export to SVG: File > Save As > (choose SVG type); File > Export > Export As... > (choose SVG type) and File > Export for Screens > (add SVG format).")
Ak to nepomoze, skus font embedding with Nano: https://vecta.io/nano

**Comment by mukrop** [comment]
Este jeden napad: Skus mi poslat PDF s dobre embednutymi fontami a ja zistim, ci neviem urobit dobry export do SVG (tak by PDF bol nas primarny exportny format, z ktoreho by sa odvodzovali ostatne).

**Comment by kikinna** [comment]
@mukrop Marti, ten export for screens funguje! Takže to všechnopřeexportuju, jakmile fixnu ty ořezy, ju? ;)

**Comment by mukrop** [comment]
Zaver:
* Kopirovatelny text by sme chceli, ale realizacia v SVG s aktualnym pismom je narocna. Kedze vlozit pisma do SVG nejde spolahlivo (mnohe klienty to pismo nezobrazuju z bezpecnostnych dovodov), museli by sme prejst na ine pismo (ktore aj tak nevieme zarucit, ze budu mat vsetci). Kedze je pre nas dobra vizulna stranka dolezita, rozhodli sme sa pismo nemenit aj napriek nutnosti krivkovat text. Najdene chyby budeme momentale radi opravovat my.
* Kopirovatelny text v PDF suboroch doplnime, tam je to technicky v poriadku (malo by to byt za par dni).

@ondraspribyla: Napis prosim Pavoukovi a issue zatvor.

**Comment by ondraspribyla** [comment]
Pavoukovi jsem napsal. Issue zaviram
