### ISSUE TITLE
Srovnání celkových ročních emisí států EU 

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#67]
Data [tu](https://docs.google.com/spreadsheets/d/1IJn4amBeD2Ra_0LFKCWY-iT-UyaxpaU2pvoQ-uuPp2o/edit#gid=525565541)

**Comment by kikinna** [comment]
Go for Tree map vis

**Comment by ondraspribyla** [comment]
Evropa momentálně zpracovaná dostatečně tady: https://faktaoklimatu.cz/infografiky/emise-eu
Někdy to můžeme vylepšovat, ale  nyní zavírám.
