### ISSUE TITLE
Vysvtělení emisí jednotlivých států

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#69]
Doplnit vysvětlení, proč které státy mají dané hodnoty emisí na osobu v jednotlivých sektorech, např. Irsko (agriculture).

**Comment by ondraspribyla** [comment]
Lucembursko má většinu emisí z dopravy, protože mají nízký daně za benzin a lidi k nim jezděj nakupovat benzin z okolí...
https://today.rtl.lu/news/luxembourg/1184731.html
+Luxembourg petrol/fuel tax

**Comment by crysman** [comment]
zde po dnešku zavírám, neb:

1. za chvíli zvěřejníme ostrou, Lucembursko tam je vysvětleno s použitím odkazu výše
1. vysvětlení dalších je vidět v tomto sheetu této tabulky (odkazováno v budoucí ostré): https://docs.google.com/spreadsheets/d/1ldy3l-W0HDG1cHK393_rQC5pGXIWbVw94Dh3ie4aEI8/edit#gid=1336176067
