### ISSUE TITLE
SVG bug in Trend nárustu teplot v ČR v jednotlivých měsících

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#70]
Na wikipedii v článku o [globálním oteplování ](https://cs.wikipedia.org/wiki/Glob%C3%A1ln%C3%AD_oteplov%C3%A1n%C3%AD_v_%C4%8Cesku)je rozsypané svg

![image](https://user-images.githubusercontent.com/11555522/62115945-99c48d80-b2b9-11e9-8a02-ef4030c88353.png)

**Comment by mukrop** [comment]
Toto je ale problem zdrojoveho SVG, tiez som s nim mal problem pri koverzii (a aktualne konvertovane PDF ma ten problem tiez). @kikinna: Prosim skus nejako vyladit zdrojovy subor. Okrem srafovanych obdlznikov sa mi okolo niektorych popisiek zobrazuje obdlznik (viz obrazok).
![screenshot](https://user-images.githubusercontent.com/1871676/62133995-0c486400-b2e0-11e9-9eeb-8289de37171f.png)

**Comment by kikinna** [comment]
To do : update wikimedia file and wikipedia article [Globální oteplování v ČR](https://cs.wikipedia.org/wiki/Glob%C3%A1ln%C3%AD_oteplov%C3%A1n%C3%AD_v_%C4%8Cesku)

**Comment by mukrop** [comment]
Aktualizovane uz aj na Wikipedii.
