### ISSUE TITLE
Duplictní nadpis infografik na webu

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#71]
Vymyslet duplicitní nadpis na webu
![image](https://user-images.githubusercontent.com/11555522/62117217-cd081c00-b2bb-11e9-9468-d52fb2b1b112.png)

**Comment by mukrop** [comment]
Navrhovane riesenie: Pri zobrazovani infografik orezavat hornych x% (v ktorych bude nadpis a vzdy prave nadpis). Tym zostava v poriadku, ze ked clovek infografiku stiahne (aj keby vybral obrazok a dal ulozit ako) tak tam ten nadpis bude mat. To iste asi urobit aj s patickou.

**Comment by kikinna** [comment]
Asi je to nejlepší řešení. 
Přemýšlela jsem nad tím a nebyla jsem si jistá, jestli nevadí mírná nekonzistence — člověk kouká na něco jiného než, co se mu pak stáhne, ale vlastně je to asi docela běžný postup ;) Takže jsem pro. ))

**Comment by mukrop** [comment]
Tak som to nakoniec orezal. Tj. nezobrazuje sa hornych 9% infografiky a na stranach a dole 3.5%. Asi si do sablony infografiky dokresli tieto linky, ze tam nic nema byt (resp. ma tam byt primarny nadpis a paticka).
Z toho vzislo par dalsich bodov:
* Nadpis v infografike a na stranke obcas nie je rovnaky. Pekne to vidno na https://faktaoklimatu.cz/ -- ked podrzite na infografiku, v tooltipe je nazov stranky. Mohli by sme to prosim zjednotit? Tyka sa to jednej teploty a vsetkych troch emisii. @ondraspribyla, ktore su spravne nadpisy?
* Rozhodol som sa trochu zvyraznit interpretacny popis pod obrazkom (ciara, kurziva, vacsi font). @ondraspribyla, @kikinna Mrknite, ci je to takto OK (mne sa to zda ako vylepsenie). Zaroven som z tychto popisiek vyhodil zdroj dat, bolo to duplicitne (mame ho medzi ostatnymi zdojmi a odkazmi na boku).
* Pri takto nastavevenom orezavani infografiky v teplote mo nesiacoch jemne rezem Cervenec. @kikinna, mohla by si to prosim opravit?

**Comment by mukrop** [comment]
Oprava: We cut ~3.5% from sides, ~13.5% from top and 5.3% from bottom.

**Comment by mukrop** [comment]
@kikinna: Ked nad tym tak rozmyslam, tak aktualne je to asi OK. Ak niekedy v buducnosti ty alebo niekto iny bude chciet upravit orezavane okraje, otvorime si na to potom novy issue.
