### ISSUE TITLE
Uklidit datový soubor emisí

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#72]
Chtělo by to pročistit soubor emisí skleníkových plynů, např: 
* Rozumně přejmenovat celý soubor a i jednotlivé záložky
* Záložky bychom měli začít možná nějak jednotně pojmenovávat a to i napříč všemi datasety? (E.g. "RAW + název" pro původní data "VIS + data" pro podkladová data pro vizualizace, "ANALYZA + název" pro nějaké analýzy, atd.?) 
* ujistit se, že všechny hodnoty jsou korektně pojmenované (např. chybí popisek k řádku s procenty celkových emisí pro státy Evropy)

**Comment by ondraspribyla** [comment]
S potřebou úklidu a konzistentního přejmenování souhlasím. Jen dodám, že jsme se s Martinem dohodli na "policy": datové soubory, na které odkazujeme zz webu jsou v samostatné složce a jsou "vyčištěné". Soubory v původních složkách jsou "pracovní..."

**Comment by ondraspribyla** [comment]
To Jeňa: máme tu tohle staré issue a souvisí s úklidem datových souborů k EMISE CR a EMISE EU...
takže tě k tomu přidávám, ať dobře trackujeme práci (zadanou i diskuse, dotazy ...)

**Comment by ondraspribyla** [comment]
@jankrcal - je tohle ISSUE hotovo? Vím, že jsi v tom něco udělal, ale nevím, jaký je stav... Jestli je hotovo, prosím zavři...
