### ISSUE TITLE
Vysvětlovat jednotky a jak se čtou?

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#75]
Myšlenka. Ví lidi, jak se čte  tCO2eq nebo  Mt CO2eq?
Jen, že bych mohla do infografik doplnit celý název, aby když o tom mluví, tak se nezasekávali na jednotkách?

**Comment by kikinna** [comment]
Teda, možná by stačilo psát "miliony tun" místo "Mt"?

**Comment by ondraspribyla** [comment]
...tohle je podle mě issue na nějaké veřejné testování. Obecně bych se
trochu bránil snahám vysvětlovat úplně všecko - to se pak signál ztrácí v
šumu vysvětlování...

O.
ᐧ

**Comment by kikinna** [comment]
Tak nějakou střední cestu? Teď pracuji na infografice a už jsem použila třeba "miliony tun CO2eq". To by podle tebe třeba šlo? 
![image](https://user-images.githubusercontent.com/11555522/62285095-3c654380-b455-11e9-8f32-8fcab53b7784.png)

**Comment by ondraspribyla** [comment]
*Aha, tady je to naprosto čitelné i v plné verzi "miliony tun" - tedy asi
záleží na konkrétním grafu.*
*Jinak kvůli konzistenci jsem navrhnoval nechat pouze státy EU - viz
odpověd na předchozí mail.*
Výhledově totiž budeme mít následující hierarchii:
- Emise Světa v nichž emise EU figuruje jako jedna položka.
- Emise EU v nichž emise ČR figuruje jako jedna položka.
Odpovídá to i politickému členění - jsme členy EU, tedy má smysl
jednoznačně zobrazovat tuto úroveň.

Uvádět zobrazení jako srovnání Evropských států je problematické: Co Rusko,
Ukrajina nebo třeba Albánie? O nich nemáme data ze stejného zdroje...

O.
ᐧ

**Comment by kikinna** [comment]
Souhlasím, zahrnu jen EU. Upravím data ;) 
Jinak díky moz a podněty! ))

**Comment by ondraspribyla** [comment]
Otázku uzavírám - problém převedena na #234
