### ISSUE TITLE
Navrhnout jednotný systém pro "čistá data"

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#77]
Co takhle vytvořit nějaké guidelines pro to, v jakém formátu mít data. Jednak tím dosáhneme nějaké konzistence a hlavně když se data pak zpracovávají dalšími nástroji (třeba v kódu nebo Tableau public atd.), tak je vhodné je mít ve specifickém v tzv. čistém formátu (co sloupeček, to jeden atribut).

Byly byste pro? Pokud jo, mohla bych to zpracovat a nachystat dokument s guidelines a třeba vzorově vyčistit jeden soubor a pak by to mohlo být něco, s čím nám někdo může pomoct na dalším hackathonu pro ostatní datové sady?

**Comment by ondraspribyla** [comment]
No... zatím máme tři datové sady, když k tomu přidáme GISS tak čtyři -
všechny grafy jsou produkty z těchto... Moc bych teď na jednotné formáty
netlacil... Myslím že postupem času se nám ukáže, jaké "standardy" mají
smysl a jaké ne...

Dne čt 1. 8. 2019 12:35 uživatel kikinna <notifications@github.com> napsal:

**Comment by mukrop** [comment]
Nebranim sa tomu, nieco take mat, ale suhlasim s Ondrasom, ze mozno je to teraz skoro. Kazdopadne by bolo fajn doporucenie, ked niekto bude tvorit novy dataset, aby sa pozrel, ako vyzeraju tie stare a postupne hladal ten idealny cisty stav.

**Comment by kikinna** [comment]
Okej, souhlas )

**Comment by mukrop** [comment]
Assigned to Yena.

**Comment by ondraspribyla** [comment]
Nápad: každý náš Gdokument by mohlo mít úvodní README sheet, ve kterém by byly vysvětleno odkud data jsou, jaký kód při vybarvování buňek používáme, (např. modré jsou pomocné výpočty, nebo ověření, která považujeme za detailní a podrobná, takže je nedáváme přímo do výslední grafiky...

**Comment by jankrcal** [comment]
Moje představa je, že všechno podstatné včetně odkazy na zdrojová data atd, bude v prvním (hlavním) sheetu a další sheety (pokud jsou potřeba) budou odkázané z hlavního sheetu. Nevím, jestli potřebujeme color coding, čím méně instrukcí, tím podle mě lépe. Ale pokud bude nutné, souhlasím, aby bylo vysvětlené na prvním sheetu.

Mám pořád rozpracovaný dokument emise ČR. Ještě jsem to nestihl dodělat, mám teď hektický pracovní týden. Nejpozději v pátek to dotáhnu a pak můžeme probrat připomínky na konkrétním případě.

**Comment by jankrcal** [comment]
Můj návrh pro emise ČR:
https://docs.google.com/spreadsheets/d/1y52VXoiW7OmzT1sm1UQeT0XhZTuKge1962A4pjFmqzg/edit#gid=0

Současný final emise ČR pro srovnání:
https://docs.google.com/spreadsheets/d/1igCIcrkec7J6sfp4L4lGMzeDS4Mf-o7GZOxduZC8-pc/edit#gid=0

Kromě reformátování jsem přidal leteckou dopravu, viz Issue #136.

Principy, na kterých je to založeno:
 - Vše podstatné pro výslednou grafiku najdu a pochopím z hlavního listu.
 - Primární data musí mít vyplněný zdroj, odkaz, čas stažení a samotnou hodnotu (pro skalární hodnoty) nebo odkaz na přílohový list (pro tabulkové hodnoty). Pokud používám přílohový list, tak do něj co nejméně zasahuju, aby to byla čistá stažená data. Vyjímky okomentuju v komentáři na hlavním listu u tohoto zdroje dat.
 - Na hlavní listu buduju výcuc z dat, který potřebujeme do grafiky. Všechny údaje je potřeba vyjádřit pomocí vzorců z primárních dat (klíčové pro snadnou ověřitelnost výpočtu).
 - Pokud před prezentací dat potřebuju nějaký jednoduchý mezivýpočet (výtah dat z přílohy), který je užitečný pro pochopení dat pro grafiku, můžu ho dát na hlavní list (viz v sheetu sekce 4. Výtah emisí hnědouhelných elektráren).
 - Pokud je výpočet příliš složitý a technický, můžu pro něj vytvořit další přílohový list a odkázat na něj jako na sekundární zdroj dat z hlavního listu. Tento pomocný výpočet opět musí tahat všechny údaje pomocí vzorců z primárních dat.

@kikinna, nesmazal jsem něco důležitého pro export do dalších nástrojů? (pokud někde data nejsou v čistém formátu nebo tam chybí nějaký důležitý sloupec, dej prosím vědět nebo to rovnou uprav). Samozřejmě taky piš, pokud máš celkově jinou představu, je to přece jenom původně tvoje iniciativa :)

@ondraspribyla, prosím o připomínky. Klidně si můžeme zavolat, kdyby to tak bylo snazší.

**Comment by jankrcal** [comment]
Ještě dodám, že jsem se inspiroval u https://docs.google.com/spreadsheets/d/1FAYM6H4IA1PzKUgn2Slg9d99xrquxqnAXoXQBzg0odg/edit#gid=21, zdrojového sheetu k https://informationisbeautiful.net/visualizations/how-many-gigatons-of-co2/.

**Comment by mukrop** [comment]
Za mna super, velmi sa mi to paci. Principy formatovania dat (tak, ako si ich tu spisal) by chcelo niekam odlozit. Mozno urobit v zlozke s finalnymi datami dokument?
@ondraspribyla: Ak si s tymto vysledkom spokojny, mam Jenovi pridat pristup do finalnych datasetov, aby to prekopiroval tam?

**Comment by ondraspribyla** [comment]
Jsem naprosto nadšený. Je to skvěle přehledné. Tedy velké DIKY. 

Musel jsem si na to sednout v klidu a chvili kriticky přemýšlet, abych našel problematické věci. Pár jich mám, zde navrhuju změny:  

0-1. Letecká doprava - chtěl bych, aby se ve výstupech zobrazovala hned vedle dalších položek Dopravy, kvůli srovnatelnosti. Už jsem upravil, HOTOVO. 

0-2. Barvy výstupního grafu - u výstupního grafu zůstaly barvy z předchozích prací, takže některé položky byly šedě... upravil jsem, tak aby byly sektory barevně rozeznatelné. HOTOVO. 

1. Zvýraznění VSTUPY - VÝSTUPY: Rád bych, aby bylo zřetelně vidět, co jsou vztupy do našeho grafu (tedy data, zaz jejichž správnost zodpovídá ten, od koho je přebíráme) a co je naše práce a tedy zodpovídáme za srpávnost my. Navrhuju 
 - - přehodit pořadí tak, aby v rámci listu SHRNUTÍ byly všechny vstupní data nahoře a výstupy teprve pod nimi. 
 - - přidat barevný kód - třeba vstupní data modře a naše výstupy do žluta...
 - - případně rozdělit první list na SHRNUTI -VSTUPY a SHRNUTI VYSTUPY
 - - Zdvojovat informaci a v prvním řádku v listech EMISE EUROSTAT a POVOLENKY nechat větu "Data jsme stáhli od [link] a upravili jsme je [upravy]".

2. Položka Jiné: Rád bych, abychom v komentáři listu SHRNUTI vysvětlili, co položka JINE, která je získána jako dopočet do celku, vlastně obsahuje... mělo by to zřetelně být vidět v listu EMISE EUROSTAT.

3. Úpravy listu EMISE EUROSTAT:  by bylo hezké přidat sloupeček poznámky a vysvětlit pojmy jako MEMO / MEMONIA (není samozřejmé a čtenář nemusí pochopit proč jsme co vybrali), označit které položky jsou v sektorech Energetika, Doprava, Spalování v domácnostech a jiné...    

4. Další listy: V tomto datovém souboru to není zásadní, v jiných jsme ale nad daty dělali nějaké analýzy, které stojí za to mít přístupné ale nejsou tak důležité, abychom je dali do infografiky. Myslím, že by na to měly být samostatné sheety  
----
Thats all.

**Comment by ondraspribyla** [comment]
Jaký uděláme další postup? Myslím, že bychom měli:



- [ ]   Implementovat úpravy v souboru, který Jeňa vytvořil, nebo rozhodnout, že je nebudeme dělat.  

- [ ] Soubor, který vytvořil Jeňa prohlásit za finální, přejmenovat ho, zamknout ho a opravit linky na soubor ve všech zdrojových textech

- [ ] Domluvit se s Jeňou, zda by opravil i další soubory Naše Data. (je to trochu forma učení o tom, co už máme hotové, a hlavně to udělal úplně božsky :+1: 

Souhlas?

**Comment by ondraspribyla** [comment]
...viz commenty v Gitu. Akorát jsem si uvědomil, že možná je jednodušší,
aby Jeňa zkopíroval listy do finálního souboru a my tak nebudeme měnit
žádné linky ve zdrojových textech...

O.

**Comment by ondraspribyla** [comment]
@protivinsky - 
Tady je styl, ve kterem budeme prezentovat finalni data> https://docs.google.com/spreadsheets/d/1y52VXoiW7OmzT1sm1UQeT0XhZTuKge1962A4pjFmqzg/edit#gid=0

**Comment by crysman** [comment]
WOW, dost dobrý!

Ad:
> ...Akorát jsem si uvědomil, že možná je jednodušší, aby Jeňa zkopíroval listy do finálního souboru a my tak nebudeme měnit žádné linky ve zdrojových textech... O.

Ano, upravit stávající dokument, **nepřelinkovávat** @jankrcal @ondraspribyla

**Comment by jankrcal** [comment]
Co se týče publikování, v tomto případě bych udělal vyjímku a soubor přelinkoval na webu. Důvod je, že se změnily data (přidání letecké dopravy) a tak potřebujeme předělat graf na webu. Pak mně přijde lepší to udělat atomicky v jednom commitu.

@kikinna Můžeš na to prosím kouknout, jestli to splňuje Tvoje představy a jestli je to použitelný pro další grafickou práci?

U ostatních datasetů souhlasím, nejjednodušší bude nakopírovat nové listy do stávajícího dokumentu.

**Comment by protivinsky** [comment]
Vytvorim obdobny soubor pro #111. S daty jsem pracoval v pythonu, uvidim, zdali bude mozne vypocty plne zreplikovat v google drive pomoci vzorcu (pouzival jsem asof join, i kdyz u tech finalnich dat nejspis neni potreba; porad vsak potrebuju alespon zakladni outer join, coz doufam GD umi).

**Comment by jankrcal** [comment]
Teď ještě k připomínkám:

> Jsem naprosto nadšený. Je to skvěle přehledné. Tedy velké DIKY.

To mám moc radost, díky!
 
> Musel jsem si na to sednout v klidu a chvili kriticky přemýšlet, abych našel problematické věci. Pár jich mám, zde navrhuju změny:
> 
> 0-1. Letecká doprava - chtěl bych, aby se ve výstupech zobrazovala hned vedle dalších položek Dopravy, kvůli srovnatelnosti. Už jsem upravil, HOTOVO.

Skvělé, díky.

> 0-2. Barvy výstupního grafu - u výstupního grafu zůstaly barvy z předchozích prací, takže některé položky byly šedě... upravil jsem, tak aby byly sektory barevně rozeznatelné. HOTOVO.

Supr, díky.

> 1. Zvýraznění VSTUPY - VÝSTUPY: Rád bych, aby bylo zřetelně vidět, co jsou vztupy do našeho grafu (tedy data, zaz jejichž správnost zodpovídá ten, od koho je přebíráme) a co je naše práce a tedy zodpovídáme za srpávnost my. Navrhuju
> 
> * * přehodit pořadí tak, aby v rámci listu SHRNUTÍ byly všechny vstupní data nahoře a výstupy teprve pod nimi.

Souhlas.

> * * přidat barevný kód - třeba vstupní data modře a naše výstupy do žluta...

Podbarvil jsem jen nadpisy, nerad bych to vizuálně zahlcoval.

> * * případně rozdělit první list na SHRNUTI -VSTUPY a SHRNUTI VYSTUPY

Toto mi nepřijde tak praktické (musíš víc překlikávat mezi listy), třeba to použijeme u nějakého složitějšího datasetu, kde struktura výstupů bude o dost jiná než struktura vstupů.

> * * Zdvojovat informaci a v prvním řádku v listech EMISE EUROSTAT a POVOLENKY nechat větu "Data jsme stáhli od [link] a upravili jsme je [upravy]".

Plus mínus hotovo. Odkázal jsem tam jen zdroje a komentáře z hlavního listu. Tak to není tak gramaticky pěkné. Řešením mi přijde uhladit texty v komentářích, tam se to taky bude hodit.
 
> 1. Položka Jiné: Rád bych, abychom v komentáři listu SHRNUTI vysvětlili, co položka JINE, která je získána jako dopočet do celku, vlastně obsahuje... mělo by to zřetelně být vidět v listu EMISE EUROSTAT.
> 2. Úpravy listu EMISE EUROSTAT:  by bylo hezké přidat sloupeček poznámky a vysvětlit pojmy jako MEMO / MEMONIA (není samozřejmé a čtenář nemusí pochopit proč jsme co vybrali), označit které položky jsou v sektorech Energetika, Doprava, Spalování v domácnostech a jiné...

Na toto už dnes nemám sílu. Udělám během příštího týdne. Pokud to máte někdo v hlavě (kdo jste původní data set dělali), klidně to přenechám, možná to bude rychlejší?

> 3. Další listy: V tomto datovém souboru to není zásadní, v jiných jsme ale nad daty dělali nějaké analýzy, které stojí za to mít přístupné ale nejsou tak důležité, abychom je dali do infografiky. Myslím, že by na to měly být samostatné sheety

Ano, plný souhlas, uvidíme na dalších datasetech.

> Thats all.

**Comment by jankrcal** [comment]
Počítám s tím, že se postupně kouknu i na další data sety. Nevím, kolik toho stihnu do týdne pro klima. Kdyby mě z toho hrabalo, tak se ozvu s prosbou o pomoc :)

**Comment by protivinsky** [comment]
Obdobny soubor pro #111 (emise-svet) - https://docs.google.com/spreadsheets/d/1aZNVRC7lJM28FxbKKnXo7HsPlyE2RaMbG3KDs8igwec/edit#gid=0

Momentalne mam hlavni vystupy na samostatnem listu - emise za regiony (vcetne per capita a per GDP) by bylo mozno prekopirovat na list "Shrnuti", akorat tam pak prilis nesedi sirka sloupcu apod (zahlavi u vstupu nedavaji u mych vystupu prilis smysl). Nevim, zdali je lepsi to proste ponechat na samostatnem listu nebo to take prekopirovat a zkusit nejak poupravit, aby to rusilo co nejmene.

Pokud mate pripominky / dotazy / navrhy co jeste s tim, dejte vedet.

**Comment by protivinsky** [comment]
Napriklad premyslim, jestli by vlastne nebylo lepsi vynechat seznamy zemi (_Ciselnik zemi podle CSU_ a _Prirazeni zemi k regionum_) - vypocet _Emise jednotlivych zemi_ to prirazeni obsahuje take a napojeni kodu zemi k ceskym nazvum a nasledne k vybranym regionum pravdepodobne neni prilis dulezite / sporne.

**Comment by jankrcal** [comment]
Já jsem v mezičase zpracoval soubor k emisím Evropa:
https://docs.google.com/spreadsheets/d/1Oi6MiPxSKRN2vlssITAqsVwjsalQazCyymNdHHc-iYg/edit#gid=979818322

Mám z toho pár pozorování:

1) Šířka sloupců v listu "Shrnutí"
 - Skutečně šířka sloupců v tabulce Shrnutí nebyla ideální na zobrazování tabulek. 
 - Co navrhuju místo toho je jednoduchý (rigidní) formát s šířkami sloupců (v px):
      |40| 360            | 120 | 120 | 120 | 120 | ...
   Tedy kromě prvního sloupce na čísla sekcí a druhého sloupce na popis položek budou všechny sloupce stejně široké. To se dost hodí na jekékoliv výstupní tabulky s čísly s mnoha sloupci.
 - Tento formát se nehodí do vstupních dat na sloupec "Komentář", tam ale lze spojit třeba 3 buňky vedle sebe a vše je fajn.

 2) Snadno se stane, že člověk ve Výstupech ve Shrnutí má více dat než v samotném grafu (např. pro emise evropa tam mám vybrané kategorie pro všechny sledované země a ne jen pro 7 vybraných pro graf). Pokud je výsledek pořád pěkně přehledný, považuju to za výhodu. Souhlasíte?

 3) Některé funkce v excelu mají jako výstup tabulku. Vzorec je jen v levém horním rohu, zbytek vypadá, jako by tam byla nakopírovaný ručně. V tabulce jsem tyto buňky, co generuje levý horní roh naznačil velmi světle šedou (#fafafa) barvou na jejich pozadí. Chápu to hlavně jako nástroj pro nás, abychom se v tom sami neztratili, proto tam nemám žádnou legendu, kde bych se to snažil vysvětlit. Je toto za vás použitelné?

 4) Nevím, kdo tento dataset původně zpracoval - chybí mi zdroj pro počet obyvatel Evropských zemí. Nevíte, odkud se to stáhlo? Samozřejmě si to můžu snadno najít jinde, chtěl bych ale přesně stejná čísla, aby se snad nemusel předělávat graf.

**Comment by jankrcal** [comment]
@protivinsky:
 - navrhoval bych oba výstupy přesunout do Shrnutí, s použitím šířek sloupců viz předchozí komentář
 - Ty oba dva číselníky bych spíš vynechal. U výstupní tabulky, která tyto kódy a české názvy a přiřazení obsahuje bych to jen okomentoval textově, že české názvy zemí jsou dle ČSÚ a rozdělení je dle world bank, wiki, atd. Asi bych tam ani nedával odkazy. Jakože o toto v těch datech fakt nejde.

**Comment by protivinsky** [comment]
4. Pocet obyvatel je zjevne take Eurostat - data presne odpovidaji roku 2016 zde http://appsso.eurostat.ec.europa.eu/nui/show.do?wai=true&dataset=demo_pjan

3. Osobne mi prijde trochu matouci, ze ta samotna generujici bunka oznacena neni. A ta seda mi trochu splyva s podkresem data mimo EU. Cili bych mozna dal nejaky podklad i pod tu generujici a klidne o malicko vyraznejsi, at vim kam klikat pro vzorec?

1 & 2 jsou dobre napady, souhlas - upravim podobne i ten svet.

**Comment by jankrcal** [comment]
Díky za komantáře!

4 - Díky, zdroj na počet obyvatel jsem doplnil.

3 - Označil jsem jak generující (výrazněji) tak generované buňky (méně výrazně). Data mimo EU jsou taky generovaná, proto mají stejnou barvu. Pro méně zajímavé hodnoty v tabulce navrhuju šedý text. Kontrast s šedým pozadím není nejlepší, ale nakonec o to mi jde, aby to nebylo výrazné :)

**Comment by jankrcal** [comment]
Trochu jsem doupravil dva datasety, které jsem řešil, a vytvořil jsem v složce Final dva nové soubory:
 - **Instrukce**: https://docs.google.com/document/d/1dv5ADA77rRzlY4Ww6qMpdM7UukF-cW5tGC9RKlM0Tlw/edit#
 - **Šablonu na zkopírování**: https://docs.google.com/spreadsheets/d/1YE-uxFBS15kzNNiKN1D6XllxnJ2sBH9F10B1mI_J04o/edit#gid=979818322 

**Prosím o komentáře** (stejně jako k datasetu emise EU (https://docs.google.com/spreadsheets/d/1Oi6MiPxSKRN2vlssITAqsVwjsalQazCyymNdHHc-iYg/edit#gid=979818322).

Víc toho dneska nezvládnu, jsem v autě v zácpě na cestě do Prahy a špatně se mi tu pracuje :)

**Comment by mukrop** [comment]
@jankrcal Ked budu pripravene emise CR, daj vediet. Nakoniec som prelinkovaval dokument a nekopiroval karty, pretoze su tam vzorce medzi jednotlivymi kartami dokumentu, ktore som nechcel rozhodit. Pristup k dokumentu som upravil na mna, Ondrasa a teba. Povodny dokument som oznacil na zmazanie za 2 mesiace.

**Comment by jankrcal** [comment]
Ano, tak jsem to myslel, přelinkovat dokument.

Máš na mysli: až budou připravené emise EU?

Za mě je to hotovo, můžete se prosím na klimatonu domluvit, kdo na to koukne a zkontrolujte to oproti momentálně zveřejněné verzi?

**Comment by mukrop** [comment]
Pozrie sa na to @ondraspribyla.

**Comment by jankrcal** [comment]
Paráda, dík!

**Comment by mukrop** [comment]
@jankrcal: Pozrel som sa aj na tu sablonu a instrukcie, obidve mi prisli fajn. Odpovedal som ti na komentar, uprav podla toho pripadne dany odstavec. Zo sablonovej tabulky som odstranil sheet protection, nedava to tam podla mna zmysel.

**Comment by jankrcal** [comment]
Instrukce jsem poslal.
