### ISSUE TITLE
Koncentrace CO2 (800 000 let, 2000let, 70let)

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#78]
Našel jsem datové podklady CO2 z ledovcových vrtů:
Stahl jsem je sem:
https://docs.google.com/spreadsheets/d/1FGGaYKDN7afk1E7-_utJr_bk1HIaVRldmHqT68Gn_uY/edit?usp=sharing

Původ: 
https://www.co2.earth/co2-ice-core-data

Zpracujme je do grafu... aby byl popdklad k tvrzení: "CO2 je nejvyšší za osmset tisíc let. (a pravděpodobně az 4Myr)"

**Comment by ondraspribyla** [comment]
@kikinna  Základní graf je součástí souboru... priorita je nižší než "body zlomu"... ale časem to můžeme udělat :-)

**Comment by kikinna** [comment]
@ondraspribyla Prosím doplň pro infografiku:
* Nadpis
* Podnadpis
* Popisky, komentáře a dovysvětlení toho, co se člověk má dozvědět

**Comment by ondraspribyla** [comment]
Zatím jen pro úklid: 
- v tabulce https://docs.google.com/spreadsheets/d/1BPQGQjLKMGds7jEmbEvXL5hsMU9wlOx-6LhqU0GXPqE/edit?usp=sharing
jsou data za posledních 800 000let, a poslední 2000let (z bublinek v ledu) a měření od roku 1958 (Keeling). Tímto přejmenovávám issue na Koncentrace CO2

**Comment by ondraspribyla** [comment]
Zbyva vycistit data a pridat na ne odkaz

**Comment by ondraspribyla** [comment]
Hotovo, zavírám... Děkuju za všechny verze a předělávky všem co přispívali!!!
