### ISSUE TITLE
Updatuj šablony infografik + stávající infografiky podle ořezu webu

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#80]
Uprav infografiky podle ořezu na webu - 9% nahoře, 3,5% dole + s danými změnami aktualizuj stávající infografiky (i ty, které nespadaj mimo ořez, ale aby byly sjednocené)
Zdroj #71

**Comment by mukrop** [comment]
Len upozornujem, ze 3.5% je orez aj na bokoch! (Kvoli prilis velkym okrajom, ktore potom zostavaju.)

**Comment by mukrop** [comment]
@kikinna: Toto je hotovo a moze sa zavriet, nie?

**Comment by mukrop** [comment]
Aktualny stav nam staci, mozno to so buducna este vycistime viac/inak, ale na teraz zatvaram.
