### ISSUE TITLE
Vytvorit stranky na expertne studie

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#81]
Do FrankBold máme k dispozici studii o kapacitách české přenosové soustavy. Podobných studií bude časem pravděpodobně více. Chtělo by to vymyslet jak na ně vhodně odkazovat. (Sekce "Studie" a psát k nim jednoodstavečkové výtahy?)
------
česká přenosová soustava zvládne, když se uhelné zdroje vypnou a nahradí obnovitelnými:
https://frankbold.org/sites/default/files/publikace/infolist-sit_bez_uhli.pdf 
https://frankbold.org/sites/default/files/publikace/czech_grid_without_coal_by_2030_fin_0.pdf 

doplňující studie z 12/2018 - různé scénáře:
https://frankbold.org/sites/default/files/publikace/infolist_-_citlivostni_analyza.pdf 
https://frankbold.org/sites/default/files/publikace/sensitivity_analysis_czech_grid_without_coal_by_2030.pdf

**Comment by mukrop** [comment]
Neviem, co presne si predstavujes. Chces na to samostatnu sekciu/stranku, podobne ako na ine weby? Alebo to pridat do rozcestnika inych stranok? Alebo sa na to chces odkazovat v jednotlivych infografikach?

**Comment by ondraspribyla** [comment]
Další studie, na které bychom mohli odkazovat (nutno přepsat vysvětlující texty - ton, kterým mluví Greenpeace je pro nás moc aktivistický)

Charnyho zpráva 1979 - https://www.greenpeace.org/czech/clanek/3909/jak-presne-vedci-predpovedeli-klimatickou-zmenu-v-roce-1979/
Modely Czech Globe - https://www.greenpeace.org/czech/clanek/3499/jake-bude-klima-v-cr-nadeje-jmenem-rcm-2-6/

**Comment by mukrop** [comment]
* [ ] Novy layout: Stranka studie (tak, ako je stranka infografiky).
  * Nazov studie
  * Strucne zavery
  * Predpoklady a metodika spracovania
  * Spracovatel (a komentar k nemu -- kto to je, ako pracuje, kto ho financuje, ...)
  * Obrazok (nahlad titlnej strany reportu?)
  * Link na original report studie
* [ ] Nova collection: Ako infografiky
  * Spracovat par (2-3) prvych studii, aby to malo obsah
* [ ] Pridat polozku do navigacneho menu
* [ ] Vytvorit novyu sekciu na titulku pod infografiky (zobrazovanie v blokoch ako bol povodny plan na ludi a projekty)

**Comment by mukrop** [comment]
Nahodil som nejaky draft stranky studie a sekcie studii na titulku. Nie som s tym este 100% spokojny, ale uz sa na to da divat :-P.
@crysman: Dopln prosim metadata k Charneyho sprave, ostatne dve studie z tabulky a prvy draft sprievodneho textu do sekcie na titulku.

**Comment by ondraspribyla** [comment]
Koukam a je to pěkný. Trochu jsem upravil text k AUTORI Charneyho zpravy...
a i další texty k Charneyho zprávě vyčistím tak, aby byly čitelné a
vypadaly dobře.
A musím říct, že UNGIT je fakt dobrá hračka... je super, když jsou pracovní
prostředí zábavná...

Díky

O.

**Comment by protivinsky** [comment]
Ahoj,
Ondras me pridal do projektu, tak se rovnou zapojuji - navrh studii vypada dobre, opravil jsem tam par drobnych preklepu, ale nemohu to ted pushnout zpet do vetve studie. Je potreba delat PR i u vetvi - myslel jsem si ze ne? Nebo mi jen chybi opravneni? Mohu byt v tom pripade pridan do tymu na gitu?
Diky,
Tom

**Comment by ondraspribyla** [comment]
Tome, jaké je tvoje GITHUBové jméno? Ať to může Martin zprocesovat...

**Comment by protivinsky** [comment]
Predpokladal jsem ze je viditelne v zahlavi komentare :)
Githubove jmeno: protivinsky, pripadne je to na email tomas.protivinsky@gmail.com
Diky!

**Comment by mukrop** [comment]
Ahoj @protivinsky,
Pridal som ti pristup priamo do repozitara. PR u vetvy inych ako `master` nie su potrebne.
(Ospravedlnujem sa za neskorsiu reakciu, som tyzden na dovolenke.)

**Comment by mukrop** [comment]
Zabralo to celkom dost casu, ale redesignoval som stranky studii. Som s nimi o dost spokojnejsi ako s tym prvym prototypom. Hlavne zavery studie su teraz vyraznejsie odlisene.
@ondraspribyla: Navrhujem kratsie texty v hlavnych zaveroch, ako idealny stav sa mi zda Charneyho sprava.

**Comment by protivinsky** [comment]
Diky za pridani - ja ted zrovna taky vyrazim na dovolenou, vyzkousim to znovu az budu zpet. S vetsi uhlikovou stopou bude i vetsi motivace :)

**Comment by mukrop** [comment]
Issue zatvaram, studie boli zaintegrovane.
