### ISSUE TITLE
Sdílení obsahu na sociálních sítích

### ISSUE THREAD

**Issue by kikinna** [mukrop/faktaoklimatu#82]
Teď mi došlo, že nemáme u infografik tlačítka pro sdílení obsahu (pro každou infografiku zvlášť), jak jsme od začátku zamýšleli. Je to něco, na co se zapomnělo nebo se to z nějakého důvodu odsunulo/zamítlo?

**Comment by repli2dev** [comment]
Pokud implementovat tak pouze v nějaké neoficiální formě, která nesleduje uživatele (
https://sharingbuttons.io...)

**Comment by mukrop** [comment]
@kikina: Odsunuli sme to, pretoze na spustenie to nebola nutna
funkcionalita. Stale to nevidim, ako zasadne, ale mozeme pridat.
@repli2dev: Dik za tip, tieto vyzeraju jednoducho a dobre.

**Comment by mukrop** [comment]
@kikinna Uz som to skusal a implementovat ich bude celkom v pohode. Kam ich chceme? Info o licencii sa mozno bude skracovat (#23), tak mozno pod to?

Notes to self:
* Chceme Facebook, Twitter a mail.
* Vhodny filter na obsah je {{ page.url | absolute_url | cgi_escape }}.

**Comment by mukrop** [comment]
Nezabudnut na sharing buttons prihodit Google Tag Manager event aby sme videli, ci ich ludia naozaj pouzivaju,

**Comment by mukrop** [comment]
Nejaka zakladna verzia je nasadena.
@repli2dev: Mohol by si sa prosim pozriet, ci to vsetko funguje, ako by malo? V pouzivani socialnych sieti sa vyznas viac.

**Comment by repli2dev** [comment]
@mukrop za mě OK, obojí se správně otevírá... jen GTM (podle mého zjišťování přes extension Tag Manager) loguje jen otevření modálního okna, ale nikoliv FB/Twitter.

**Comment by mukrop** [comment]
Urcite? Podla Analytiky si dnes zdielal (=klikol na) Emise skleníkových plynů ČR (detailní) 2x na Twittri a 1x na Faceboou. Suhlasi?

**Comment by repli2dev** [comment]
Sedi, v dataLayer jsem to ale nevidel.

18. 8. 2019 v 18:27, Martin Ukrop <notifications@github.com>:
