### ISSUE TITLE
odstranit justify u podnadpisu

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#83]
podnadpis
"Shromažďujeme data o klimatu a klimatické změně, která poskytují vědecké instituce (ČHMÚ, NASA, Eurostat a jiné) a zpracováváme z nich grafy a infografiky pro další použití."

má styl `justify`, což dělá potíže v mobilním zobrazení, navrhuju to odstranit, testoval jsem, jak to vypadá bez toho, a je to zcela v poho, takže není důvod to tam mít (ostatní odstavce do bloku nejsou) - je to nekonzistentní a dělá to potíže.

**Comment by mukrop** [comment]
To je bug. Na pocitaci ma vsetko `justify`, na telefone vsetko `left` (len ten jeden odstavec bol mimo).
