### ISSUE TITLE
Zatvarat polozky menu po kliku

### ISSUE THREAD

**Issue by crysman** [mukrop/faktaoklimatu#84]
sekce tvůrci je jen anchor link a dělá následující potíže při mobilním zobrazení:

1. při odzoomnutí na level takový, že je vidno na screenu i patičku při klikání na "tvůrci" v menu to nic nedělá - velmi matoucí

2. po kliknutí z menu zůstává menu otevřeno (nekonzistentně, vzhledem k ostatním položkám menu - ty se chovají standardně)

**Comment by mukrop** [comment]
1. U mna funguje v pohode. Prosim odskusaj znova, ci je to u teba naozaj tak.
2. Nekonzistentne to je len vzhladom na polozku "Uvod". Ostatne sa u mna spravaju rovnako.

Za mna je vsetko podla ocakavania, ale beriem to ako feature request, ze by sa menu mohlo po zvoleni polozky zatvarat (este netusim, ako to urobit, ale nejako by to ist mohlo).
