### ISSUE TITLE
Téma: Fosil Fuel Subsidies

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#85]
Mít infografiku na  __Fosil Fuel Subsidies__  by bylo super... a byl by to krok k "řešení".
---------
https://www.theguardian.com/environment/2019/aug/01/fossil-fuel-subsidy-cash-pay-green-energy-transition?fbclid=IwAR2tGWBXG09d6Ply_BBjhU5V8LgkXNVdOm0Kj0BUAQPIB8VcD-cR3Z_vZSo

https://www.euro.cz/byznys/deset-procent-dotaci-na-fosilni-zdroje-bude-stacit-na-zelenou-revoluci-1461275?fbclid=IwAR2-Ihg5Kml2KlLpVy8h9j-MCj9pRChHxHhrxHFVDMuro7fhIc1byAs1230

**Comment by kikinna** [comment]
To je rozhodně zajímavý téma. Co vše by jsi rád v rámci tohoto tématu do infografiky zahrnul?

**Comment by ondraspribyla** [comment]
Visí to tu dlouoho bez pokroku. Presunul jsem do sekce "Napady na infografiky a studie" na WIKI
