### ISSUE TITLE
Typo v podnadpise infografiky

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#87]
Ako pisal Pavouk (vid #64), v emise-vybrane-staty je "nadbytečná tučná tečka v první větě pod nadpisem".

**Comment by kikinna** [comment]
Jej, pardon, já nahrála špatnou verzi (u sebe to mám už opravené). Díky za upozornění!

**Comment by mukrop** [comment]
Toto uz je hotovo.
