### ISSUE TITLE
Zistit podrobnosti o tlaci na textil

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#92]
* Zistit moznosti rozmerov, materialov a cien.
* Povodne plachty na poulicnej akademii boli cca 1.5m x 2m.
* Vyhladovo ako transparent na Tyden za klima.

**Comment by ondraspribyla** [comment]
FFF chystají pouliční akademie v Praze i jiných městech. Z toho plyne: 
- pokud se nám podaří zajistit tisk, pomůže to pouličním akademiím i jinde... 
- FFF by mohly mít prostředky na zaplacení bannerů

**Comment by mukrop** [comment]
Zhrnutie relevantnych ponuk:
* [**PrintHouse**](http://www.tiskni.to/)  
Lity banner + UV tisk 4/0: 1.3m x 2m za 572 Kc, 1.5m x 2.25m za 742 Kc, 2m x 3m za1.320 Kc  
Textil Samba + UV tisk, 1m x3m za 1.470 Kc (ine rozmery som sa nepytal)  
dodavka DPD 150 Kc (nad 150cm 380 Kc)  
ceny su bez DPH
* [**VUVeL**](https://www.vri.cz/cz/spoluprace__s_praxi/dtp_sluzby_(velkoformatove_tisky__graficke_zpracovani_dokumentu)/velkoformatovy_tisk_na_plotterech)  
potisk textilu (Samba), rola 130cm, bezny meter za 660 Kc bez DPH
* [**CopyCentrum.cz**](http://www.copycentrum.cz/)  
Tisk na banner, 800 Kc za 1 m^2

**Comment by mukrop** [comment]
Tlac hotova, kurier by to mohol doniest do Brna tak v pondelok.
Info k objednavke spisane na gDrive:
https://drive.google.com/drive/folders/1INAj4IJT6R0_21Jj00xTqqHLPLslDeFr
