### ISSUE TITLE
Web hosting: Skontrolovat limity na emailove adresy

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#93]
Ondras by chcel: ondras.pribyla@faktaoklimatu.cz

**Comment by repli2dev** [comment]
(Potenciálně to může vyhovovat podmínkám GApps pro neziskový sektor...)

**Comment by mukrop** [comment]
Obavam sa, ze na to potrebujeme byt zapisany na rejstrikovom sude ako spolok (zda sa mi, podla toho, ako to riesili Instruktori Brno). Ale pozriem sa, dik za tip.

**Comment by mukrop** [comment]
GSuite for non-profits vyzaduje byt registrovana entita.
Povysil som tarif u OneBit, mamte teraz 4 adresy. Zriadil som webmaster@faktaoklimatu a jednu Ondrasovi.
