### ISSUE TITLE
Data: CO2 koncentrace za posledních 200 let

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#96]
Tady jsou data: https://data.giss.nasa.gov/modelforce/ghgases/Fig1A.ext.txt

Dáte je někdo do googlesheetua uděláte první drafty grafů? 
Příp. chcete napsat text pro data. Související Issue je #78.

**Comment by crysman** [comment]
du na to

**Comment by crysman** [comment]
@ondraspribyla tak jsem něco vyrobil. výsledek zde:
https://drive.google.com/drive/folders/1aqdQK6tEwhaCVvTY2nKttaJKXp1X-02Z

chcete tam i ty future predictions?

PS: a protože mě baví bashovat, tu je, jak jsem se k datům dostal :$) (samo možno znovupoužít s úpravami na libovolný další podobně formátovaný dokument - dávám to sem jako inspiraci):

```
wget https://data.giss.nasa.gov/modelforce/ghgases/Fig1A.ext.txt -qO - | sed -n 6,55p | grep -oE "[[:digit:]]{4}[[:space:]]{2}[0-9.]+" | sort | sed -E 's~ +~\t~'
```

**Comment by ondraspribyla** [comment]
Data o CO2 jsem přesunoul do souhrnného souboru, který obsahuje data za 800000let, 2000let a současná měření - KEELING. Link viz níže, Kika z toho souboru zpracovává grafiky. Tímto zavírám issue jako duplicitní, další diskuse patří k issue #78  https://docs.google.com/spreadsheets/d/1BPQGQjLKMGds7jEmbEvXL5hsMU9wlOx-6LhqU0GXPqE/edit?usp=sharing
