### ISSUE TITLE
Data: Výroba a spotřeba elektřiny v ČR (flowchart)

### ISSUE THREAD

**Issue by ondraspribyla** [mukrop/faktaoklimatu#97]
https://m.tzb-info.cz/elektroenergetika/17553-vyroba-a-spotreba-elektriny-v-cr-v-roce-2017

**Comment by ondraspribyla** [comment]
Současná práce je v https://docs.google.com/spreadsheets/d/1p1wQ-1eWNjnkeookXZK-t5W31mzAwfpIgqXmtgj1_cI/edit?usp=sharing

Je potřeba
- vypočítat / zkontrolovat EMISE ELEKTRAREN (Olda)
- zpracovat grafiku (SANKEY DIAGRAM) (Kika)

**Comment by ondraspribyla** [comment]
##Komentáře od OLDY:

- Spotřebu dle sektorů LZE najít v Roční zpráva o provozu ES ČR2018, dostupné na stránkách ERÚ - je na straně 15 tohoto dokumentu http://www.eru.cz/documents/10540/4580207/Rocni_zprava_provoz_ES_2018.pdf/1420388b-8eb6-4424-9ad9-c06a57b5326c Koncová spotřeba domácností činí cca 25 %.

- Než mě napadlo podívat se na stránky ERÚ, hledal jsem u ČSÚ. Tam se mi v oficiální sekci podařilo najít spotřebu dle NACE kodu (klasifikaci ekonomických činností) zde https://www.czso.cz/documents/10180/61661397/1501421802.pdf/74c3a12e-0c1b-4338-b690-2b479f077b32?version=1.2 Domácnosti zde z pochopitelných důvodů nejsou. Spotřebu dle sektorů se mi podařilo najít až ve Statistické ročence Pardubického kraje (?) https://www.czso.cz/csu/czso/14-energetika-h9bylio6su Obsažena jsou nicméně data pro celou ČR (pro rok 2016): https://www.czso.cz/documents/10180/46120827/1714103.xlsx/1758eff4-ba55-4e4a-b0c1-e999e39567f2?version=1.3

- Dalším dostupným zdrojem jsou stránky European Environment Agency. Ty ale zobrazují data pouze do roku 2014: https://www.eea.europa.eu/data-and-maps/daviz/final-energy-consumption-of-electricity-2#tab-googlechartid_chart_21_filters=%7B%22rowFilters%22%3A%7B%7D%3B%22columnFilters%22%3A%7B%22pre_config_ugeo%22%3A%5B%22Czech%20Republic%22%5D%7D%7D

**Comment by ondraspribyla** [comment]
##Další odkazy: 
pro inspiraci zasílám odkaz na stránky Lawrence Livermore National Laboratory z US: https://flowcharts.llnl.gov/ kteří zpracovali diagram pro CO2 a všechny energetické zdroje/oblasti spotřeby: https://flowcharts.llnl.gov/content/assets/images/charts/Carbon/Carbon_2014_United-States.png

V minulosti dokonce zpracovali energetické toky i pro ČR (pro rok 2011): https://flowcharts.llnl.gov/content/assets/images/charts/Energy/ENERGY_2011_CZECH.png

Podobně zpracovali energetické toky pro ČR i na stránkách eurostatu: https://ec.europa.eu/eurostat/cache/sankey/sankey.html?geos=CZ&year=2017&unit=KTOE&fuels=TOTAL&highlight=_&nodeDisagg=0101000000000&flowDisagg=false&translateX=192.1785401073995&translateY=121.71959217118783&scale=0.6712688031959795&language=EN#0

**Comment by mukrop** [comment]
Assigned to Olda.

**Comment by jankrcal** [comment]
(na základě zpětné vazby od mojí ženy, když jsem ji web ukazoval)

Nevím, jakou máte vizi o tomto, ale přišlo by mi skvělý to nějak provázat s detailním grafem emisí v ČR, kde uvádíme konkrétní hnědouhelné elektrárny. Aby bylo snadno vidět, jak nadproporční vůči produkci elektřiny tyto jejich emise jsou.

**Comment by ondraspribyla** [comment]
TU je výstup od Pavla Ulbricha: 
[vyroba_a_spotreba_elektriny_markII.pdf](https://github.com/mukrop/faktaoklimatu/files/3752826/vyroba_a_spotreba_elektriny_markII.pdf)

**Comment by ondraspribyla** [comment]
Po dlouhé výměně nakonec hotovo!
