### ISSUE TITLE
Napisat kratky "style & typography guide"

### ISSUE THREAD

**Issue by mukrop** [mukrop/faktaoklimatu#98]
Spisat kratky dokument, ktory bude obsahovat:
* Veci, ktore casto zabudame (medzery pred stupnami Celsia, rozdelovniky vs. pomlcky, medzerty pred jednotkami, desatinna ciarka vs. bodka, ...).
* Aku typografiu pouzivame (tj. poseme &ndash; alebo unicode znak pre pomlcku?).
* Par zasad k obsahu textov (su faktograficke, nie aktivisticke, vyhybame sa nepodlozenym tvrdeniam a pod.).

Podla takto spisanych zasad potom zjednotit existujuce texty (napr. tie pomlcky).

**Comment by ondraspribyla** [comment]
kopiruju do #234 a zavírám.
